// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backlogs.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createBacklog = `-- name: CreateBacklog :one

INSERT INTO backlogs (project_id, name, description, position)
VALUES (
    $1,
    $2,
    $3,
    COALESCE((SELECT MAX(position) + 1 FROM backlogs WHERE project_id = $1), 0)
)
RETURNING id, project_id, name, description, position, created_at, updated_at
`

type CreateBacklogParams struct {
	ProjectID   uuid.UUID `json:"project_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}

// Backlogs have no owner column of their own; ownership is always checked
// through the parent project. CreateBacklog/ListBacklogsByProject trust the
// caller to have already verified project ownership (e.g. via
// project.Service.Get), while the single-backlog queries join to projects so
// a foreign backlog is indistinguishable from a missing one.
func (q *Queries) CreateBacklog(ctx context.Context, arg CreateBacklogParams) (Backlog, error) {
	row := q.db.QueryRow(ctx, createBacklog, arg.ProjectID, arg.Name, arg.Description)
	var i Backlog
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBacklogForOwner = `-- name: DeleteBacklogForOwner :execrows
DELETE FROM backlogs b
USING projects p
WHERE b.id = $1 AND b.project_id = p.id AND p.owner_user_id = $2
`

type DeleteBacklogForOwnerParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) DeleteBacklogForOwner(ctx context.Context, arg DeleteBacklogForOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBacklogForOwner, arg.ID, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBacklogForOwner = `-- name: GetBacklogForOwner :one
SELECT b.id, b.project_id, b.name, b.description, b.position, b.created_at, b.updated_at
FROM backlogs b
JOIN projects p ON p.id = b.project_id
WHERE b.id = $1 AND p.owner_user_id = $2
`

type GetBacklogForOwnerParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) GetBacklogForOwner(ctx context.Context, arg GetBacklogForOwnerParams) (Backlog, error) {
	row := q.db.QueryRow(ctx, getBacklogForOwner, arg.ID, arg.OwnerUserID)
	var i Backlog
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBacklogsByProject = `-- name: ListBacklogsByProject :many
SELECT id, project_id, name, description, position, created_at, updated_at FROM backlogs WHERE project_id = $1 ORDER BY position ASC, created_at ASC
`

func (q *Queries) ListBacklogsByProject(ctx context.Context, projectID uuid.UUID) ([]Backlog, error) {
	rows, err := q.db.Query(ctx, listBacklogsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Backlog{}
	for rows.Next() {
		var i Backlog
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBacklogForOwner = `-- name: UpdateBacklogForOwner :one
UPDATE backlogs b
SET name = $3, description = $4, position = $5, updated_at = now()
FROM projects p
WHERE b.id = $1 AND b.project_id = p.id AND p.owner_user_id = $2
RETURNING b.id, b.project_id, b.name, b.description, b.position, b.created_at, b.updated_at
`

type UpdateBacklogForOwnerParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Position    int32     `json:"position"`
}

func (q *Queries) UpdateBacklogForOwner(ctx context.Context, arg UpdateBacklogForOwnerParams) (Backlog, error) {
	row := q.db.QueryRow(ctx, updateBacklogForOwner,
		arg.ID,
		arg.OwnerUserID,
		arg.Name,
		arg.Description,
		arg.Position,
	)
	var i Backlog
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
