// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backlog_progress_events.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBacklogProgressEvent = `-- name: CreateBacklogProgressEvent :one
INSERT INTO backlog_progress_events (backlog_id, from_progress, to_progress, actor_kind, actor_user_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, backlog_id, from_progress, to_progress, actor_kind, actor_user_id, occurred_at
`

type CreateBacklogProgressEventParams struct {
	BacklogID    uuid.UUID   `json:"backlog_id"`
	FromProgress string      `json:"from_progress"`
	ToProgress   string      `json:"to_progress"`
	ActorKind    string      `json:"actor_kind"`
	ActorUserID  pgtype.UUID `json:"actor_user_id"`
}

func (q *Queries) CreateBacklogProgressEvent(ctx context.Context, arg CreateBacklogProgressEventParams) (BacklogProgressEvent, error) {
	row := q.db.QueryRow(ctx, createBacklogProgressEvent,
		arg.BacklogID,
		arg.FromProgress,
		arg.ToProgress,
		arg.ActorKind,
		arg.ActorUserID,
	)
	var i BacklogProgressEvent
	err := row.Scan(
		&i.ID,
		&i.BacklogID,
		&i.FromProgress,
		&i.ToProgress,
		&i.ActorKind,
		&i.ActorUserID,
		&i.OccurredAt,
	)
	return i, err
}

const listBacklogProgressEventsByBacklog = `-- name: ListBacklogProgressEventsByBacklog :many
SELECT id, backlog_id, from_progress, to_progress, actor_kind, actor_user_id, occurred_at FROM backlog_progress_events WHERE backlog_id = $1 ORDER BY occurred_at ASC
`

func (q *Queries) ListBacklogProgressEventsByBacklog(ctx context.Context, backlogID uuid.UUID) ([]BacklogProgressEvent, error) {
	rows, err := q.db.Query(ctx, listBacklogProgressEventsByBacklog, backlogID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BacklogProgressEvent{}
	for rows.Next() {
		var i BacklogProgressEvent
		if err := rows.Scan(
			&i.ID,
			&i.BacklogID,
			&i.FromProgress,
			&i.ToProgress,
			&i.ActorKind,
			&i.ActorUserID,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
