// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backlogs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBacklog = `-- name: CreateBacklog :one

INSERT INTO backlogs (project_id, name, description, position, start_date, due_on, priority, progress)
VALUES (
    $1,
    $2,
    $3,
    COALESCE((SELECT MAX(position) + 1 FROM backlogs WHERE project_id = $1), 0),
    $4,
    $5,
    $6,
    $7
)
RETURNING id, project_id, name, description, position, created_at, updated_at, start_date, due_on, priority, progress
`

type CreateBacklogParams struct {
	ProjectID   uuid.UUID   `json:"project_id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	StartDate   pgtype.Date `json:"start_date"`
	DueOn       pgtype.Date `json:"due_on"`
	Priority    string      `json:"priority"`
	Progress    string      `json:"progress"`
}

// Backlogs have no owner column of their own; ownership is always checked
// through the parent project. CreateBacklog/ListBacklogsByProject trust the
// caller to have already verified project ownership (e.g. via
// project.Service.Get), while the single-backlog queries join to projects so
// a foreign backlog is indistinguishable from a missing one.
func (q *Queries) CreateBacklog(ctx context.Context, arg CreateBacklogParams) (Backlog, error) {
	row := q.db.QueryRow(ctx, createBacklog,
		arg.ProjectID,
		arg.Name,
		arg.Description,
		arg.StartDate,
		arg.DueOn,
		arg.Priority,
		arg.Progress,
	)
	var i Backlog
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartDate,
		&i.DueOn,
		&i.Priority,
		&i.Progress,
	)
	return i, err
}

const deleteBacklogForOwner = `-- name: DeleteBacklogForOwner :execrows
DELETE FROM backlogs b
WHERE b.id = $1
  AND EXISTS (
    SELECT 1 FROM project_members pm
    WHERE pm.project_id = b.project_id AND pm.user_id = $2 AND pm.role IN ('member', 'owner')
  )
`

type DeleteBacklogForOwnerParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) DeleteBacklogForOwner(ctx context.Context, arg DeleteBacklogForOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBacklogForOwner, arg.ID, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBacklogForOwner = `-- name: GetBacklogForOwner :one
SELECT b.id, b.project_id, b.name, b.description, b.position, b.created_at, b.updated_at, b.start_date, b.due_on, b.priority, b.progress
FROM backlogs b
WHERE b.id = $1
  AND EXISTS (
    SELECT 1 FROM project_members pm
    WHERE pm.project_id = b.project_id AND pm.user_id = $2
  )
`

type GetBacklogForOwnerParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) GetBacklogForOwner(ctx context.Context, arg GetBacklogForOwnerParams) (Backlog, error) {
	row := q.db.QueryRow(ctx, getBacklogForOwner, arg.ID, arg.OwnerUserID)
	var i Backlog
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartDate,
		&i.DueOn,
		&i.Priority,
		&i.Progress,
	)
	return i, err
}

const getBacklogProjectID = `-- name: GetBacklogProjectID :one

SELECT project_id FROM backlogs WHERE id = $1
`

// GetBacklogProjectID is the lightweight project lookup
// requireTokenResourceProject (internal/http, issue #66) uses to enforce a
// bearer token's project boundary on a single-backlog URL, without
// GetBacklogForOwner's owner join — a token has no session owner to join
// against.
func (q *Queries) GetBacklogProjectID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getBacklogProjectID, id)
	var project_id uuid.UUID
	err := row.Scan(&project_id)
	return project_id, err
}

const listBacklogsByProject = `-- name: ListBacklogsByProject :many
SELECT id, project_id, name, description, position, created_at, updated_at, start_date, due_on, priority, progress FROM backlogs
WHERE project_id = $1
  AND ($2::text = '' OR priority = $2)
  AND ($3::text = '' OR progress = $3)
ORDER BY
  (CASE WHEN $4::boolean THEN
     CASE priority WHEN 'urgent' THEN 4 WHEN 'high' THEN 3 WHEN 'medium' THEN 2 WHEN 'low' THEN 1 ELSE 0 END
   ELSE 0 END) DESC,
  (CASE WHEN $5::boolean THEN
     CASE progress WHEN 'not_started' THEN 1 WHEN 'in_progress' THEN 2 WHEN 'on_hold' THEN 3 WHEN 'done' THEN 4 ELSE 0 END
   ELSE 0 END) ASC,
  position ASC, created_at ASC
`

type ListBacklogsByProjectParams struct {
	ProjectID      uuid.UUID `json:"project_id"`
	Priority       string    `json:"priority"`
	Progress       string    `json:"progress"`
	SortByPriority bool      `json:"sort_by_priority"`
	SortByProgress bool      `json:"sort_by_progress"`
}

// ListBacklogsByProject's priority and progress filters and sorts follow the
// same "empty/false disables it" convention as internal/task's
// ListTasksByProject. Sorting by priority ranks urgent > high > medium > low;
// sorting by progress runs the other way, not_started first through done, so
// the order reads as the work advancing (and matches the Board view's
// left-to-right axis). Both fall back to the usual position/created_at order
// as a tiebreak. sort_by_priority and sort_by_progress are mutually exclusive
// in practice — internal/backlog sets at most one from a single ?sort=.
func (q *Queries) ListBacklogsByProject(ctx context.Context, arg ListBacklogsByProjectParams) ([]Backlog, error) {
	rows, err := q.db.Query(ctx, listBacklogsByProject,
		arg.ProjectID,
		arg.Priority,
		arg.Progress,
		arg.SortByPriority,
		arg.SortByProgress,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Backlog{}
	for rows.Next() {
		var i Backlog
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartDate,
			&i.DueOn,
			&i.Priority,
			&i.Progress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reorderBacklogs = `-- name: ReorderBacklogs :exec

WITH ordered AS (
    SELECT id, (ord - 1)::int AS position
    FROM unnest($2::uuid[]) WITH ORDINALITY AS t(id, ord)
)
UPDATE backlogs
SET position = ordered.position, updated_at = now()
FROM ordered
WHERE backlogs.id = ordered.id
  AND backlogs.project_id = $1
`

type ReorderBacklogsParams struct {
	ProjectID  uuid.UUID   `json:"project_id"`
	BacklogIds []uuid.UUID `json:"backlog_ids"`
}

// ReorderBacklogs resequences a project's backlogs to backlog_ids' given
// order (position 0 for the first id, 1 for the second, ...) in a single
// statement, the same all-or-nothing shape as internal/task's ReorderTasks
// (issue #79). internal/backlog.Service.Reorder checks backlog_ids is
// exactly the project's current backlog set before calling this.
func (q *Queries) ReorderBacklogs(ctx context.Context, arg ReorderBacklogsParams) error {
	_, err := q.db.Exec(ctx, reorderBacklogs, arg.ProjectID, arg.BacklogIds)
	return err
}

const updateBacklogForOwner = `-- name: UpdateBacklogForOwner :one
UPDATE backlogs b
SET name = $2, description = $3, position = $4, start_date = $5, due_on = $6, priority = $7, progress = $8, updated_at = now()
WHERE b.id = $1
  AND EXISTS (
    SELECT 1 FROM project_members pm
    WHERE pm.project_id = b.project_id AND pm.user_id = $9 AND pm.role IN ('member', 'owner')
  )
RETURNING b.id, b.project_id, b.name, b.description, b.position, b.created_at, b.updated_at, b.start_date, b.due_on, b.priority, b.progress
`

type UpdateBacklogForOwnerParams struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Position    int32       `json:"position"`
	StartDate   pgtype.Date `json:"start_date"`
	DueOn       pgtype.Date `json:"due_on"`
	Priority    string      `json:"priority"`
	Progress    string      `json:"progress"`
	OwnerUserID uuid.UUID   `json:"owner_user_id"`
}

// UpdateBacklogForOwner overwrites every editable column, so start_date/due_on
// must arrive already resolved: backlog.Service reads the current row first and
// fills in whatever the PATCH body left out (see its Update).
func (q *Queries) UpdateBacklogForOwner(ctx context.Context, arg UpdateBacklogForOwnerParams) (Backlog, error) {
	row := q.db.QueryRow(ctx, updateBacklogForOwner,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Position,
		arg.StartDate,
		arg.DueOn,
		arg.Priority,
		arg.Progress,
		arg.OwnerUserID,
	)
	var i Backlog
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartDate,
		&i.DueOn,
		&i.Priority,
		&i.Progress,
	)
	return i, err
}
