// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: epics.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignTasksToEpic = `-- name: AssignTasksToEpic :execrows
UPDATE tasks t
SET epic_id = e.id, backlog_id = e.backlog_id, updated_at = now()
FROM epics e
WHERE e.id = $1
  AND t.id = ANY($2::uuid[])
  AND t.project_id = e.project_id
`

type AssignTasksToEpicParams struct {
	EpicID  uuid.UUID   `json:"epic_id"`
	TaskIds []uuid.UUID `json:"task_ids"`
}

// AssignTasksToEpic files the named tasks under the epic, writing the epic's
// own backlog onto each in the same statement — a task's epic and backlog
// must agree (000032), and this is the one write that can move a task into an
// epic without going through internal/task.
//
// The project_id check is what stops an epic from adopting another project's
// task; the row count tells the caller whether every id actually matched, so
// a foreign or missing id rolls the whole set back rather than silently
// moving the rest.
func (q *Queries) AssignTasksToEpic(ctx context.Context, arg AssignTasksToEpicParams) (int64, error) {
	result, err := q.db.Exec(ctx, assignTasksToEpic, arg.EpicID, arg.TaskIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearEpicTasksExcept = `-- name: ClearEpicTasksExcept :exec

UPDATE tasks
SET epic_id = NULL, updated_at = now()
WHERE epic_id = $1
  AND NOT (id = ANY($2::uuid[]))
`

type ClearEpicTasksExceptParams struct {
	EpicID  pgtype.UUID `json:"epic_id"`
	TaskIds []uuid.UUID `json:"task_ids"`
}

// SetEpicTasks is the declarative half of "which tasks are in this epic": the
// caller sends the whole set, and these two statements make the table match
// it inside one transaction (internal/epic.Service.SetTasks). A per-task
// PATCH loop could leave a half-applied epic behind if one call failed;
// moving several tasks at once is exactly the operation that must not.
// ClearEpicTasksExcept unfiles every task currently in the epic that the new
// set no longer names. The tasks keep their backlog — dropping out of an epic
// returns a task to sitting directly in it, the same as deleting the epic.
func (q *Queries) ClearEpicTasksExcept(ctx context.Context, arg ClearEpicTasksExceptParams) error {
	_, err := q.db.Exec(ctx, clearEpicTasksExcept, arg.EpicID, arg.TaskIds)
	return err
}

const countTasksInProjectByIDs = `-- name: CountTasksInProjectByIDs :one
SELECT COUNT(*) FROM tasks
WHERE project_id = $1
  AND id = ANY($2::uuid[])
`

type CountTasksInProjectByIDsParams struct {
	ProjectID uuid.UUID   `json:"project_id"`
	TaskIds   []uuid.UUID `json:"task_ids"`
}

// CountTasksInProjectByIDs is SetEpicTasks' pre-check: how many of the given
// ids are really tasks in the epic's project. internal/epic rejects the whole
// request before writing anything when the count falls short, so a foreign or
// missing id is refused rather than rolled back — the guarantee then holds
// independently of transaction semantics, which is also what lets the
// in-memory fake (dbtest) reproduce it.
func (q *Queries) CountTasksInProjectByIDs(ctx context.Context, arg CountTasksInProjectByIDsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTasksInProjectByIDs, arg.ProjectID, arg.TaskIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEpic = `-- name: CreateEpic :one

INSERT INTO epics (project_id, backlog_id, name, description, position, start_date, due_on, priority, progress, default_linked_gitlab_project_id, base_branch, allowed_scope, forbidden_scope, assignee_user_id, estimated_points)
VALUES (
    $1,
    $2,
    $3,
    $4,
    COALESCE((SELECT MAX(position) + 1 FROM epics WHERE project_id = $1), 0),
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14
)
RETURNING id, project_id, backlog_id, name, description, position, start_date, due_on, priority, progress, assignee_user_id, base_branch, allowed_scope, forbidden_scope, default_linked_gitlab_project_id, created_at, updated_at, estimated_points
`

type CreateEpicParams struct {
	ProjectID                    uuid.UUID   `json:"project_id"`
	BacklogID                    pgtype.UUID `json:"backlog_id"`
	Name                         string      `json:"name"`
	Description                  string      `json:"description"`
	StartDate                    pgtype.Date `json:"start_date"`
	DueOn                        pgtype.Date `json:"due_on"`
	Priority                     string      `json:"priority"`
	Progress                     string      `json:"progress"`
	DefaultLinkedGitlabProjectID pgtype.UUID `json:"default_linked_gitlab_project_id"`
	BaseBranch                   string      `json:"base_branch"`
	AllowedScope                 string      `json:"allowed_scope"`
	ForbiddenScope               string      `json:"forbidden_scope"`
	AssigneeUserID               pgtype.UUID `json:"assignee_user_id"`
	EstimatedPoints              pgtype.Int4 `json:"estimated_points"`
}

// Epics (000032) are the optional rung between a backlog and its tasks.
// Like backlogs they have no owner column of their own: ownership is always
// checked through the parent project. CreateEpic/ListEpicsByProject trust the
// caller to have already verified project access (e.g. via
// project.Service.Authorize), while the single-epic queries join to
// project_members so a foreign epic is indistinguishable from a missing one.
//
// Every column here mirrors backlogs.sql's, deliberately — see the 000032
// migration. backlog_id is the one addition, and it is nullable: an epic
// outside any backlog is the Unclassified group, exactly as an unfiled task
// is. estimated_points (000033) is the second, and is nullable for a reason
// of its own: NULL means "nobody has estimated this epic", which is not the
// same statement as any number, least of all 0.
func (q *Queries) CreateEpic(ctx context.Context, arg CreateEpicParams) (Epic, error) {
	row := q.db.QueryRow(ctx, createEpic,
		arg.ProjectID,
		arg.BacklogID,
		arg.Name,
		arg.Description,
		arg.StartDate,
		arg.DueOn,
		arg.Priority,
		arg.Progress,
		arg.DefaultLinkedGitlabProjectID,
		arg.BaseBranch,
		arg.AllowedScope,
		arg.ForbiddenScope,
		arg.AssigneeUserID,
		arg.EstimatedPoints,
	)
	var i Epic
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BacklogID,
		&i.Name,
		&i.Description,
		&i.Position,
		&i.StartDate,
		&i.DueOn,
		&i.Priority,
		&i.Progress,
		&i.AssigneeUserID,
		&i.BaseBranch,
		&i.AllowedScope,
		&i.ForbiddenScope,
		&i.DefaultLinkedGitlabProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EstimatedPoints,
	)
	return i, err
}

const deleteEpicForOwner = `-- name: DeleteEpicForOwner :execrows
DELETE FROM epics e
WHERE e.id = $1
  AND EXISTS (
    SELECT 1 FROM project_members pm
    WHERE pm.project_id = e.project_id AND pm.user_id = $2 AND pm.role IN ('member', 'owner')
  )
`

type DeleteEpicForOwnerParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) DeleteEpicForOwner(ctx context.Context, arg DeleteEpicForOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEpicForOwner, arg.ID, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEpicForOwner = `-- name: GetEpicForOwner :one
SELECT e.id, e.project_id, e.backlog_id, e.name, e.description, e.position, e.start_date, e.due_on, e.priority, e.progress, e.assignee_user_id, e.base_branch, e.allowed_scope, e.forbidden_scope, e.default_linked_gitlab_project_id, e.created_at, e.updated_at, e.estimated_points
FROM epics e
WHERE e.id = $1
  AND EXISTS (
    SELECT 1 FROM project_members pm
    WHERE pm.project_id = e.project_id AND pm.user_id = $2
  )
`

type GetEpicForOwnerParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) GetEpicForOwner(ctx context.Context, arg GetEpicForOwnerParams) (Epic, error) {
	row := q.db.QueryRow(ctx, getEpicForOwner, arg.ID, arg.OwnerUserID)
	var i Epic
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BacklogID,
		&i.Name,
		&i.Description,
		&i.Position,
		&i.StartDate,
		&i.DueOn,
		&i.Priority,
		&i.Progress,
		&i.AssigneeUserID,
		&i.BaseBranch,
		&i.AllowedScope,
		&i.ForbiddenScope,
		&i.DefaultLinkedGitlabProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EstimatedPoints,
	)
	return i, err
}

const getEpicIssueDestination = `-- name: GetEpicIssueDestination :one
SELECT default_linked_gitlab_project_id, backlog_id FROM epics WHERE id = $1
`

type GetEpicIssueDestinationRow struct {
	DefaultLinkedGitlabProjectID pgtype.UUID `json:"default_linked_gitlab_project_id"`
	BacklogID                    pgtype.UUID `json:"backlog_id"`
}

// GetEpicIssueDestination is the create-time lookup internal/task uses to
// resolve where a new task's issue is filed: the epic's own link, and the
// backlog it belongs to so the chain can fall through to that backlog's link
// and then the project default.
func (q *Queries) GetEpicIssueDestination(ctx context.Context, id uuid.UUID) (GetEpicIssueDestinationRow, error) {
	row := q.db.QueryRow(ctx, getEpicIssueDestination, id)
	var i GetEpicIssueDestinationRow
	err := row.Scan(&i.DefaultLinkedGitlabProjectID, &i.BacklogID)
	return i, err
}

const getEpicProjectID = `-- name: GetEpicProjectID :one
SELECT project_id FROM epics WHERE id = $1
`

// GetEpicProjectID is the lightweight project lookup
// requireTokenResourceProject (internal/http) uses to enforce a bearer
// token's project boundary on a single-epic URL, without GetEpicForOwner's
// member join — a token has no session owner to join against.
func (q *Queries) GetEpicProjectID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getEpicProjectID, id)
	var project_id uuid.UUID
	err := row.Scan(&project_id)
	return project_id, err
}

const getEpicTaskDefaults = `-- name: GetEpicTaskDefaults :one
SELECT base_branch, allowed_scope, forbidden_scope, backlog_id FROM epics WHERE id = $1
`

type GetEpicTaskDefaultsRow struct {
	BaseBranch     string      `json:"base_branch"`
	AllowedScope   string      `json:"allowed_scope"`
	ForbiddenScope string      `json:"forbidden_scope"`
	BacklogID      pgtype.UUID `json:"backlog_id"`
}

// GetEpicTaskDefaults is GetBacklogTaskDefaults' epic-rung twin: the
// lightweight lookup internal/task's Context uses to resolve a task's epic's
// base_branch/allowed_scope/forbidden_scope. The two are resolved per field
// (epic value if non-empty, else the backlog's), not per object, so an epic
// that sets only base_branch still inherits its backlog's scope.
func (q *Queries) GetEpicTaskDefaults(ctx context.Context, id uuid.UUID) (GetEpicTaskDefaultsRow, error) {
	row := q.db.QueryRow(ctx, getEpicTaskDefaults, id)
	var i GetEpicTaskDefaultsRow
	err := row.Scan(
		&i.BaseBranch,
		&i.AllowedScope,
		&i.ForbiddenScope,
		&i.BacklogID,
	)
	return i, err
}

const listEpicsByProject = `-- name: ListEpicsByProject :many
SELECT
  e.id, e.project_id, e.backlog_id, e.name, e.description, e.position, e.created_at, e.updated_at,
  e.start_date, e.due_on, e.priority, e.progress, e.default_linked_gitlab_project_id, e.base_branch,
  e.allowed_scope, e.forbidden_scope, e.assignee_user_id, e.estimated_points,
  COUNT(t.id) AS task_count,
  COUNT(t.id) FILTER (WHERE t.status = 'closed') AS closed_task_count
FROM epics e
LEFT JOIN tasks t ON t.epic_id = e.id
WHERE e.project_id = $1
  AND ($2::uuid IS NULL OR e.backlog_id = $2)
  AND (NOT $3::boolean OR e.backlog_id IS NULL)
  AND ($4::text = '' OR e.priority = $4)
  AND ($5::text = '' OR e.progress = $5)
  AND ($6::uuid IS NULL OR e.assignee_user_id = $6)
  AND (NOT $7::boolean OR e.assignee_user_id IS NULL)
GROUP BY e.id
ORDER BY
  (CASE WHEN $8::boolean THEN
     CASE e.priority WHEN 'urgent' THEN 4 WHEN 'high' THEN 3 WHEN 'medium' THEN 2 WHEN 'low' THEN 1 ELSE 0 END
   ELSE 0 END) DESC,
  (CASE WHEN $9::boolean THEN
     CASE e.progress WHEN 'not_started' THEN 1 WHEN 'in_progress' THEN 2 WHEN 'on_hold' THEN 3 WHEN 'done' THEN 4 ELSE 0 END
   ELSE 0 END) ASC,
  e.position ASC, e.created_at ASC
`

type ListEpicsByProjectParams struct {
	ProjectID          uuid.UUID   `json:"project_id"`
	BacklogID          pgtype.UUID `json:"backlog_id"`
	BacklogUnfiled     bool        `json:"backlog_unfiled"`
	Priority           string      `json:"priority"`
	Progress           string      `json:"progress"`
	AssigneeUserID     pgtype.UUID `json:"assignee_user_id"`
	AssigneeUnassigned bool        `json:"assignee_unassigned"`
	SortByPriority     bool        `json:"sort_by_priority"`
	SortByProgress     bool        `json:"sort_by_progress"`
}

type ListEpicsByProjectRow struct {
	ID                           uuid.UUID          `json:"id"`
	ProjectID                    uuid.UUID          `json:"project_id"`
	BacklogID                    pgtype.UUID        `json:"backlog_id"`
	Name                         string             `json:"name"`
	Description                  string             `json:"description"`
	Position                     int32              `json:"position"`
	CreatedAt                    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                    pgtype.Timestamptz `json:"updated_at"`
	StartDate                    pgtype.Date        `json:"start_date"`
	DueOn                        pgtype.Date        `json:"due_on"`
	Priority                     string             `json:"priority"`
	Progress                     string             `json:"progress"`
	DefaultLinkedGitlabProjectID pgtype.UUID        `json:"default_linked_gitlab_project_id"`
	BaseBranch                   string             `json:"base_branch"`
	AllowedScope                 string             `json:"allowed_scope"`
	ForbiddenScope               string             `json:"forbidden_scope"`
	AssigneeUserID               pgtype.UUID        `json:"assignee_user_id"`
	EstimatedPoints              pgtype.Int4        `json:"estimated_points"`
	TaskCount                    int64              `json:"task_count"`
	ClosedTaskCount              int64              `json:"closed_task_count"`
}

// ListEpicsByProject follows ListBacklogsByProject exactly — the same
// "empty/false disables it" filter convention, the same priority/progress
// sort ranks, and the same LEFT JOIN task counts so the Epic collection
// screen's List row count, Board card ratio and Timeline bar fill come from
// one query. backlog_id is the extra filter: sqlc.narg(backlog_id) narrows to
// one backlog's epics, and backlog_unfiled to the epics in no backlog at all.
func (q *Queries) ListEpicsByProject(ctx context.Context, arg ListEpicsByProjectParams) ([]ListEpicsByProjectRow, error) {
	rows, err := q.db.Query(ctx, listEpicsByProject,
		arg.ProjectID,
		arg.BacklogID,
		arg.BacklogUnfiled,
		arg.Priority,
		arg.Progress,
		arg.AssigneeUserID,
		arg.AssigneeUnassigned,
		arg.SortByPriority,
		arg.SortByProgress,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEpicsByProjectRow{}
	for rows.Next() {
		var i ListEpicsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.BacklogID,
			&i.Name,
			&i.Description,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartDate,
			&i.DueOn,
			&i.Priority,
			&i.Progress,
			&i.DefaultLinkedGitlabProjectID,
			&i.BaseBranch,
			&i.AllowedScope,
			&i.ForbiddenScope,
			&i.AssigneeUserID,
			&i.EstimatedPoints,
			&i.TaskCount,
			&i.ClosedTaskCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveEpicTasksToBacklog = `-- name: MoveEpicTasksToBacklog :exec
UPDATE tasks
SET backlog_id = $1, updated_at = now()
WHERE epic_id = $2
  AND backlog_id IS DISTINCT FROM $1
`

type MoveEpicTasksToBacklogParams struct {
	BacklogID pgtype.UUID `json:"backlog_id"`
	EpicID    pgtype.UUID `json:"epic_id"`
}

// MoveEpicTasksToBacklog keeps a task's backlog_id in step with its epic's
// when the epic itself moves between backlogs (internal/epic.Service.Update
// runs it in the same transaction as UpdateEpicForOwner). Without it a task
// would report a backlog its own epic no longer belongs to.
func (q *Queries) MoveEpicTasksToBacklog(ctx context.Context, arg MoveEpicTasksToBacklogParams) error {
	_, err := q.db.Exec(ctx, moveEpicTasksToBacklog, arg.BacklogID, arg.EpicID)
	return err
}

const reorderEpics = `-- name: ReorderEpics :exec
WITH ordered AS (
    SELECT id, (ord - 1)::int AS position
    FROM unnest($2::uuid[]) WITH ORDINALITY AS t(id, ord)
)
UPDATE epics
SET position = ordered.position, updated_at = now()
FROM ordered
WHERE epics.id = ordered.id
  AND epics.project_id = $1
`

type ReorderEpicsParams struct {
	ProjectID uuid.UUID   `json:"project_id"`
	EpicIds   []uuid.UUID `json:"epic_ids"`
}

// ReorderEpics resequences a project's epics to epic_ids' given order
// (position 0 for the first id, 1 for the second, ...) in a single
// statement, the same all-or-nothing shape as ReorderBacklogs.
// internal/epic.Service.Reorder checks epic_ids is exactly the project's
// current epic set before calling this.
func (q *Queries) ReorderEpics(ctx context.Context, arg ReorderEpicsParams) error {
	_, err := q.db.Exec(ctx, reorderEpics, arg.ProjectID, arg.EpicIds)
	return err
}

const updateEpicForOwner = `-- name: UpdateEpicForOwner :one
UPDATE epics e
SET backlog_id = $2, name = $3, description = $4, position = $5, start_date = $6, due_on = $7, priority = $8, progress = $9, default_linked_gitlab_project_id = $10, base_branch = $11, allowed_scope = $12, forbidden_scope = $13,
    assignee_user_id = $14, estimated_points = $15, updated_at = now()
WHERE e.id = $1
  AND EXISTS (
    SELECT 1 FROM project_members pm
    WHERE pm.project_id = e.project_id AND pm.user_id = $16 AND pm.role IN ('member', 'owner')
  )
RETURNING e.id, e.project_id, e.backlog_id, e.name, e.description, e.position, e.start_date, e.due_on, e.priority, e.progress, e.assignee_user_id, e.base_branch, e.allowed_scope, e.forbidden_scope, e.default_linked_gitlab_project_id, e.created_at, e.updated_at, e.estimated_points
`

type UpdateEpicForOwnerParams struct {
	ID                           uuid.UUID   `json:"id"`
	BacklogID                    pgtype.UUID `json:"backlog_id"`
	Name                         string      `json:"name"`
	Description                  string      `json:"description"`
	Position                     int32       `json:"position"`
	StartDate                    pgtype.Date `json:"start_date"`
	DueOn                        pgtype.Date `json:"due_on"`
	Priority                     string      `json:"priority"`
	Progress                     string      `json:"progress"`
	DefaultLinkedGitlabProjectID pgtype.UUID `json:"default_linked_gitlab_project_id"`
	BaseBranch                   string      `json:"base_branch"`
	AllowedScope                 string      `json:"allowed_scope"`
	ForbiddenScope               string      `json:"forbidden_scope"`
	AssigneeUserID               pgtype.UUID `json:"assignee_user_id"`
	EstimatedPoints              pgtype.Int4 `json:"estimated_points"`
	OwnerUserID                  uuid.UUID   `json:"owner_user_id"`
}

// UpdateEpicForOwner overwrites every editable column, so the optional ones
// must arrive already resolved: epic.Service reads the current row first and
// fills in whatever the PATCH body left out (see its Update).
func (q *Queries) UpdateEpicForOwner(ctx context.Context, arg UpdateEpicForOwnerParams) (Epic, error) {
	row := q.db.QueryRow(ctx, updateEpicForOwner,
		arg.ID,
		arg.BacklogID,
		arg.Name,
		arg.Description,
		arg.Position,
		arg.StartDate,
		arg.DueOn,
		arg.Priority,
		arg.Progress,
		arg.DefaultLinkedGitlabProjectID,
		arg.BaseBranch,
		arg.AllowedScope,
		arg.ForbiddenScope,
		arg.AssigneeUserID,
		arg.EstimatedPoints,
		arg.OwnerUserID,
	)
	var i Epic
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BacklogID,
		&i.Name,
		&i.Description,
		&i.Position,
		&i.StartDate,
		&i.DueOn,
		&i.Priority,
		&i.Progress,
		&i.AssigneeUserID,
		&i.BaseBranch,
		&i.AllowedScope,
		&i.ForbiddenScope,
		&i.DefaultLinkedGitlabProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EstimatedPoints,
	)
	return i, err
}
