// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: flow_metrics.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listBacklogProgressEventsForFlowMetrics = `-- name: ListBacklogProgressEventsForFlowMetrics :many
SELECT e.backlog_id, e.from_progress, e.to_progress, e.occurred_at
FROM backlog_progress_events e
JOIN backlogs b ON b.id = e.backlog_id
WHERE b.project_id = $1
  AND EXISTS (
    SELECT 1 FROM project_members pm
    WHERE pm.project_id = b.project_id AND pm.user_id = $2
  )
  AND ($3::timestamptz IS NULL OR b.created_at >= $3)
  AND ($4::timestamptz IS NULL OR b.created_at <= $4)
ORDER BY e.backlog_id, e.occurred_at ASC
`

type ListBacklogProgressEventsForFlowMetricsParams struct {
	ProjectID   uuid.UUID          `json:"project_id"`
	OwnerUserID uuid.UUID          `json:"owner_user_id"`
	Since       pgtype.Timestamptz `json:"since"`
	Until       pgtype.Timestamptz `json:"until"`
}

type ListBacklogProgressEventsForFlowMetricsRow struct {
	BacklogID    uuid.UUID          `json:"backlog_id"`
	FromProgress string             `json:"from_progress"`
	ToProgress   string             `json:"to_progress"`
	OccurredAt   pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) ListBacklogProgressEventsForFlowMetrics(ctx context.Context, arg ListBacklogProgressEventsForFlowMetricsParams) ([]ListBacklogProgressEventsForFlowMetricsRow, error) {
	rows, err := q.db.Query(ctx, listBacklogProgressEventsForFlowMetrics,
		arg.ProjectID,
		arg.OwnerUserID,
		arg.Since,
		arg.Until,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBacklogProgressEventsForFlowMetricsRow{}
	for rows.Next() {
		var i ListBacklogProgressEventsForFlowMetricsRow
		if err := rows.Scan(
			&i.BacklogID,
			&i.FromProgress,
			&i.ToProgress,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBacklogTaskCreatedAtForFlowMetrics = `-- name: ListBacklogTaskCreatedAtForFlowMetrics :many

SELECT t.backlog_id, t.created_at
FROM tasks t
JOIN backlogs b ON b.id = t.backlog_id
WHERE b.project_id = $1
  AND EXISTS (
    SELECT 1 FROM project_members pm
    WHERE pm.project_id = b.project_id AND pm.user_id = $2
  )
  AND ($3::timestamptz IS NULL OR b.created_at >= $3)
  AND ($4::timestamptz IS NULL OR b.created_at <= $4)
ORDER BY t.backlog_id, t.created_at ASC
`

type ListBacklogTaskCreatedAtForFlowMetricsParams struct {
	ProjectID   uuid.UUID          `json:"project_id"`
	OwnerUserID uuid.UUID          `json:"owner_user_id"`
	Since       pgtype.Timestamptz `json:"since"`
	Until       pgtype.Timestamptz `json:"until"`
}

type ListBacklogTaskCreatedAtForFlowMetricsRow struct {
	BacklogID pgtype.UUID        `json:"backlog_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// ListBacklogTaskCreatedAtForFlowMetrics returns every (backlog_id,
// task.created_at) pair for tasks filed under an in-range backlog,
// unfiltered by the task's own created_at — internal/flowmetrics needs a
// backlog's *whole* task history to tell "tasks created after this backlog
// went in_progress" apart from "this backlog already had tasks before it
// went in_progress" (the exclusion issue #173 asks for), which a
// task-created_at bound would silently break.
func (q *Queries) ListBacklogTaskCreatedAtForFlowMetrics(ctx context.Context, arg ListBacklogTaskCreatedAtForFlowMetricsParams) ([]ListBacklogTaskCreatedAtForFlowMetricsRow, error) {
	rows, err := q.db.Query(ctx, listBacklogTaskCreatedAtForFlowMetrics,
		arg.ProjectID,
		arg.OwnerUserID,
		arg.Since,
		arg.Until,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBacklogTaskCreatedAtForFlowMetricsRow{}
	for rows.Next() {
		var i ListBacklogTaskCreatedAtForFlowMetricsRow
		if err := rows.Scan(&i.BacklogID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBacklogsForFlowMetrics = `-- name: ListBacklogsForFlowMetrics :many

SELECT b.id, b.created_at
FROM backlogs b
WHERE b.project_id = $1
  AND EXISTS (
    SELECT 1 FROM project_members pm
    WHERE pm.project_id = b.project_id AND pm.user_id = $2
  )
  AND ($3::timestamptz IS NULL OR b.created_at >= $3)
  AND ($4::timestamptz IS NULL OR b.created_at <= $4)
`

type ListBacklogsForFlowMetricsParams struct {
	ProjectID   uuid.UUID          `json:"project_id"`
	OwnerUserID uuid.UUID          `json:"owner_user_id"`
	Since       pgtype.Timestamptz `json:"since"`
	Until       pgtype.Timestamptz `json:"until"`
}

type ListBacklogsForFlowMetricsRow struct {
	ID        uuid.UUID          `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Backlog-level flow metrics (issue #173): one level up from the
// task-level queries above, sourced from backlog_progress_events (issue
// #173) plus each backlog's own tasks. since/until bound backlogs.created_at
// here, not tasks.created_at — a backlog and its eventual tasks can span
// very different windows, and it's the backlog's own creation that starts
// the "waiting to start" clock this query feeds.
func (q *Queries) ListBacklogsForFlowMetrics(ctx context.Context, arg ListBacklogsForFlowMetricsParams) ([]ListBacklogsForFlowMetricsRow, error) {
	rows, err := q.db.Query(ctx, listBacklogsForFlowMetrics,
		arg.ProjectID,
		arg.OwnerUserID,
		arg.Since,
		arg.Until,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBacklogsForFlowMetricsRow{}
	for rows.Next() {
		var i ListBacklogsForFlowMetricsRow
		if err := rows.Scan(&i.ID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskProgressEventsForFlowMetrics = `-- name: ListTaskProgressEventsForFlowMetrics :many

SELECT e.task_id, e.from_progress, e.to_progress, e.occurred_at
FROM task_progress_events e
JOIN tasks t ON t.id = e.task_id
WHERE t.project_id = $1
  AND EXISTS (
    SELECT 1 FROM project_members pm
    WHERE pm.project_id = t.project_id AND pm.user_id = $2
  )
  AND ($3::timestamptz IS NULL OR t.created_at >= $3)
  AND ($4::timestamptz IS NULL OR t.created_at <= $4)
ORDER BY e.task_id, e.occurred_at ASC
`

type ListTaskProgressEventsForFlowMetricsParams struct {
	ProjectID   uuid.UUID          `json:"project_id"`
	OwnerUserID uuid.UUID          `json:"owner_user_id"`
	Since       pgtype.Timestamptz `json:"since"`
	Until       pgtype.Timestamptz `json:"until"`
}

type ListTaskProgressEventsForFlowMetricsRow struct {
	TaskID       uuid.UUID          `json:"task_id"`
	FromProgress string             `json:"from_progress"`
	ToProgress   string             `json:"to_progress"`
	OccurredAt   pgtype.Timestamptz `json:"occurred_at"`
}

// ListTaskProgressEventsForFlowMetrics returns every task_progress_events
// row for tasks in the same project/date range ListTasksForFlowMetrics
// selects, so internal/flowmetrics can replay each task's progress
// timeline (first in_progress, first done, on_hold intervals) without an
// N+1 query per task. Ordered by task then occurred_at so the caller can
// walk each task's timeline in order without re-sorting.
func (q *Queries) ListTaskProgressEventsForFlowMetrics(ctx context.Context, arg ListTaskProgressEventsForFlowMetricsParams) ([]ListTaskProgressEventsForFlowMetricsRow, error) {
	rows, err := q.db.Query(ctx, listTaskProgressEventsForFlowMetrics,
		arg.ProjectID,
		arg.OwnerUserID,
		arg.Since,
		arg.Until,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskProgressEventsForFlowMetricsRow{}
	for rows.Next() {
		var i ListTaskProgressEventsForFlowMetricsRow
		if err := rows.Scan(
			&i.TaskID,
			&i.FromProgress,
			&i.ToProgress,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksForFlowMetrics = `-- name: ListTasksForFlowMetrics :many


SELECT t.id, t.created_at, mr.gitlab_created_at AS mr_gitlab_created_at, mr.merged_at AS mr_merged_at
FROM tasks t
LEFT JOIN LATERAL (
    SELECT m.gitlab_created_at, m.merged_at
    FROM merge_requests m
    WHERE m.task_id = t.id
    ORDER BY m.gitlab_created_at ASC NULLS LAST, m.created_at ASC
    LIMIT 1
) mr ON true
WHERE t.project_id = $1
  AND EXISTS (
    SELECT 1 FROM project_members pm
    WHERE pm.project_id = t.project_id AND pm.user_id = $2
  )
  AND ($3::timestamptz IS NULL OR t.created_at >= $3)
  AND ($4::timestamptz IS NULL OR t.created_at <= $4)
`

type ListTasksForFlowMetricsParams struct {
	ProjectID   uuid.UUID          `json:"project_id"`
	OwnerUserID uuid.UUID          `json:"owner_user_id"`
	Since       pgtype.Timestamptz `json:"since"`
	Until       pgtype.Timestamptz `json:"until"`
}

type ListTasksForFlowMetricsRow struct {
	ID                uuid.UUID          `json:"id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	MrGitlabCreatedAt pgtype.Timestamptz `json:"mr_gitlab_created_at"`
	MrMergedAt        pgtype.Timestamptz `json:"mr_merged_at"`
}

// Flow-metrics aggregation (issue #171): per-task stage lead times, sourced
// from task_progress_events (issue #169) plus each task's earliest linked
// merge request (merge_requests.task_id, set by internal/mrsync, issue
// #111). Unlike deliverymetrics, which aggregates merge_requests alone,
// this walks the whole progress pipeline a task moves through — see
// internal/flowmetrics for how the two queries below are combined.
// ListTasksForFlowMetrics returns each in-range task alongside its earliest
// linked merge request's gitlab_created_at/merged_at (NULL when the task
// has no linked merge request, or none yet has a GitLab-side created_at). A
// merge request has at most one task (migration 000019's comment), but a
// task can have more than one merge request; the earliest by
// gitlab_created_at is the one flow-metrics' implementation/review stages
// measure against, since it's the one that closes the "in_progress" wait.
func (q *Queries) ListTasksForFlowMetrics(ctx context.Context, arg ListTasksForFlowMetricsParams) ([]ListTasksForFlowMetricsRow, error) {
	rows, err := q.db.Query(ctx, listTasksForFlowMetrics,
		arg.ProjectID,
		arg.OwnerUserID,
		arg.Since,
		arg.Until,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTasksForFlowMetricsRow{}
	for rows.Next() {
		var i ListTasksForFlowMetricsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.MrGitlabCreatedAt,
			&i.MrMergedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
