// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gitlab_sync_runs.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const completeGitlabSyncRun = `-- name: CompleteGitlabSyncRun :one
UPDATE gitlab_sync_runs
SET status = 'succeeded',
    issues_seen = $2,
    issues_created = $3,
    issues_updated = $4,
    completed_at = now()
WHERE id = $1
RETURNING id, linked_gitlab_project_id, kind, status, issues_seen, issues_created, issues_updated, started_at, completed_at, error_message, created_at
`

type CompleteGitlabSyncRunParams struct {
	ID            uuid.UUID `json:"id"`
	IssuesSeen    int32     `json:"issues_seen"`
	IssuesCreated int32     `json:"issues_created"`
	IssuesUpdated int32     `json:"issues_updated"`
}

func (q *Queries) CompleteGitlabSyncRun(ctx context.Context, arg CompleteGitlabSyncRunParams) (GitlabSyncRun, error) {
	row := q.db.QueryRow(ctx, completeGitlabSyncRun,
		arg.ID,
		arg.IssuesSeen,
		arg.IssuesCreated,
		arg.IssuesUpdated,
	)
	var i GitlabSyncRun
	err := row.Scan(
		&i.ID,
		&i.LinkedGitlabProjectID,
		&i.Kind,
		&i.Status,
		&i.IssuesSeen,
		&i.IssuesCreated,
		&i.IssuesUpdated,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const createGitlabSyncRun = `-- name: CreateGitlabSyncRun :one

INSERT INTO gitlab_sync_runs (linked_gitlab_project_id, kind, status, started_at)
VALUES ($1, $2, 'running', now())
RETURNING id, linked_gitlab_project_id, kind, status, issues_seen, issues_created, issues_updated, started_at, completed_at, error_message, created_at
`

type CreateGitlabSyncRunParams struct {
	LinkedGitlabProjectID uuid.UUID `json:"linked_gitlab_project_id"`
	Kind                  string    `json:"kind"`
}

// gitlab_sync_runs records one project.import / project.resync execution
// against a linked GitLab project (docs/plans/issue-sync.md's SyncRun
// object, issue #25). Concurrency is enforced at the database level, not by
// a check-then-insert race in Go: a partial UNIQUE index on
// (linked_gitlab_project_id) WHERE completed_at IS NULL (migration 000006)
// means CreateGitlabSyncRun itself fails with a unique-constraint violation
// when a run is already in progress for the same link, which
// internal/projectsync maps to ErrRunInProgress (HTTP 409).
func (q *Queries) CreateGitlabSyncRun(ctx context.Context, arg CreateGitlabSyncRunParams) (GitlabSyncRun, error) {
	row := q.db.QueryRow(ctx, createGitlabSyncRun, arg.LinkedGitlabProjectID, arg.Kind)
	var i GitlabSyncRun
	err := row.Scan(
		&i.ID,
		&i.LinkedGitlabProjectID,
		&i.Kind,
		&i.Status,
		&i.IssuesSeen,
		&i.IssuesCreated,
		&i.IssuesUpdated,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const failGitlabSyncRun = `-- name: FailGitlabSyncRun :one
UPDATE gitlab_sync_runs
SET status = 'failed',
    issues_seen = $2,
    issues_created = $3,
    issues_updated = $4,
    error_message = $5,
    completed_at = now()
WHERE id = $1
RETURNING id, linked_gitlab_project_id, kind, status, issues_seen, issues_created, issues_updated, started_at, completed_at, error_message, created_at
`

type FailGitlabSyncRunParams struct {
	ID            uuid.UUID `json:"id"`
	IssuesSeen    int32     `json:"issues_seen"`
	IssuesCreated int32     `json:"issues_created"`
	IssuesUpdated int32     `json:"issues_updated"`
	ErrorMessage  string    `json:"error_message"`
}

func (q *Queries) FailGitlabSyncRun(ctx context.Context, arg FailGitlabSyncRunParams) (GitlabSyncRun, error) {
	row := q.db.QueryRow(ctx, failGitlabSyncRun,
		arg.ID,
		arg.IssuesSeen,
		arg.IssuesCreated,
		arg.IssuesUpdated,
		arg.ErrorMessage,
	)
	var i GitlabSyncRun
	err := row.Scan(
		&i.ID,
		&i.LinkedGitlabProjectID,
		&i.Kind,
		&i.Status,
		&i.IssuesSeen,
		&i.IssuesCreated,
		&i.IssuesUpdated,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const getGitlabSyncRunByID = `-- name: GetGitlabSyncRunByID :one

SELECT id, linked_gitlab_project_id, kind, status, issues_seen, issues_created, issues_updated, started_at, completed_at, error_message, created_at FROM gitlab_sync_runs WHERE id = $1
`

// Unscoped, like GetLinkedGitlabProjectByID: the background worker
// (internal/projectsync) reads this with no acting user of its own — the
// job row that names this run's ID was already authorized when it was
// created (either automatically at link creation, or by an owner-scoped
// HTTP request).
func (q *Queries) GetGitlabSyncRunByID(ctx context.Context, id uuid.UUID) (GitlabSyncRun, error) {
	row := q.db.QueryRow(ctx, getGitlabSyncRunByID, id)
	var i GitlabSyncRun
	err := row.Scan(
		&i.ID,
		&i.LinkedGitlabProjectID,
		&i.Kind,
		&i.Status,
		&i.IssuesSeen,
		&i.IssuesCreated,
		&i.IssuesUpdated,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const listGitlabSyncRunsByLinkedGitlabProjectID = `-- name: ListGitlabSyncRunsByLinkedGitlabProjectID :many

SELECT id, linked_gitlab_project_id, kind, status, issues_seen, issues_created, issues_updated, started_at, completed_at, error_message, created_at FROM gitlab_sync_runs
WHERE linked_gitlab_project_id = $1
ORDER BY created_at DESC
`

// Ownership of linkID must already be verified by the caller via
// GetLinkedGitlabProjectForOwner before this runs.
func (q *Queries) ListGitlabSyncRunsByLinkedGitlabProjectID(ctx context.Context, linkedGitlabProjectID uuid.UUID) ([]GitlabSyncRun, error) {
	rows, err := q.db.Query(ctx, listGitlabSyncRunsByLinkedGitlabProjectID, linkedGitlabProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GitlabSyncRun{}
	for rows.Next() {
		var i GitlabSyncRun
		if err := rows.Scan(
			&i.ID,
			&i.LinkedGitlabProjectID,
			&i.Kind,
			&i.Status,
			&i.IssuesSeen,
			&i.IssuesCreated,
			&i.IssuesUpdated,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
