// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gitlabidentity.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const listUserGitlabIdentitiesByUser = `-- name: ListUserGitlabIdentitiesByUser :many
SELECT id, user_id, gitlab_base_url, gitlab_user_id, gitlab_username, created_at, updated_at
FROM user_gitlab_identities
WHERE user_id = $1
ORDER BY gitlab_base_url ASC
`

func (q *Queries) ListUserGitlabIdentitiesByUser(ctx context.Context, userID uuid.UUID) ([]UserGitlabIdentity, error) {
	rows, err := q.db.Query(ctx, listUserGitlabIdentitiesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserGitlabIdentity{}
	for rows.Next() {
		var i UserGitlabIdentity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GitlabBaseUrl,
			&i.GitlabUserID,
			&i.GitlabUsername,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserGitlabIdentity = `-- name: UpsertUserGitlabIdentity :one

INSERT INTO user_gitlab_identities (user_id, gitlab_base_url, gitlab_user_id, gitlab_username)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, gitlab_base_url) DO UPDATE
SET gitlab_user_id = EXCLUDED.gitlab_user_id,
    gitlab_username = EXCLUDED.gitlab_username,
    updated_at = now()
RETURNING id, user_id, gitlab_base_url, gitlab_user_id, gitlab_username, created_at, updated_at
`

type UpsertUserGitlabIdentityParams struct {
	UserID         uuid.UUID `json:"user_id"`
	GitlabBaseUrl  string    `json:"gitlab_base_url"`
	GitlabUserID   int64     `json:"gitlab_user_id"`
	GitlabUsername string    `json:"gitlab_username"`
}

// user_gitlab_identities maps a FlowLens user to their GitLab user ID/username
// on one GitLab CE instance (gitlab_base_url), so ?assignee=me on the task
// collections (internal/task) can match against tasks.assignee_gitlab_user_id.
// UpsertUserGitlabIdentity is the only write: a user re-registering the same
// base_url replaces the previous mapping rather than erroring.
func (q *Queries) UpsertUserGitlabIdentity(ctx context.Context, arg UpsertUserGitlabIdentityParams) (UserGitlabIdentity, error) {
	row := q.db.QueryRow(ctx, upsertUserGitlabIdentity,
		arg.UserID,
		arg.GitlabBaseUrl,
		arg.GitlabUserID,
		arg.GitlabUsername,
	)
	var i UserGitlabIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GitlabBaseUrl,
		&i.GitlabUserID,
		&i.GitlabUsername,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
