// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: linked_gitlab_projects.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearDefaultLinkedGitlabProjectsForOwner = `-- name: ClearDefaultLinkedGitlabProjectsForOwner :exec
UPDATE linked_gitlab_projects lgp
SET is_default = false,
    updated_at = now()
FROM gitlab_connections gc
WHERE lgp.gitlab_connection_id = gc.id
    AND EXISTS (
      SELECT 1 FROM project_members pm
      WHERE pm.project_id = gc.project_id AND pm.user_id = $2 AND pm.role IN ('member', 'owner')
    )
    AND lgp.gitlab_connection_id = (
        SELECT orig.gitlab_connection_id FROM linked_gitlab_projects orig WHERE orig.id = $1
    )
    AND lgp.id != $1
`

type ClearDefaultLinkedGitlabProjectsForOwnerParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

// Unsets is_default on every other link in the same connection as linkID,
// so SetDefaultLinkedGitlabProjectForOwner can set exactly one.
func (q *Queries) ClearDefaultLinkedGitlabProjectsForOwner(ctx context.Context, arg ClearDefaultLinkedGitlabProjectsForOwnerParams) error {
	_, err := q.db.Exec(ctx, clearDefaultLinkedGitlabProjectsForOwner, arg.ID, arg.OwnerUserID)
	return err
}

const createLinkedGitlabProject = `-- name: CreateLinkedGitlabProject :one

INSERT INTO linked_gitlab_projects (
    gitlab_connection_id, gitlab_project_id, path_with_namespace, name, web_url,
    sync_scope, sync_labels, is_default
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    NOT EXISTS (SELECT 1 FROM linked_gitlab_projects WHERE gitlab_connection_id = $1)
)
RETURNING id, gitlab_connection_id, gitlab_project_id, path_with_namespace, name, web_url, sync_scope, sync_labels, webhook_id, encrypted_webhook_secret, webhook_registered_at, initial_import_status, last_synced_at, created_at, updated_at, is_default, webhook_registration_error
`

type CreateLinkedGitlabProjectParams struct {
	GitlabConnectionID uuid.UUID `json:"gitlab_connection_id"`
	GitlabProjectID    int64     `json:"gitlab_project_id"`
	PathWithNamespace  string    `json:"path_with_namespace"`
	Name               string    `json:"name"`
	WebUrl             string    `json:"web_url"`
	SyncScope          string    `json:"sync_scope"`
	SyncLabels         []string  `json:"sync_labels"`
}

// linked_gitlab_projects has no owner column of its own; ownership is always
// checked by joining through gitlab_connections to projects, the same way
// gitlab_connections is checked through projects. A link belonging to
// another user's project is indistinguishable from a missing one.
// is_default is computed here, not by the caller: the first project linked
// to a connection becomes its default, later ones do not.
func (q *Queries) CreateLinkedGitlabProject(ctx context.Context, arg CreateLinkedGitlabProjectParams) (LinkedGitlabProject, error) {
	row := q.db.QueryRow(ctx, createLinkedGitlabProject,
		arg.GitlabConnectionID,
		arg.GitlabProjectID,
		arg.PathWithNamespace,
		arg.Name,
		arg.WebUrl,
		arg.SyncScope,
		arg.SyncLabels,
	)
	var i LinkedGitlabProject
	err := row.Scan(
		&i.ID,
		&i.GitlabConnectionID,
		&i.GitlabProjectID,
		&i.PathWithNamespace,
		&i.Name,
		&i.WebUrl,
		&i.SyncScope,
		&i.SyncLabels,
		&i.WebhookID,
		&i.EncryptedWebhookSecret,
		&i.WebhookRegisteredAt,
		&i.InitialImportStatus,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
		&i.WebhookRegistrationError,
	)
	return i, err
}

const deleteLinkedGitlabProjectForOwner = `-- name: DeleteLinkedGitlabProjectForOwner :one
DELETE FROM linked_gitlab_projects lgp
USING gitlab_connections gc
WHERE lgp.id = $1 AND lgp.gitlab_connection_id = gc.id
    AND EXISTS (
      SELECT 1 FROM project_members pm
      WHERE pm.project_id = gc.project_id AND pm.user_id = $2 AND pm.role IN ('member', 'owner')
    )
RETURNING lgp.id, lgp.gitlab_connection_id, lgp.gitlab_project_id, lgp.path_with_namespace, lgp.name, lgp.web_url, lgp.sync_scope, lgp.sync_labels, lgp.webhook_id, lgp.encrypted_webhook_secret, lgp.webhook_registered_at, lgp.initial_import_status, lgp.last_synced_at, lgp.created_at, lgp.updated_at, lgp.is_default, lgp.webhook_registration_error
`

type DeleteLinkedGitlabProjectForOwnerParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

// Returns the deleted row (rather than an affected-row count) so the
// service can tell whether it removed the default link and needs to
// promote another one.
func (q *Queries) DeleteLinkedGitlabProjectForOwner(ctx context.Context, arg DeleteLinkedGitlabProjectForOwnerParams) (LinkedGitlabProject, error) {
	row := q.db.QueryRow(ctx, deleteLinkedGitlabProjectForOwner, arg.ID, arg.OwnerUserID)
	var i LinkedGitlabProject
	err := row.Scan(
		&i.ID,
		&i.GitlabConnectionID,
		&i.GitlabProjectID,
		&i.PathWithNamespace,
		&i.Name,
		&i.WebUrl,
		&i.SyncScope,
		&i.SyncLabels,
		&i.WebhookID,
		&i.EncryptedWebhookSecret,
		&i.WebhookRegisteredAt,
		&i.InitialImportStatus,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
		&i.WebhookRegistrationError,
	)
	return i, err
}

const getDefaultLinkedGitlabProjectForOwner = `-- name: GetDefaultLinkedGitlabProjectForOwner :one
SELECT lgp.id, lgp.gitlab_connection_id, lgp.gitlab_project_id, lgp.path_with_namespace, lgp.name, lgp.web_url, lgp.sync_scope, lgp.sync_labels, lgp.webhook_id, lgp.encrypted_webhook_secret, lgp.webhook_registered_at, lgp.initial_import_status, lgp.last_synced_at, lgp.created_at, lgp.updated_at, lgp.is_default, lgp.webhook_registration_error
FROM linked_gitlab_projects lgp
JOIN gitlab_connections gc ON gc.id = lgp.gitlab_connection_id
WHERE gc.project_id = $1
  AND EXISTS (
    SELECT 1 FROM project_members pm
    WHERE pm.project_id = gc.project_id AND pm.user_id = $2
  )
  AND lgp.is_default = true
`

type GetDefaultLinkedGitlabProjectForOwnerParams struct {
	ProjectID   uuid.UUID `json:"project_id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

// internal/task uses this at task-create time to decide whether the
// project has anywhere to push a new issue, and if so, where
// (docs/plans/issue-sync.md, "Outbound").
func (q *Queries) GetDefaultLinkedGitlabProjectForOwner(ctx context.Context, arg GetDefaultLinkedGitlabProjectForOwnerParams) (LinkedGitlabProject, error) {
	row := q.db.QueryRow(ctx, getDefaultLinkedGitlabProjectForOwner, arg.ProjectID, arg.OwnerUserID)
	var i LinkedGitlabProject
	err := row.Scan(
		&i.ID,
		&i.GitlabConnectionID,
		&i.GitlabProjectID,
		&i.PathWithNamespace,
		&i.Name,
		&i.WebUrl,
		&i.SyncScope,
		&i.SyncLabels,
		&i.WebhookID,
		&i.EncryptedWebhookSecret,
		&i.WebhookRegisteredAt,
		&i.InitialImportStatus,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
		&i.WebhookRegistrationError,
	)
	return i, err
}

const getLinkedGitlabProjectByID = `-- name: GetLinkedGitlabProjectByID :one
SELECT id, gitlab_connection_id, gitlab_project_id, path_with_namespace, name, web_url, sync_scope, sync_labels, webhook_id, encrypted_webhook_secret, webhook_registered_at, initial_import_status, last_synced_at, created_at, updated_at, is_default, webhook_registration_error FROM linked_gitlab_projects WHERE id = $1
`

// Unscoped: the outbox worker (internal/issuesync) has no acting user. The
// sync_jobs row that names this linked project's ID was already authorized
// when internal/task enqueued it, so the job's execution needs no further
// ownership check.
func (q *Queries) GetLinkedGitlabProjectByID(ctx context.Context, id uuid.UUID) (LinkedGitlabProject, error) {
	row := q.db.QueryRow(ctx, getLinkedGitlabProjectByID, id)
	var i LinkedGitlabProject
	err := row.Scan(
		&i.ID,
		&i.GitlabConnectionID,
		&i.GitlabProjectID,
		&i.PathWithNamespace,
		&i.Name,
		&i.WebUrl,
		&i.SyncScope,
		&i.SyncLabels,
		&i.WebhookID,
		&i.EncryptedWebhookSecret,
		&i.WebhookRegisteredAt,
		&i.InitialImportStatus,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
		&i.WebhookRegistrationError,
	)
	return i, err
}

const getLinkedGitlabProjectForOwner = `-- name: GetLinkedGitlabProjectForOwner :one
SELECT lgp.id, lgp.gitlab_connection_id, lgp.gitlab_project_id, lgp.path_with_namespace, lgp.name, lgp.web_url, lgp.sync_scope, lgp.sync_labels, lgp.webhook_id, lgp.encrypted_webhook_secret, lgp.webhook_registered_at, lgp.initial_import_status, lgp.last_synced_at, lgp.created_at, lgp.updated_at, lgp.is_default, lgp.webhook_registration_error
FROM linked_gitlab_projects lgp
JOIN gitlab_connections gc ON gc.id = lgp.gitlab_connection_id
WHERE lgp.id = $1
  AND EXISTS (
    SELECT 1 FROM project_members pm
    WHERE pm.project_id = gc.project_id AND pm.user_id = $2
  )
`

type GetLinkedGitlabProjectForOwnerParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) GetLinkedGitlabProjectForOwner(ctx context.Context, arg GetLinkedGitlabProjectForOwnerParams) (LinkedGitlabProject, error) {
	row := q.db.QueryRow(ctx, getLinkedGitlabProjectForOwner, arg.ID, arg.OwnerUserID)
	var i LinkedGitlabProject
	err := row.Scan(
		&i.ID,
		&i.GitlabConnectionID,
		&i.GitlabProjectID,
		&i.PathWithNamespace,
		&i.Name,
		&i.WebUrl,
		&i.SyncScope,
		&i.SyncLabels,
		&i.WebhookID,
		&i.EncryptedWebhookSecret,
		&i.WebhookRegisteredAt,
		&i.InitialImportStatus,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
		&i.WebhookRegistrationError,
	)
	return i, err
}

const getLinkedGitlabProjectProjectID = `-- name: GetLinkedGitlabProjectProjectID :one
SELECT gc.project_id
FROM linked_gitlab_projects lgp
JOIN gitlab_connections gc ON gc.id = lgp.gitlab_connection_id
WHERE lgp.id = $1
`

// The lightweight project lookup requireTokenResourceProject (internal/http,
// issue #66) uses to enforce a bearer token's project boundary on
// GET /linked-gitlab-projects/{linkID}/sync-runs, resolved through
// gitlab_connections the same way linkedProjectOwner (dbtest) does, since a
// linked project has no project_id column of its own.
func (q *Queries) GetLinkedGitlabProjectProjectID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getLinkedGitlabProjectProjectID, id)
	var project_id uuid.UUID
	err := row.Scan(&project_id)
	return project_id, err
}

const listLinkedGitlabProjectsForOwner = `-- name: ListLinkedGitlabProjectsForOwner :many
SELECT lgp.id, lgp.gitlab_connection_id, lgp.gitlab_project_id, lgp.path_with_namespace, lgp.name, lgp.web_url, lgp.sync_scope, lgp.sync_labels, lgp.webhook_id, lgp.encrypted_webhook_secret, lgp.webhook_registered_at, lgp.initial_import_status, lgp.last_synced_at, lgp.created_at, lgp.updated_at, lgp.is_default, lgp.webhook_registration_error
FROM linked_gitlab_projects lgp
JOIN gitlab_connections gc ON gc.id = lgp.gitlab_connection_id
WHERE gc.project_id = $1
  AND EXISTS (
    SELECT 1 FROM project_members pm
    WHERE pm.project_id = gc.project_id AND pm.user_id = $2
  )
ORDER BY lgp.created_at
`

type ListLinkedGitlabProjectsForOwnerParams struct {
	ProjectID   uuid.UUID `json:"project_id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) ListLinkedGitlabProjectsForOwner(ctx context.Context, arg ListLinkedGitlabProjectsForOwnerParams) ([]LinkedGitlabProject, error) {
	rows, err := q.db.Query(ctx, listLinkedGitlabProjectsForOwner, arg.ProjectID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LinkedGitlabProject{}
	for rows.Next() {
		var i LinkedGitlabProject
		if err := rows.Scan(
			&i.ID,
			&i.GitlabConnectionID,
			&i.GitlabProjectID,
			&i.PathWithNamespace,
			&i.Name,
			&i.WebUrl,
			&i.SyncScope,
			&i.SyncLabels,
			&i.WebhookID,
			&i.EncryptedWebhookSecret,
			&i.WebhookRegisteredAt,
			&i.InitialImportStatus,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDefault,
			&i.WebhookRegistrationError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteOldestLinkedGitlabProjectAsDefault = `-- name: PromoteOldestLinkedGitlabProjectAsDefault :exec
UPDATE linked_gitlab_projects
SET is_default = true, updated_at = now()
WHERE id = (
    SELECT candidate.id FROM linked_gitlab_projects candidate
    WHERE candidate.gitlab_connection_id = $1
    ORDER BY candidate.created_at
    LIMIT 1
)
`

// Used after deleting the default link: makes the oldest remaining link in
// the same connection the new default. A no-op if none remain.
func (q *Queries) PromoteOldestLinkedGitlabProjectAsDefault(ctx context.Context, gitlabConnectionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, promoteOldestLinkedGitlabProjectAsDefault, gitlabConnectionID)
	return err
}

const setDefaultLinkedGitlabProjectForOwner = `-- name: SetDefaultLinkedGitlabProjectForOwner :one
UPDATE linked_gitlab_projects lgp
SET is_default = true,
    updated_at = now()
FROM gitlab_connections gc
WHERE lgp.id = $1 AND lgp.gitlab_connection_id = gc.id
    AND EXISTS (
      SELECT 1 FROM project_members pm
      WHERE pm.project_id = gc.project_id AND pm.user_id = $2 AND pm.role IN ('member', 'owner')
    )
RETURNING lgp.id, lgp.gitlab_connection_id, lgp.gitlab_project_id, lgp.path_with_namespace, lgp.name, lgp.web_url, lgp.sync_scope, lgp.sync_labels, lgp.webhook_id, lgp.encrypted_webhook_secret, lgp.webhook_registered_at, lgp.initial_import_status, lgp.last_synced_at, lgp.created_at, lgp.updated_at, lgp.is_default, lgp.webhook_registration_error
`

type SetDefaultLinkedGitlabProjectForOwnerParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) SetDefaultLinkedGitlabProjectForOwner(ctx context.Context, arg SetDefaultLinkedGitlabProjectForOwnerParams) (LinkedGitlabProject, error) {
	row := q.db.QueryRow(ctx, setDefaultLinkedGitlabProjectForOwner, arg.ID, arg.OwnerUserID)
	var i LinkedGitlabProject
	err := row.Scan(
		&i.ID,
		&i.GitlabConnectionID,
		&i.GitlabProjectID,
		&i.PathWithNamespace,
		&i.Name,
		&i.WebUrl,
		&i.SyncScope,
		&i.SyncLabels,
		&i.WebhookID,
		&i.EncryptedWebhookSecret,
		&i.WebhookRegisteredAt,
		&i.InitialImportStatus,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
		&i.WebhookRegistrationError,
	)
	return i, err
}

const setLinkedGitlabProjectWebhookErrorForOwner = `-- name: SetLinkedGitlabProjectWebhookErrorForOwner :one
UPDATE linked_gitlab_projects lgp
SET webhook_registration_error = $2,
    updated_at = now()
FROM gitlab_connections gc
WHERE lgp.id = $1 AND lgp.gitlab_connection_id = gc.id
    AND EXISTS (
      SELECT 1 FROM project_members pm
      WHERE pm.project_id = gc.project_id AND pm.user_id = $3 AND pm.role IN ('member', 'owner')
    )
RETURNING lgp.id, lgp.gitlab_connection_id, lgp.gitlab_project_id, lgp.path_with_namespace, lgp.name, lgp.web_url, lgp.sync_scope, lgp.sync_labels, lgp.webhook_id, lgp.encrypted_webhook_secret, lgp.webhook_registered_at, lgp.initial_import_status, lgp.last_synced_at, lgp.created_at, lgp.updated_at, lgp.is_default, lgp.webhook_registration_error
`

type SetLinkedGitlabProjectWebhookErrorForOwnerParams struct {
	ID                       uuid.UUID `json:"id"`
	WebhookRegistrationError string    `json:"webhook_registration_error"`
	OwnerUserID              uuid.UUID `json:"owner_user_id"`
}

// Records why registering or repairing a webhook failed (most commonly
// insufficient GitLab permissions) without touching any existing
// webhook_id, so the link stays usable via manual sync.
func (q *Queries) SetLinkedGitlabProjectWebhookErrorForOwner(ctx context.Context, arg SetLinkedGitlabProjectWebhookErrorForOwnerParams) (LinkedGitlabProject, error) {
	row := q.db.QueryRow(ctx, setLinkedGitlabProjectWebhookErrorForOwner, arg.ID, arg.WebhookRegistrationError, arg.OwnerUserID)
	var i LinkedGitlabProject
	err := row.Scan(
		&i.ID,
		&i.GitlabConnectionID,
		&i.GitlabProjectID,
		&i.PathWithNamespace,
		&i.Name,
		&i.WebUrl,
		&i.SyncScope,
		&i.SyncLabels,
		&i.WebhookID,
		&i.EncryptedWebhookSecret,
		&i.WebhookRegisteredAt,
		&i.InitialImportStatus,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
		&i.WebhookRegistrationError,
	)
	return i, err
}

const setLinkedGitlabProjectWebhookForOwner = `-- name: SetLinkedGitlabProjectWebhookForOwner :one
UPDATE linked_gitlab_projects lgp
SET webhook_id = $2,
    encrypted_webhook_secret = $3,
    webhook_registered_at = now(),
    webhook_registration_error = '',
    updated_at = now()
FROM gitlab_connections gc
WHERE lgp.id = $1 AND lgp.gitlab_connection_id = gc.id
    AND EXISTS (
      SELECT 1 FROM project_members pm
      WHERE pm.project_id = gc.project_id AND pm.user_id = $4 AND pm.role IN ('member', 'owner')
    )
RETURNING lgp.id, lgp.gitlab_connection_id, lgp.gitlab_project_id, lgp.path_with_namespace, lgp.name, lgp.web_url, lgp.sync_scope, lgp.sync_labels, lgp.webhook_id, lgp.encrypted_webhook_secret, lgp.webhook_registered_at, lgp.initial_import_status, lgp.last_synced_at, lgp.created_at, lgp.updated_at, lgp.is_default, lgp.webhook_registration_error
`

type SetLinkedGitlabProjectWebhookForOwnerParams struct {
	ID                     uuid.UUID   `json:"id"`
	WebhookID              pgtype.Int8 `json:"webhook_id"`
	EncryptedWebhookSecret []byte      `json:"encrypted_webhook_secret"`
	OwnerUserID            uuid.UUID   `json:"owner_user_id"`
}

// Records a successful webhook registration or rotation (issue #18) and
// clears any earlier registration error.
func (q *Queries) SetLinkedGitlabProjectWebhookForOwner(ctx context.Context, arg SetLinkedGitlabProjectWebhookForOwnerParams) (LinkedGitlabProject, error) {
	row := q.db.QueryRow(ctx, setLinkedGitlabProjectWebhookForOwner,
		arg.ID,
		arg.WebhookID,
		arg.EncryptedWebhookSecret,
		arg.OwnerUserID,
	)
	var i LinkedGitlabProject
	err := row.Scan(
		&i.ID,
		&i.GitlabConnectionID,
		&i.GitlabProjectID,
		&i.PathWithNamespace,
		&i.Name,
		&i.WebUrl,
		&i.SyncScope,
		&i.SyncLabels,
		&i.WebhookID,
		&i.EncryptedWebhookSecret,
		&i.WebhookRegisteredAt,
		&i.InitialImportStatus,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
		&i.WebhookRegistrationError,
	)
	return i, err
}

const updateLinkedGitlabProjectInitialImportStatus = `-- name: UpdateLinkedGitlabProjectInitialImportStatus :one
UPDATE linked_gitlab_projects
SET initial_import_status = $2, updated_at = now()
WHERE id = $1
RETURNING id, gitlab_connection_id, gitlab_project_id, path_with_namespace, name, web_url, sync_scope, sync_labels, webhook_id, encrypted_webhook_secret, webhook_registered_at, initial_import_status, last_synced_at, created_at, updated_at, is_default, webhook_registration_error
`

type UpdateLinkedGitlabProjectInitialImportStatusParams struct {
	ID                  uuid.UUID `json:"id"`
	InitialImportStatus string    `json:"initial_import_status"`
}

// Unscoped, for the same reason as UpdateLinkedGitlabProjectLastSyncedAt.
// Values used: "pending" (default), "completed", "failed"
// (internal/projectsync).
func (q *Queries) UpdateLinkedGitlabProjectInitialImportStatus(ctx context.Context, arg UpdateLinkedGitlabProjectInitialImportStatusParams) (LinkedGitlabProject, error) {
	row := q.db.QueryRow(ctx, updateLinkedGitlabProjectInitialImportStatus, arg.ID, arg.InitialImportStatus)
	var i LinkedGitlabProject
	err := row.Scan(
		&i.ID,
		&i.GitlabConnectionID,
		&i.GitlabProjectID,
		&i.PathWithNamespace,
		&i.Name,
		&i.WebUrl,
		&i.SyncScope,
		&i.SyncLabels,
		&i.WebhookID,
		&i.EncryptedWebhookSecret,
		&i.WebhookRegisteredAt,
		&i.InitialImportStatus,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
		&i.WebhookRegistrationError,
	)
	return i, err
}

const updateLinkedGitlabProjectLastSyncedAt = `-- name: UpdateLinkedGitlabProjectLastSyncedAt :one
UPDATE linked_gitlab_projects
SET last_synced_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, gitlab_connection_id, gitlab_project_id, path_with_namespace, name, web_url, sync_scope, sync_labels, webhook_id, encrypted_webhook_secret, webhook_registered_at, initial_import_status, last_synced_at, created_at, updated_at, is_default, webhook_registration_error
`

// Unscoped, like GetLinkedGitlabProjectByID: called by the background
// worker (internal/projectsync) after a project.import/project.resync run
// finishes, which has no acting user to scope through.
func (q *Queries) UpdateLinkedGitlabProjectLastSyncedAt(ctx context.Context, id uuid.UUID) (LinkedGitlabProject, error) {
	row := q.db.QueryRow(ctx, updateLinkedGitlabProjectLastSyncedAt, id)
	var i LinkedGitlabProject
	err := row.Scan(
		&i.ID,
		&i.GitlabConnectionID,
		&i.GitlabProjectID,
		&i.PathWithNamespace,
		&i.Name,
		&i.WebUrl,
		&i.SyncScope,
		&i.SyncLabels,
		&i.WebhookID,
		&i.EncryptedWebhookSecret,
		&i.WebhookRegisteredAt,
		&i.InitialImportStatus,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
		&i.WebhookRegistrationError,
	)
	return i, err
}

const updateLinkedGitlabProjectSyncScopeForOwner = `-- name: UpdateLinkedGitlabProjectSyncScopeForOwner :one

UPDATE linked_gitlab_projects lgp
SET sync_scope = $2,
    sync_labels = $3,
    updated_at = now()
FROM gitlab_connections gc
WHERE lgp.id = $1 AND lgp.gitlab_connection_id = gc.id
    AND EXISTS (
      SELECT 1 FROM project_members pm
      WHERE pm.project_id = gc.project_id AND pm.user_id = $4 AND pm.role IN ('member', 'owner')
    )
RETURNING lgp.id, lgp.gitlab_connection_id, lgp.gitlab_project_id, lgp.path_with_namespace, lgp.name, lgp.web_url, lgp.sync_scope, lgp.sync_labels, lgp.webhook_id, lgp.encrypted_webhook_secret, lgp.webhook_registered_at, lgp.initial_import_status, lgp.last_synced_at, lgp.created_at, lgp.updated_at, lgp.is_default, lgp.webhook_registration_error
`

type UpdateLinkedGitlabProjectSyncScopeForOwnerParams struct {
	ID          uuid.UUID `json:"id"`
	SyncScope   string    `json:"sync_scope"`
	SyncLabels  []string  `json:"sync_labels"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

// Everything below is member-minimum (issue #99): using an already-connected
// project to link/sync is a member-level action, distinct from managing the
// connection's credential itself (owner-only, gitlab_connections.sql).
func (q *Queries) UpdateLinkedGitlabProjectSyncScopeForOwner(ctx context.Context, arg UpdateLinkedGitlabProjectSyncScopeForOwnerParams) (LinkedGitlabProject, error) {
	row := q.db.QueryRow(ctx, updateLinkedGitlabProjectSyncScopeForOwner,
		arg.ID,
		arg.SyncScope,
		arg.SyncLabels,
		arg.OwnerUserID,
	)
	var i LinkedGitlabProject
	err := row.Scan(
		&i.ID,
		&i.GitlabConnectionID,
		&i.GitlabProjectID,
		&i.PathWithNamespace,
		&i.Name,
		&i.WebUrl,
		&i.SyncScope,
		&i.SyncLabels,
		&i.WebhookID,
		&i.EncryptedWebhookSecret,
		&i.WebhookRegisteredAt,
		&i.InitialImportStatus,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
		&i.WebhookRegistrationError,
	)
	return i, err
}
