// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: linked_gitlab_projects.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearDefaultLinkedGitlabProjectsForOwner = `-- name: ClearDefaultLinkedGitlabProjectsForOwner :exec
UPDATE linked_gitlab_projects lgp
SET is_default = false,
    updated_at = now()
FROM gitlab_connections gc, projects p
WHERE lgp.gitlab_connection_id = gc.id AND gc.project_id = p.id
    AND p.owner_user_id = $2
    AND lgp.gitlab_connection_id = (
        SELECT orig.gitlab_connection_id FROM linked_gitlab_projects orig WHERE orig.id = $1
    )
    AND lgp.id != $1
`

type ClearDefaultLinkedGitlabProjectsForOwnerParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

// Unsets is_default on every other link in the same connection as linkID,
// so SetDefaultLinkedGitlabProjectForOwner can set exactly one.
func (q *Queries) ClearDefaultLinkedGitlabProjectsForOwner(ctx context.Context, arg ClearDefaultLinkedGitlabProjectsForOwnerParams) error {
	_, err := q.db.Exec(ctx, clearDefaultLinkedGitlabProjectsForOwner, arg.ID, arg.OwnerUserID)
	return err
}

const createLinkedGitlabProject = `-- name: CreateLinkedGitlabProject :one

INSERT INTO linked_gitlab_projects (
    gitlab_connection_id, gitlab_project_id, path_with_namespace, name, web_url,
    sync_scope, sync_labels, is_default
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    NOT EXISTS (SELECT 1 FROM linked_gitlab_projects WHERE gitlab_connection_id = $1)
)
RETURNING id, gitlab_connection_id, gitlab_project_id, path_with_namespace, name, web_url, sync_scope, sync_labels, webhook_id, encrypted_webhook_secret, webhook_registered_at, initial_import_status, last_synced_at, created_at, updated_at, is_default, webhook_registration_error
`

type CreateLinkedGitlabProjectParams struct {
	GitlabConnectionID uuid.UUID `json:"gitlab_connection_id"`
	GitlabProjectID    int64     `json:"gitlab_project_id"`
	PathWithNamespace  string    `json:"path_with_namespace"`
	Name               string    `json:"name"`
	WebUrl             string    `json:"web_url"`
	SyncScope          string    `json:"sync_scope"`
	SyncLabels         []string  `json:"sync_labels"`
}

// linked_gitlab_projects has no owner column of its own; ownership is always
// checked by joining through gitlab_connections to projects, the same way
// gitlab_connections is checked through projects. A link belonging to
// another user's project is indistinguishable from a missing one.
// is_default is computed here, not by the caller: the first project linked
// to a connection becomes its default, later ones do not.
func (q *Queries) CreateLinkedGitlabProject(ctx context.Context, arg CreateLinkedGitlabProjectParams) (LinkedGitlabProject, error) {
	row := q.db.QueryRow(ctx, createLinkedGitlabProject,
		arg.GitlabConnectionID,
		arg.GitlabProjectID,
		arg.PathWithNamespace,
		arg.Name,
		arg.WebUrl,
		arg.SyncScope,
		arg.SyncLabels,
	)
	var i LinkedGitlabProject
	err := row.Scan(
		&i.ID,
		&i.GitlabConnectionID,
		&i.GitlabProjectID,
		&i.PathWithNamespace,
		&i.Name,
		&i.WebUrl,
		&i.SyncScope,
		&i.SyncLabels,
		&i.WebhookID,
		&i.EncryptedWebhookSecret,
		&i.WebhookRegisteredAt,
		&i.InitialImportStatus,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
		&i.WebhookRegistrationError,
	)
	return i, err
}

const deleteLinkedGitlabProjectForOwner = `-- name: DeleteLinkedGitlabProjectForOwner :one
DELETE FROM linked_gitlab_projects lgp
USING gitlab_connections gc, projects p
WHERE lgp.id = $1 AND lgp.gitlab_connection_id = gc.id AND gc.project_id = p.id
    AND p.owner_user_id = $2
RETURNING lgp.id, lgp.gitlab_connection_id, lgp.gitlab_project_id, lgp.path_with_namespace, lgp.name, lgp.web_url, lgp.sync_scope, lgp.sync_labels, lgp.webhook_id, lgp.encrypted_webhook_secret, lgp.webhook_registered_at, lgp.initial_import_status, lgp.last_synced_at, lgp.created_at, lgp.updated_at, lgp.is_default, lgp.webhook_registration_error
`

type DeleteLinkedGitlabProjectForOwnerParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

// Returns the deleted row (rather than an affected-row count) so the
// service can tell whether it removed the default link and needs to
// promote another one.
func (q *Queries) DeleteLinkedGitlabProjectForOwner(ctx context.Context, arg DeleteLinkedGitlabProjectForOwnerParams) (LinkedGitlabProject, error) {
	row := q.db.QueryRow(ctx, deleteLinkedGitlabProjectForOwner, arg.ID, arg.OwnerUserID)
	var i LinkedGitlabProject
	err := row.Scan(
		&i.ID,
		&i.GitlabConnectionID,
		&i.GitlabProjectID,
		&i.PathWithNamespace,
		&i.Name,
		&i.WebUrl,
		&i.SyncScope,
		&i.SyncLabels,
		&i.WebhookID,
		&i.EncryptedWebhookSecret,
		&i.WebhookRegisteredAt,
		&i.InitialImportStatus,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
		&i.WebhookRegistrationError,
	)
	return i, err
}

const getLinkedGitlabProjectForOwner = `-- name: GetLinkedGitlabProjectForOwner :one
SELECT lgp.id, lgp.gitlab_connection_id, lgp.gitlab_project_id, lgp.path_with_namespace, lgp.name, lgp.web_url, lgp.sync_scope, lgp.sync_labels, lgp.webhook_id, lgp.encrypted_webhook_secret, lgp.webhook_registered_at, lgp.initial_import_status, lgp.last_synced_at, lgp.created_at, lgp.updated_at, lgp.is_default, lgp.webhook_registration_error
FROM linked_gitlab_projects lgp
JOIN gitlab_connections gc ON gc.id = lgp.gitlab_connection_id
JOIN projects p ON p.id = gc.project_id
WHERE lgp.id = $1 AND p.owner_user_id = $2
`

type GetLinkedGitlabProjectForOwnerParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) GetLinkedGitlabProjectForOwner(ctx context.Context, arg GetLinkedGitlabProjectForOwnerParams) (LinkedGitlabProject, error) {
	row := q.db.QueryRow(ctx, getLinkedGitlabProjectForOwner, arg.ID, arg.OwnerUserID)
	var i LinkedGitlabProject
	err := row.Scan(
		&i.ID,
		&i.GitlabConnectionID,
		&i.GitlabProjectID,
		&i.PathWithNamespace,
		&i.Name,
		&i.WebUrl,
		&i.SyncScope,
		&i.SyncLabels,
		&i.WebhookID,
		&i.EncryptedWebhookSecret,
		&i.WebhookRegisteredAt,
		&i.InitialImportStatus,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
		&i.WebhookRegistrationError,
	)
	return i, err
}

const listLinkedGitlabProjectsForOwner = `-- name: ListLinkedGitlabProjectsForOwner :many
SELECT lgp.id, lgp.gitlab_connection_id, lgp.gitlab_project_id, lgp.path_with_namespace, lgp.name, lgp.web_url, lgp.sync_scope, lgp.sync_labels, lgp.webhook_id, lgp.encrypted_webhook_secret, lgp.webhook_registered_at, lgp.initial_import_status, lgp.last_synced_at, lgp.created_at, lgp.updated_at, lgp.is_default, lgp.webhook_registration_error
FROM linked_gitlab_projects lgp
JOIN gitlab_connections gc ON gc.id = lgp.gitlab_connection_id
JOIN projects p ON p.id = gc.project_id
WHERE p.id = $1 AND p.owner_user_id = $2
ORDER BY lgp.created_at
`

type ListLinkedGitlabProjectsForOwnerParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) ListLinkedGitlabProjectsForOwner(ctx context.Context, arg ListLinkedGitlabProjectsForOwnerParams) ([]LinkedGitlabProject, error) {
	rows, err := q.db.Query(ctx, listLinkedGitlabProjectsForOwner, arg.ID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LinkedGitlabProject{}
	for rows.Next() {
		var i LinkedGitlabProject
		if err := rows.Scan(
			&i.ID,
			&i.GitlabConnectionID,
			&i.GitlabProjectID,
			&i.PathWithNamespace,
			&i.Name,
			&i.WebUrl,
			&i.SyncScope,
			&i.SyncLabels,
			&i.WebhookID,
			&i.EncryptedWebhookSecret,
			&i.WebhookRegisteredAt,
			&i.InitialImportStatus,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDefault,
			&i.WebhookRegistrationError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteOldestLinkedGitlabProjectAsDefault = `-- name: PromoteOldestLinkedGitlabProjectAsDefault :exec
UPDATE linked_gitlab_projects
SET is_default = true, updated_at = now()
WHERE id = (
    SELECT candidate.id FROM linked_gitlab_projects candidate
    WHERE candidate.gitlab_connection_id = $1
    ORDER BY candidate.created_at
    LIMIT 1
)
`

// Used after deleting the default link: makes the oldest remaining link in
// the same connection the new default. A no-op if none remain.
func (q *Queries) PromoteOldestLinkedGitlabProjectAsDefault(ctx context.Context, gitlabConnectionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, promoteOldestLinkedGitlabProjectAsDefault, gitlabConnectionID)
	return err
}

const setDefaultLinkedGitlabProjectForOwner = `-- name: SetDefaultLinkedGitlabProjectForOwner :one
UPDATE linked_gitlab_projects lgp
SET is_default = true,
    updated_at = now()
FROM gitlab_connections gc, projects p
WHERE lgp.id = $1 AND lgp.gitlab_connection_id = gc.id AND gc.project_id = p.id
    AND p.owner_user_id = $2
RETURNING lgp.id, lgp.gitlab_connection_id, lgp.gitlab_project_id, lgp.path_with_namespace, lgp.name, lgp.web_url, lgp.sync_scope, lgp.sync_labels, lgp.webhook_id, lgp.encrypted_webhook_secret, lgp.webhook_registered_at, lgp.initial_import_status, lgp.last_synced_at, lgp.created_at, lgp.updated_at, lgp.is_default, lgp.webhook_registration_error
`

type SetDefaultLinkedGitlabProjectForOwnerParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) SetDefaultLinkedGitlabProjectForOwner(ctx context.Context, arg SetDefaultLinkedGitlabProjectForOwnerParams) (LinkedGitlabProject, error) {
	row := q.db.QueryRow(ctx, setDefaultLinkedGitlabProjectForOwner, arg.ID, arg.OwnerUserID)
	var i LinkedGitlabProject
	err := row.Scan(
		&i.ID,
		&i.GitlabConnectionID,
		&i.GitlabProjectID,
		&i.PathWithNamespace,
		&i.Name,
		&i.WebUrl,
		&i.SyncScope,
		&i.SyncLabels,
		&i.WebhookID,
		&i.EncryptedWebhookSecret,
		&i.WebhookRegisteredAt,
		&i.InitialImportStatus,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
		&i.WebhookRegistrationError,
	)
	return i, err
}

const setLinkedGitlabProjectWebhookErrorForOwner = `-- name: SetLinkedGitlabProjectWebhookErrorForOwner :one
UPDATE linked_gitlab_projects lgp
SET webhook_registration_error = $3,
    updated_at = now()
FROM gitlab_connections gc, projects p
WHERE lgp.id = $1 AND lgp.gitlab_connection_id = gc.id AND gc.project_id = p.id
    AND p.owner_user_id = $2
RETURNING lgp.id, lgp.gitlab_connection_id, lgp.gitlab_project_id, lgp.path_with_namespace, lgp.name, lgp.web_url, lgp.sync_scope, lgp.sync_labels, lgp.webhook_id, lgp.encrypted_webhook_secret, lgp.webhook_registered_at, lgp.initial_import_status, lgp.last_synced_at, lgp.created_at, lgp.updated_at, lgp.is_default, lgp.webhook_registration_error
`

type SetLinkedGitlabProjectWebhookErrorForOwnerParams struct {
	ID                       uuid.UUID `json:"id"`
	OwnerUserID              uuid.UUID `json:"owner_user_id"`
	WebhookRegistrationError string    `json:"webhook_registration_error"`
}

// Records why registering or repairing a webhook failed (most commonly
// insufficient GitLab permissions) without touching any existing
// webhook_id, so the link stays usable via manual sync.
func (q *Queries) SetLinkedGitlabProjectWebhookErrorForOwner(ctx context.Context, arg SetLinkedGitlabProjectWebhookErrorForOwnerParams) (LinkedGitlabProject, error) {
	row := q.db.QueryRow(ctx, setLinkedGitlabProjectWebhookErrorForOwner, arg.ID, arg.OwnerUserID, arg.WebhookRegistrationError)
	var i LinkedGitlabProject
	err := row.Scan(
		&i.ID,
		&i.GitlabConnectionID,
		&i.GitlabProjectID,
		&i.PathWithNamespace,
		&i.Name,
		&i.WebUrl,
		&i.SyncScope,
		&i.SyncLabels,
		&i.WebhookID,
		&i.EncryptedWebhookSecret,
		&i.WebhookRegisteredAt,
		&i.InitialImportStatus,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
		&i.WebhookRegistrationError,
	)
	return i, err
}

const setLinkedGitlabProjectWebhookForOwner = `-- name: SetLinkedGitlabProjectWebhookForOwner :one
UPDATE linked_gitlab_projects lgp
SET webhook_id = $3,
    encrypted_webhook_secret = $4,
    webhook_registered_at = now(),
    webhook_registration_error = '',
    updated_at = now()
FROM gitlab_connections gc, projects p
WHERE lgp.id = $1 AND lgp.gitlab_connection_id = gc.id AND gc.project_id = p.id
    AND p.owner_user_id = $2
RETURNING lgp.id, lgp.gitlab_connection_id, lgp.gitlab_project_id, lgp.path_with_namespace, lgp.name, lgp.web_url, lgp.sync_scope, lgp.sync_labels, lgp.webhook_id, lgp.encrypted_webhook_secret, lgp.webhook_registered_at, lgp.initial_import_status, lgp.last_synced_at, lgp.created_at, lgp.updated_at, lgp.is_default, lgp.webhook_registration_error
`

type SetLinkedGitlabProjectWebhookForOwnerParams struct {
	ID                     uuid.UUID   `json:"id"`
	OwnerUserID            uuid.UUID   `json:"owner_user_id"`
	WebhookID              pgtype.Int8 `json:"webhook_id"`
	EncryptedWebhookSecret []byte      `json:"encrypted_webhook_secret"`
}

// Records a successful webhook registration or rotation (issue #18) and
// clears any earlier registration error.
func (q *Queries) SetLinkedGitlabProjectWebhookForOwner(ctx context.Context, arg SetLinkedGitlabProjectWebhookForOwnerParams) (LinkedGitlabProject, error) {
	row := q.db.QueryRow(ctx, setLinkedGitlabProjectWebhookForOwner,
		arg.ID,
		arg.OwnerUserID,
		arg.WebhookID,
		arg.EncryptedWebhookSecret,
	)
	var i LinkedGitlabProject
	err := row.Scan(
		&i.ID,
		&i.GitlabConnectionID,
		&i.GitlabProjectID,
		&i.PathWithNamespace,
		&i.Name,
		&i.WebUrl,
		&i.SyncScope,
		&i.SyncLabels,
		&i.WebhookID,
		&i.EncryptedWebhookSecret,
		&i.WebhookRegisteredAt,
		&i.InitialImportStatus,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
		&i.WebhookRegistrationError,
	)
	return i, err
}

const updateLinkedGitlabProjectSyncScopeForOwner = `-- name: UpdateLinkedGitlabProjectSyncScopeForOwner :one
UPDATE linked_gitlab_projects lgp
SET sync_scope = $3,
    sync_labels = $4,
    updated_at = now()
FROM gitlab_connections gc, projects p
WHERE lgp.id = $1 AND lgp.gitlab_connection_id = gc.id AND gc.project_id = p.id
    AND p.owner_user_id = $2
RETURNING lgp.id, lgp.gitlab_connection_id, lgp.gitlab_project_id, lgp.path_with_namespace, lgp.name, lgp.web_url, lgp.sync_scope, lgp.sync_labels, lgp.webhook_id, lgp.encrypted_webhook_secret, lgp.webhook_registered_at, lgp.initial_import_status, lgp.last_synced_at, lgp.created_at, lgp.updated_at, lgp.is_default, lgp.webhook_registration_error
`

type UpdateLinkedGitlabProjectSyncScopeForOwnerParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
	SyncScope   string    `json:"sync_scope"`
	SyncLabels  []string  `json:"sync_labels"`
}

func (q *Queries) UpdateLinkedGitlabProjectSyncScopeForOwner(ctx context.Context, arg UpdateLinkedGitlabProjectSyncScopeForOwnerParams) (LinkedGitlabProject, error) {
	row := q.db.QueryRow(ctx, updateLinkedGitlabProjectSyncScopeForOwner,
		arg.ID,
		arg.OwnerUserID,
		arg.SyncScope,
		arg.SyncLabels,
	)
	var i LinkedGitlabProject
	err := row.Scan(
		&i.ID,
		&i.GitlabConnectionID,
		&i.GitlabProjectID,
		&i.PathWithNamespace,
		&i.Name,
		&i.WebUrl,
		&i.SyncScope,
		&i.SyncLabels,
		&i.WebhookID,
		&i.EncryptedWebhookSecret,
		&i.WebhookRegisteredAt,
		&i.InitialImportStatus,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
		&i.WebhookRegistrationError,
	)
	return i, err
}
