// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: merge_requests.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countMergeRequestsByProject = `-- name: CountMergeRequestsByProject :one

SELECT count(*)
FROM merge_requests mr
JOIN repositories r ON r.id = mr.repository_id
JOIN linked_gitlab_projects lgp ON lgp.id = r.linked_gitlab_project_id
JOIN gitlab_connections gc ON gc.id = lgp.gitlab_connection_id
WHERE gc.project_id = $1
  AND EXISTS (
    SELECT 1 FROM project_members pm
    WHERE pm.project_id = gc.project_id AND pm.user_id = $2
  )
  AND ($3::text = '' OR mr.state = $3)
  AND ($4::text = '' OR mr.author_gitlab_username = $4)
  AND ($5::uuid IS NULL OR mr.task_id = $5)
  AND ($6::timestamptz IS NULL OR mr.gitlab_created_at >= $6)
  AND ($7::timestamptz IS NULL OR mr.gitlab_created_at <= $7)
`

type CountMergeRequestsByProjectParams struct {
	ProjectID   uuid.UUID          `json:"project_id"`
	OwnerUserID uuid.UUID          `json:"owner_user_id"`
	State       string             `json:"state"`
	Author      string             `json:"author"`
	TaskID      pgtype.UUID        `json:"task_id"`
	Since       pgtype.Timestamptz `json:"since"`
	Until       pgtype.Timestamptz `json:"until"`
}

// CountMergeRequestsByProject is ListMergeRequestsByProject's total, with
// the same scoping and the same filters, minus the ordering and paging. The
// collection view needs it because the paged list can no longer be counted
// client-side by its length, and the project sidebar's merge-request badge
// is a count rather than a list — it used to fetch every row just to read
// .length off it.
func (q *Queries) CountMergeRequestsByProject(ctx context.Context, arg CountMergeRequestsByProjectParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMergeRequestsByProject,
		arg.ProjectID,
		arg.OwnerUserID,
		arg.State,
		arg.Author,
		arg.TaskID,
		arg.Since,
		arg.Until,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMergeRequest = `-- name: CreateMergeRequest :one

INSERT INTO merge_requests (
    repository_id, gitlab_merge_request_id, number, title, state, is_draft,
    author_gitlab_username, author_avatar_url, base_branch, head_branch,
    gitlab_created_at, gitlab_updated_at, merged_at, closed_at, html_url,
    pipeline_status, pipeline_id, pipeline_updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18
)
RETURNING id, repository_id, gitlab_merge_request_id, number, title, state, is_draft, author_gitlab_username, author_avatar_url, base_branch, head_branch, additions, deletions, changed_files, gitlab_created_at, gitlab_updated_at, merged_at, closed_at, html_url, created_at, updated_at, first_reviewed_at, pipeline_status, pipeline_id, pipeline_updated_at, task_id
`

type CreateMergeRequestParams struct {
	RepositoryID         uuid.UUID          `json:"repository_id"`
	GitlabMergeRequestID int64              `json:"gitlab_merge_request_id"`
	Number               int32              `json:"number"`
	Title                string             `json:"title"`
	State                string             `json:"state"`
	IsDraft              bool               `json:"is_draft"`
	AuthorGitlabUsername string             `json:"author_gitlab_username"`
	AuthorAvatarUrl      string             `json:"author_avatar_url"`
	BaseBranch           string             `json:"base_branch"`
	HeadBranch           string             `json:"head_branch"`
	GitlabCreatedAt      pgtype.Timestamptz `json:"gitlab_created_at"`
	GitlabUpdatedAt      pgtype.Timestamptz `json:"gitlab_updated_at"`
	MergedAt             pgtype.Timestamptz `json:"merged_at"`
	ClosedAt             pgtype.Timestamptz `json:"closed_at"`
	HtmlUrl              string             `json:"html_url"`
	PipelineStatus       string             `json:"pipeline_status"`
	PipelineID           pgtype.Int8        `json:"pipeline_id"`
	PipelineUpdatedAt    pgtype.Timestamptz `json:"pipeline_updated_at"`
}

// merge_requests mirrors a repository's GitLab merge requests, read-only
// (issue #111: FlowLens never writes back to GitLab). Idempotency comes
// from the UNIQUE constraint on gitlab_merge_request_id, the same shape as
// task_gitlab_links' issue-iid uniqueness.
func (q *Queries) CreateMergeRequest(ctx context.Context, arg CreateMergeRequestParams) (MergeRequest, error) {
	row := q.db.QueryRow(ctx, createMergeRequest,
		arg.RepositoryID,
		arg.GitlabMergeRequestID,
		arg.Number,
		arg.Title,
		arg.State,
		arg.IsDraft,
		arg.AuthorGitlabUsername,
		arg.AuthorAvatarUrl,
		arg.BaseBranch,
		arg.HeadBranch,
		arg.GitlabCreatedAt,
		arg.GitlabUpdatedAt,
		arg.MergedAt,
		arg.ClosedAt,
		arg.HtmlUrl,
		arg.PipelineStatus,
		arg.PipelineID,
		arg.PipelineUpdatedAt,
	)
	var i MergeRequest
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.GitlabMergeRequestID,
		&i.Number,
		&i.Title,
		&i.State,
		&i.IsDraft,
		&i.AuthorGitlabUsername,
		&i.AuthorAvatarUrl,
		&i.BaseBranch,
		&i.HeadBranch,
		&i.Additions,
		&i.Deletions,
		&i.ChangedFiles,
		&i.GitlabCreatedAt,
		&i.GitlabUpdatedAt,
		&i.MergedAt,
		&i.ClosedAt,
		&i.HtmlUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstReviewedAt,
		&i.PipelineStatus,
		&i.PipelineID,
		&i.PipelineUpdatedAt,
		&i.TaskID,
	)
	return i, err
}

const getMergeRequestByGitlabMergeRequestID = `-- name: GetMergeRequestByGitlabMergeRequestID :one
SELECT id, repository_id, gitlab_merge_request_id, number, title, state, is_draft, author_gitlab_username, author_avatar_url, base_branch, head_branch, additions, deletions, changed_files, gitlab_created_at, gitlab_updated_at, merged_at, closed_at, html_url, created_at, updated_at, first_reviewed_at, pipeline_status, pipeline_id, pipeline_updated_at, task_id FROM merge_requests WHERE gitlab_merge_request_id = $1
`

func (q *Queries) GetMergeRequestByGitlabMergeRequestID(ctx context.Context, gitlabMergeRequestID int64) (MergeRequest, error) {
	row := q.db.QueryRow(ctx, getMergeRequestByGitlabMergeRequestID, gitlabMergeRequestID)
	var i MergeRequest
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.GitlabMergeRequestID,
		&i.Number,
		&i.Title,
		&i.State,
		&i.IsDraft,
		&i.AuthorGitlabUsername,
		&i.AuthorAvatarUrl,
		&i.BaseBranch,
		&i.HeadBranch,
		&i.Additions,
		&i.Deletions,
		&i.ChangedFiles,
		&i.GitlabCreatedAt,
		&i.GitlabUpdatedAt,
		&i.MergedAt,
		&i.ClosedAt,
		&i.HtmlUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstReviewedAt,
		&i.PipelineStatus,
		&i.PipelineID,
		&i.PipelineUpdatedAt,
		&i.TaskID,
	)
	return i, err
}

const getMergeRequestByRepositoryAndNumber = `-- name: GetMergeRequestByRepositoryAndNumber :one

SELECT id, repository_id, gitlab_merge_request_id, number, title, state, is_draft, author_gitlab_username, author_avatar_url, base_branch, head_branch, additions, deletions, changed_files, gitlab_created_at, gitlab_updated_at, merged_at, closed_at, html_url, created_at, updated_at, first_reviewed_at, pipeline_status, pipeline_id, pipeline_updated_at, task_id FROM merge_requests WHERE repository_id = $1 AND number = $2
`

type GetMergeRequestByRepositoryAndNumberParams struct {
	RepositoryID uuid.UUID `json:"repository_id"`
	Number       int32     `json:"number"`
}

// GetMergeRequestByRepositoryAndNumber looks up a merge request by its
// project-scoped IID (the "number" column) rather than its global GitLab
// id — the key a "Pipeline Hook" delivery's merge_request.iid gives
// (internal/webhookapply), unlike an MR event's own object_attributes.id.
func (q *Queries) GetMergeRequestByRepositoryAndNumber(ctx context.Context, arg GetMergeRequestByRepositoryAndNumberParams) (MergeRequest, error) {
	row := q.db.QueryRow(ctx, getMergeRequestByRepositoryAndNumber, arg.RepositoryID, arg.Number)
	var i MergeRequest
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.GitlabMergeRequestID,
		&i.Number,
		&i.Title,
		&i.State,
		&i.IsDraft,
		&i.AuthorGitlabUsername,
		&i.AuthorAvatarUrl,
		&i.BaseBranch,
		&i.HeadBranch,
		&i.Additions,
		&i.Deletions,
		&i.ChangedFiles,
		&i.GitlabCreatedAt,
		&i.GitlabUpdatedAt,
		&i.MergedAt,
		&i.ClosedAt,
		&i.HtmlUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstReviewedAt,
		&i.PipelineStatus,
		&i.PipelineID,
		&i.PipelineUpdatedAt,
		&i.TaskID,
	)
	return i, err
}

const getMergeRequestForOwner = `-- name: GetMergeRequestForOwner :one

SELECT mr.id, mr.repository_id, mr.gitlab_merge_request_id, mr.number, mr.title, mr.state, mr.is_draft, mr.author_gitlab_username, mr.author_avatar_url, mr.base_branch, mr.head_branch, mr.additions, mr.deletions, mr.changed_files, mr.gitlab_created_at, mr.gitlab_updated_at, mr.merged_at, mr.closed_at, mr.html_url, mr.created_at, mr.updated_at, mr.first_reviewed_at, mr.pipeline_status, mr.pipeline_id, mr.pipeline_updated_at, mr.task_id
FROM merge_requests mr
JOIN repositories r ON r.id = mr.repository_id
JOIN linked_gitlab_projects lgp ON lgp.id = r.linked_gitlab_project_id
JOIN gitlab_connections gc ON gc.id = lgp.gitlab_connection_id
WHERE mr.id = $1
  AND EXISTS (
    SELECT 1 FROM project_members pm
    WHERE pm.project_id = gc.project_id AND pm.user_id = $2
  )
`

type GetMergeRequestForOwnerParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

// GetMergeRequestForOwner is ListMergeRequestsByProject's single-object
// counterpart, backing the merge-request single view. Scoped the same way,
// so a merge request belonging to a project the caller isn't a member of is
// indistinguishable from one that doesn't exist.
func (q *Queries) GetMergeRequestForOwner(ctx context.Context, arg GetMergeRequestForOwnerParams) (MergeRequest, error) {
	row := q.db.QueryRow(ctx, getMergeRequestForOwner, arg.ID, arg.OwnerUserID)
	var i MergeRequest
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.GitlabMergeRequestID,
		&i.Number,
		&i.Title,
		&i.State,
		&i.IsDraft,
		&i.AuthorGitlabUsername,
		&i.AuthorAvatarUrl,
		&i.BaseBranch,
		&i.HeadBranch,
		&i.Additions,
		&i.Deletions,
		&i.ChangedFiles,
		&i.GitlabCreatedAt,
		&i.GitlabUpdatedAt,
		&i.MergedAt,
		&i.ClosedAt,
		&i.HtmlUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstReviewedAt,
		&i.PipelineStatus,
		&i.PipelineID,
		&i.PipelineUpdatedAt,
		&i.TaskID,
	)
	return i, err
}

const getMergeRequestProjectID = `-- name: GetMergeRequestProjectID :one

SELECT gc.project_id
FROM merge_requests mr
JOIN repositories r ON r.id = mr.repository_id
JOIN linked_gitlab_projects lgp ON lgp.id = r.linked_gitlab_project_id
JOIN gitlab_connections gc ON gc.id = lgp.gitlab_connection_id
WHERE mr.id = $1
`

// GetMergeRequestProjectID is the lightweight, unscoped lookup
// requireTokenResourceProject (internal/http, issue #66) uses to enforce a
// bearer token's project boundary on a single-merge-request URL, the same
// role GetTaskProjectID plays for tasks.
func (q *Queries) GetMergeRequestProjectID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getMergeRequestProjectID, id)
	var project_id uuid.UUID
	err := row.Scan(&project_id)
	return project_id, err
}

const listMergeRequestsByProject = `-- name: ListMergeRequestsByProject :many

SELECT mr.id, mr.repository_id, mr.gitlab_merge_request_id, mr.number, mr.title, mr.state, mr.is_draft, mr.author_gitlab_username, mr.author_avatar_url, mr.base_branch, mr.head_branch, mr.additions, mr.deletions, mr.changed_files, mr.gitlab_created_at, mr.gitlab_updated_at, mr.merged_at, mr.closed_at, mr.html_url, mr.created_at, mr.updated_at, mr.first_reviewed_at, mr.pipeline_status, mr.pipeline_id, mr.pipeline_updated_at, mr.task_id
FROM merge_requests mr
JOIN repositories r ON r.id = mr.repository_id
JOIN linked_gitlab_projects lgp ON lgp.id = r.linked_gitlab_project_id
JOIN gitlab_connections gc ON gc.id = lgp.gitlab_connection_id
WHERE gc.project_id = $1
  AND EXISTS (
    SELECT 1 FROM project_members pm
    WHERE pm.project_id = gc.project_id AND pm.user_id = $2
  )
  AND ($3::text = '' OR mr.state = $3)
  AND ($4::text = '' OR mr.author_gitlab_username = $4)
  AND ($5::uuid IS NULL OR mr.task_id = $5)
  AND ($6::timestamptz IS NULL OR mr.gitlab_created_at >= $6)
  AND ($7::timestamptz IS NULL OR mr.gitlab_created_at <= $7)
ORDER BY
  (CASE WHEN $8::boolean THEN mr.gitlab_updated_at ELSE mr.gitlab_created_at END) DESC NULLS LAST,
  mr.created_at DESC
LIMIT $10 OFFSET $9
`

type ListMergeRequestsByProjectParams struct {
	ProjectID     uuid.UUID          `json:"project_id"`
	OwnerUserID   uuid.UUID          `json:"owner_user_id"`
	State         string             `json:"state"`
	Author        string             `json:"author"`
	TaskID        pgtype.UUID        `json:"task_id"`
	Since         pgtype.Timestamptz `json:"since"`
	Until         pgtype.Timestamptz `json:"until"`
	SortByUpdated bool               `json:"sort_by_updated"`
	OffsetCount   int32              `json:"offset_count"`
	LimitCount    int32              `json:"limit_count"`
}

// ListMergeRequestsByProject backs the merge-request collection view (issue
// #112), scoped through repositories -> linked_gitlab_projects ->
// gitlab_connections to the app project the caller is a member of, the same
// project_members EXISTS check GetTaskForOwner uses. state/author/task_id
// follow ListTasksByProject's "empty/NULL disables it" convention;
// since/until bound gitlab_created_at. sort_by_updated switches the primary
// order from gitlab_created_at to gitlab_updated_at, both DESC with created_at
// as the tiebreak, so a merge request with no GitLab timestamp yet still
// sorts deterministically.
//
// LIMIT/OFFSET paging follows the same "fetch one extra row to detect a next
// page" convention ListWebhookEventsByLinkedGitlabProjectID/internal/webhookevent
// established: a long-lived repository accumulates thousands of merged merge
// requests, and this view used to return every one of them in a single
// response. idx_merge_requests_repo_state_{created,updated} (migration 28)
// back both orderings.
func (q *Queries) ListMergeRequestsByProject(ctx context.Context, arg ListMergeRequestsByProjectParams) ([]MergeRequest, error) {
	rows, err := q.db.Query(ctx, listMergeRequestsByProject,
		arg.ProjectID,
		arg.OwnerUserID,
		arg.State,
		arg.Author,
		arg.TaskID,
		arg.Since,
		arg.Until,
		arg.SortByUpdated,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MergeRequest{}
	for rows.Next() {
		var i MergeRequest
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.GitlabMergeRequestID,
			&i.Number,
			&i.Title,
			&i.State,
			&i.IsDraft,
			&i.AuthorGitlabUsername,
			&i.AuthorAvatarUrl,
			&i.BaseBranch,
			&i.HeadBranch,
			&i.Additions,
			&i.Deletions,
			&i.ChangedFiles,
			&i.GitlabCreatedAt,
			&i.GitlabUpdatedAt,
			&i.MergedAt,
			&i.ClosedAt,
			&i.HtmlUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstReviewedAt,
			&i.PipelineStatus,
			&i.PipelineID,
			&i.PipelineUpdatedAt,
			&i.TaskID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMergeRequestsForMetrics = `-- name: ListMergeRequestsForMetrics :many

SELECT mr.state, mr.additions, mr.deletions, mr.changed_files, mr.gitlab_created_at, mr.merged_at, mr.first_reviewed_at, mr.pipeline_status
FROM merge_requests mr
JOIN repositories r ON r.id = mr.repository_id
JOIN linked_gitlab_projects lgp ON lgp.id = r.linked_gitlab_project_id
JOIN gitlab_connections gc ON gc.id = lgp.gitlab_connection_id
WHERE gc.project_id = $1
  AND EXISTS (
    SELECT 1 FROM project_members pm
    WHERE pm.project_id = gc.project_id AND pm.user_id = $2
  )
  AND ($3::timestamptz IS NULL OR mr.gitlab_created_at >= $3)
  AND ($4::timestamptz IS NULL OR mr.gitlab_created_at <= $4)
`

type ListMergeRequestsForMetricsParams struct {
	ProjectID   uuid.UUID          `json:"project_id"`
	OwnerUserID uuid.UUID          `json:"owner_user_id"`
	Since       pgtype.Timestamptz `json:"since"`
	Until       pgtype.Timestamptz `json:"until"`
}

type ListMergeRequestsForMetricsRow struct {
	State           string             `json:"state"`
	Additions       int32              `json:"additions"`
	Deletions       int32              `json:"deletions"`
	ChangedFiles    int32              `json:"changed_files"`
	GitlabCreatedAt pgtype.Timestamptz `json:"gitlab_created_at"`
	MergedAt        pgtype.Timestamptz `json:"merged_at"`
	FirstReviewedAt pgtype.Timestamptz `json:"first_reviewed_at"`
	PipelineStatus  string             `json:"pipeline_status"`
}

// ListMergeRequestsForMetrics backs the delivery-metrics aggregation (issue
// #113): the narrow column set deliverymetrics.Service needs to compute
// median/p90 durations, size distribution, pipeline success rate and
// throughput in the application layer, following docs/testing.md's "test
// aggregation/derivation logic at the domain layer with fakes" guidance.
// Scoped and filtered exactly like ListMergeRequestsByProject (same
// project_members check, same since/until bounding gitlab_created_at), minus
// the state/author/task_id/sort filters that view alone needs.
func (q *Queries) ListMergeRequestsForMetrics(ctx context.Context, arg ListMergeRequestsForMetricsParams) ([]ListMergeRequestsForMetricsRow, error) {
	rows, err := q.db.Query(ctx, listMergeRequestsForMetrics,
		arg.ProjectID,
		arg.OwnerUserID,
		arg.Since,
		arg.Until,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMergeRequestsForMetricsRow{}
	for rows.Next() {
		var i ListMergeRequestsForMetricsRow
		if err := rows.Scan(
			&i.State,
			&i.Additions,
			&i.Deletions,
			&i.ChangedFiles,
			&i.GitlabCreatedAt,
			&i.MergedAt,
			&i.FirstReviewedAt,
			&i.PipelineStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMergeRequest = `-- name: UpdateMergeRequest :one

UPDATE merge_requests
SET title = $2,
    state = $3,
    is_draft = $4,
    author_gitlab_username = $5,
    author_avatar_url = $6,
    base_branch = $7,
    head_branch = $8,
    gitlab_updated_at = COALESCE($9, gitlab_updated_at),
    merged_at = $10,
    closed_at = $11,
    html_url = $12,
    pipeline_status = $13,
    pipeline_id = $14,
    pipeline_updated_at = $15,
    updated_at = now()
WHERE gitlab_merge_request_id = $1
RETURNING id, repository_id, gitlab_merge_request_id, number, title, state, is_draft, author_gitlab_username, author_avatar_url, base_branch, head_branch, additions, deletions, changed_files, gitlab_created_at, gitlab_updated_at, merged_at, closed_at, html_url, created_at, updated_at, first_reviewed_at, pipeline_status, pipeline_id, pipeline_updated_at, task_id
`

type UpdateMergeRequestParams struct {
	GitlabMergeRequestID int64              `json:"gitlab_merge_request_id"`
	Title                string             `json:"title"`
	State                string             `json:"state"`
	IsDraft              bool               `json:"is_draft"`
	AuthorGitlabUsername string             `json:"author_gitlab_username"`
	AuthorAvatarUrl      string             `json:"author_avatar_url"`
	BaseBranch           string             `json:"base_branch"`
	HeadBranch           string             `json:"head_branch"`
	GitlabUpdatedAt      pgtype.Timestamptz `json:"gitlab_updated_at"`
	MergedAt             pgtype.Timestamptz `json:"merged_at"`
	ClosedAt             pgtype.Timestamptz `json:"closed_at"`
	HtmlUrl              string             `json:"html_url"`
	PipelineStatus       string             `json:"pipeline_status"`
	PipelineID           pgtype.Int8        `json:"pipeline_id"`
	PipelineUpdatedAt    pgtype.Timestamptz `json:"pipeline_updated_at"`
}

// UpdateMergeRequest applies the latest GitLab-sourced fields to an
// already-imported merge request. first_reviewed_at and task_id are
// intentionally not touched here — see UpdateMergeRequestFirstReviewedAt
// and UpdateMergeRequestTaskID, which set them at most once each.
// gitlab_updated_at is COALESCEd rather than written unconditionally: a
// delivery whose updated_at didn't parse (issue #183) passes NULL, and that
// must never erase an already-recorded baseline (see the same reasoning on
// MarkTaskGitlabLinkAppliedForTask in task_gitlab_links.sql).
func (q *Queries) UpdateMergeRequest(ctx context.Context, arg UpdateMergeRequestParams) (MergeRequest, error) {
	row := q.db.QueryRow(ctx, updateMergeRequest,
		arg.GitlabMergeRequestID,
		arg.Title,
		arg.State,
		arg.IsDraft,
		arg.AuthorGitlabUsername,
		arg.AuthorAvatarUrl,
		arg.BaseBranch,
		arg.HeadBranch,
		arg.GitlabUpdatedAt,
		arg.MergedAt,
		arg.ClosedAt,
		arg.HtmlUrl,
		arg.PipelineStatus,
		arg.PipelineID,
		arg.PipelineUpdatedAt,
	)
	var i MergeRequest
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.GitlabMergeRequestID,
		&i.Number,
		&i.Title,
		&i.State,
		&i.IsDraft,
		&i.AuthorGitlabUsername,
		&i.AuthorAvatarUrl,
		&i.BaseBranch,
		&i.HeadBranch,
		&i.Additions,
		&i.Deletions,
		&i.ChangedFiles,
		&i.GitlabCreatedAt,
		&i.GitlabUpdatedAt,
		&i.MergedAt,
		&i.ClosedAt,
		&i.HtmlUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstReviewedAt,
		&i.PipelineStatus,
		&i.PipelineID,
		&i.PipelineUpdatedAt,
		&i.TaskID,
	)
	return i, err
}

const updateMergeRequestFirstReviewedAt = `-- name: UpdateMergeRequestFirstReviewedAt :one

UPDATE merge_requests
SET first_reviewed_at = $2
WHERE id = $1 AND first_reviewed_at IS NULL
RETURNING id, repository_id, gitlab_merge_request_id, number, title, state, is_draft, author_gitlab_username, author_avatar_url, base_branch, head_branch, additions, deletions, changed_files, gitlab_created_at, gitlab_updated_at, merged_at, closed_at, html_url, created_at, updated_at, first_reviewed_at, pipeline_status, pipeline_id, pipeline_updated_at, task_id
`

type UpdateMergeRequestFirstReviewedAtParams struct {
	ID              uuid.UUID          `json:"id"`
	FirstReviewedAt pgtype.Timestamptz `json:"first_reviewed_at"`
}

// UpdateMergeRequestFirstReviewedAt records the first review activity
// (ADR-0011 §3) at most once: the WHERE guard means a later, later-timed
// call is a no-op rather than clobbering the true first review.
func (q *Queries) UpdateMergeRequestFirstReviewedAt(ctx context.Context, arg UpdateMergeRequestFirstReviewedAtParams) (MergeRequest, error) {
	row := q.db.QueryRow(ctx, updateMergeRequestFirstReviewedAt, arg.ID, arg.FirstReviewedAt)
	var i MergeRequest
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.GitlabMergeRequestID,
		&i.Number,
		&i.Title,
		&i.State,
		&i.IsDraft,
		&i.AuthorGitlabUsername,
		&i.AuthorAvatarUrl,
		&i.BaseBranch,
		&i.HeadBranch,
		&i.Additions,
		&i.Deletions,
		&i.ChangedFiles,
		&i.GitlabCreatedAt,
		&i.GitlabUpdatedAt,
		&i.MergedAt,
		&i.ClosedAt,
		&i.HtmlUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstReviewedAt,
		&i.PipelineStatus,
		&i.PipelineID,
		&i.PipelineUpdatedAt,
		&i.TaskID,
	)
	return i, err
}

const updateMergeRequestPipeline = `-- name: UpdateMergeRequestPipeline :one

UPDATE merge_requests
SET pipeline_status = $2,
    pipeline_id = $3,
    pipeline_updated_at = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, repository_id, gitlab_merge_request_id, number, title, state, is_draft, author_gitlab_username, author_avatar_url, base_branch, head_branch, additions, deletions, changed_files, gitlab_created_at, gitlab_updated_at, merged_at, closed_at, html_url, created_at, updated_at, first_reviewed_at, pipeline_status, pipeline_id, pipeline_updated_at, task_id
`

type UpdateMergeRequestPipelineParams struct {
	ID                uuid.UUID          `json:"id"`
	PipelineStatus    string             `json:"pipeline_status"`
	PipelineID        pgtype.Int8        `json:"pipeline_id"`
	PipelineUpdatedAt pgtype.Timestamptz `json:"pipeline_updated_at"`
}

// UpdateMergeRequestPipeline applies a "Pipeline Hook" delivery's status to
// the merge request it belongs to (internal/webhookapply), narrower than
// UpdateMergeRequest since a pipeline event carries no MR fields at all.
func (q *Queries) UpdateMergeRequestPipeline(ctx context.Context, arg UpdateMergeRequestPipelineParams) (MergeRequest, error) {
	row := q.db.QueryRow(ctx, updateMergeRequestPipeline,
		arg.ID,
		arg.PipelineStatus,
		arg.PipelineID,
		arg.PipelineUpdatedAt,
	)
	var i MergeRequest
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.GitlabMergeRequestID,
		&i.Number,
		&i.Title,
		&i.State,
		&i.IsDraft,
		&i.AuthorGitlabUsername,
		&i.AuthorAvatarUrl,
		&i.BaseBranch,
		&i.HeadBranch,
		&i.Additions,
		&i.Deletions,
		&i.ChangedFiles,
		&i.GitlabCreatedAt,
		&i.GitlabUpdatedAt,
		&i.MergedAt,
		&i.ClosedAt,
		&i.HtmlUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstReviewedAt,
		&i.PipelineStatus,
		&i.PipelineID,
		&i.PipelineUpdatedAt,
		&i.TaskID,
	)
	return i, err
}

const updateMergeRequestTaskID = `-- name: UpdateMergeRequestTaskID :one

UPDATE merge_requests
SET task_id = $2
WHERE id = $1
RETURNING id, repository_id, gitlab_merge_request_id, number, title, state, is_draft, author_gitlab_username, author_avatar_url, base_branch, head_branch, additions, deletions, changed_files, gitlab_created_at, gitlab_updated_at, merged_at, closed_at, html_url, created_at, updated_at, first_reviewed_at, pipeline_status, pipeline_id, pipeline_updated_at, task_id
`

type UpdateMergeRequestTaskIDParams struct {
	ID     uuid.UUID   `json:"id"`
	TaskID pgtype.UUID `json:"task_id"`
}

// UpdateMergeRequestTaskID links a merge request to the task its
// description/branch name references (resolved through task_gitlab_links).
func (q *Queries) UpdateMergeRequestTaskID(ctx context.Context, arg UpdateMergeRequestTaskIDParams) (MergeRequest, error) {
	row := q.db.QueryRow(ctx, updateMergeRequestTaskID, arg.ID, arg.TaskID)
	var i MergeRequest
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.GitlabMergeRequestID,
		&i.Number,
		&i.Title,
		&i.State,
		&i.IsDraft,
		&i.AuthorGitlabUsername,
		&i.AuthorAvatarUrl,
		&i.BaseBranch,
		&i.HeadBranch,
		&i.Additions,
		&i.Deletions,
		&i.ChangedFiles,
		&i.GitlabCreatedAt,
		&i.GitlabUpdatedAt,
		&i.MergedAt,
		&i.ClosedAt,
		&i.HtmlUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstReviewedAt,
		&i.PipelineStatus,
		&i.PipelineID,
		&i.PipelineUpdatedAt,
		&i.TaskID,
	)
	return i, err
}
