// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: merge_requests.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMergeRequest = `-- name: CreateMergeRequest :one

INSERT INTO merge_requests (
    repository_id, gitlab_merge_request_id, number, title, state, is_draft,
    author_gitlab_username, author_avatar_url, base_branch, head_branch,
    gitlab_created_at, gitlab_updated_at, merged_at, closed_at, html_url,
    pipeline_status, pipeline_id, pipeline_updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18
)
RETURNING id, repository_id, gitlab_merge_request_id, number, title, state, is_draft, author_gitlab_username, author_avatar_url, base_branch, head_branch, additions, deletions, changed_files, gitlab_created_at, gitlab_updated_at, merged_at, closed_at, html_url, created_at, updated_at, first_reviewed_at, pipeline_status, pipeline_id, pipeline_updated_at, task_id
`

type CreateMergeRequestParams struct {
	RepositoryID         uuid.UUID          `json:"repository_id"`
	GitlabMergeRequestID int64              `json:"gitlab_merge_request_id"`
	Number               int32              `json:"number"`
	Title                string             `json:"title"`
	State                string             `json:"state"`
	IsDraft              bool               `json:"is_draft"`
	AuthorGitlabUsername string             `json:"author_gitlab_username"`
	AuthorAvatarUrl      string             `json:"author_avatar_url"`
	BaseBranch           string             `json:"base_branch"`
	HeadBranch           string             `json:"head_branch"`
	GitlabCreatedAt      pgtype.Timestamptz `json:"gitlab_created_at"`
	GitlabUpdatedAt      pgtype.Timestamptz `json:"gitlab_updated_at"`
	MergedAt             pgtype.Timestamptz `json:"merged_at"`
	ClosedAt             pgtype.Timestamptz `json:"closed_at"`
	HtmlUrl              string             `json:"html_url"`
	PipelineStatus       string             `json:"pipeline_status"`
	PipelineID           pgtype.Int8        `json:"pipeline_id"`
	PipelineUpdatedAt    pgtype.Timestamptz `json:"pipeline_updated_at"`
}

// merge_requests mirrors a repository's GitLab merge requests, read-only
// (issue #111: FlowLens never writes back to GitLab). Idempotency comes
// from the UNIQUE constraint on gitlab_merge_request_id, the same shape as
// task_gitlab_links' issue-iid uniqueness.
func (q *Queries) CreateMergeRequest(ctx context.Context, arg CreateMergeRequestParams) (MergeRequest, error) {
	row := q.db.QueryRow(ctx, createMergeRequest,
		arg.RepositoryID,
		arg.GitlabMergeRequestID,
		arg.Number,
		arg.Title,
		arg.State,
		arg.IsDraft,
		arg.AuthorGitlabUsername,
		arg.AuthorAvatarUrl,
		arg.BaseBranch,
		arg.HeadBranch,
		arg.GitlabCreatedAt,
		arg.GitlabUpdatedAt,
		arg.MergedAt,
		arg.ClosedAt,
		arg.HtmlUrl,
		arg.PipelineStatus,
		arg.PipelineID,
		arg.PipelineUpdatedAt,
	)
	var i MergeRequest
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.GitlabMergeRequestID,
		&i.Number,
		&i.Title,
		&i.State,
		&i.IsDraft,
		&i.AuthorGitlabUsername,
		&i.AuthorAvatarUrl,
		&i.BaseBranch,
		&i.HeadBranch,
		&i.Additions,
		&i.Deletions,
		&i.ChangedFiles,
		&i.GitlabCreatedAt,
		&i.GitlabUpdatedAt,
		&i.MergedAt,
		&i.ClosedAt,
		&i.HtmlUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstReviewedAt,
		&i.PipelineStatus,
		&i.PipelineID,
		&i.PipelineUpdatedAt,
		&i.TaskID,
	)
	return i, err
}

const getMergeRequestByGitlabMergeRequestID = `-- name: GetMergeRequestByGitlabMergeRequestID :one
SELECT id, repository_id, gitlab_merge_request_id, number, title, state, is_draft, author_gitlab_username, author_avatar_url, base_branch, head_branch, additions, deletions, changed_files, gitlab_created_at, gitlab_updated_at, merged_at, closed_at, html_url, created_at, updated_at, first_reviewed_at, pipeline_status, pipeline_id, pipeline_updated_at, task_id FROM merge_requests WHERE gitlab_merge_request_id = $1
`

func (q *Queries) GetMergeRequestByGitlabMergeRequestID(ctx context.Context, gitlabMergeRequestID int64) (MergeRequest, error) {
	row := q.db.QueryRow(ctx, getMergeRequestByGitlabMergeRequestID, gitlabMergeRequestID)
	var i MergeRequest
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.GitlabMergeRequestID,
		&i.Number,
		&i.Title,
		&i.State,
		&i.IsDraft,
		&i.AuthorGitlabUsername,
		&i.AuthorAvatarUrl,
		&i.BaseBranch,
		&i.HeadBranch,
		&i.Additions,
		&i.Deletions,
		&i.ChangedFiles,
		&i.GitlabCreatedAt,
		&i.GitlabUpdatedAt,
		&i.MergedAt,
		&i.ClosedAt,
		&i.HtmlUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstReviewedAt,
		&i.PipelineStatus,
		&i.PipelineID,
		&i.PipelineUpdatedAt,
		&i.TaskID,
	)
	return i, err
}

const getMergeRequestByRepositoryAndNumber = `-- name: GetMergeRequestByRepositoryAndNumber :one

SELECT id, repository_id, gitlab_merge_request_id, number, title, state, is_draft, author_gitlab_username, author_avatar_url, base_branch, head_branch, additions, deletions, changed_files, gitlab_created_at, gitlab_updated_at, merged_at, closed_at, html_url, created_at, updated_at, first_reviewed_at, pipeline_status, pipeline_id, pipeline_updated_at, task_id FROM merge_requests WHERE repository_id = $1 AND number = $2
`

type GetMergeRequestByRepositoryAndNumberParams struct {
	RepositoryID uuid.UUID `json:"repository_id"`
	Number       int32     `json:"number"`
}

// GetMergeRequestByRepositoryAndNumber looks up a merge request by its
// project-scoped IID (the "number" column) rather than its global GitLab
// id — the key a "Pipeline Hook" delivery's merge_request.iid gives
// (internal/webhookapply), unlike an MR event's own object_attributes.id.
func (q *Queries) GetMergeRequestByRepositoryAndNumber(ctx context.Context, arg GetMergeRequestByRepositoryAndNumberParams) (MergeRequest, error) {
	row := q.db.QueryRow(ctx, getMergeRequestByRepositoryAndNumber, arg.RepositoryID, arg.Number)
	var i MergeRequest
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.GitlabMergeRequestID,
		&i.Number,
		&i.Title,
		&i.State,
		&i.IsDraft,
		&i.AuthorGitlabUsername,
		&i.AuthorAvatarUrl,
		&i.BaseBranch,
		&i.HeadBranch,
		&i.Additions,
		&i.Deletions,
		&i.ChangedFiles,
		&i.GitlabCreatedAt,
		&i.GitlabUpdatedAt,
		&i.MergedAt,
		&i.ClosedAt,
		&i.HtmlUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstReviewedAt,
		&i.PipelineStatus,
		&i.PipelineID,
		&i.PipelineUpdatedAt,
		&i.TaskID,
	)
	return i, err
}

const updateMergeRequest = `-- name: UpdateMergeRequest :one

UPDATE merge_requests
SET title = $2,
    state = $3,
    is_draft = $4,
    author_gitlab_username = $5,
    author_avatar_url = $6,
    base_branch = $7,
    head_branch = $8,
    gitlab_updated_at = $9,
    merged_at = $10,
    closed_at = $11,
    html_url = $12,
    pipeline_status = $13,
    pipeline_id = $14,
    pipeline_updated_at = $15,
    updated_at = now()
WHERE gitlab_merge_request_id = $1
RETURNING id, repository_id, gitlab_merge_request_id, number, title, state, is_draft, author_gitlab_username, author_avatar_url, base_branch, head_branch, additions, deletions, changed_files, gitlab_created_at, gitlab_updated_at, merged_at, closed_at, html_url, created_at, updated_at, first_reviewed_at, pipeline_status, pipeline_id, pipeline_updated_at, task_id
`

type UpdateMergeRequestParams struct {
	GitlabMergeRequestID int64              `json:"gitlab_merge_request_id"`
	Title                string             `json:"title"`
	State                string             `json:"state"`
	IsDraft              bool               `json:"is_draft"`
	AuthorGitlabUsername string             `json:"author_gitlab_username"`
	AuthorAvatarUrl      string             `json:"author_avatar_url"`
	BaseBranch           string             `json:"base_branch"`
	HeadBranch           string             `json:"head_branch"`
	GitlabUpdatedAt      pgtype.Timestamptz `json:"gitlab_updated_at"`
	MergedAt             pgtype.Timestamptz `json:"merged_at"`
	ClosedAt             pgtype.Timestamptz `json:"closed_at"`
	HtmlUrl              string             `json:"html_url"`
	PipelineStatus       string             `json:"pipeline_status"`
	PipelineID           pgtype.Int8        `json:"pipeline_id"`
	PipelineUpdatedAt    pgtype.Timestamptz `json:"pipeline_updated_at"`
}

// UpdateMergeRequest applies the latest GitLab-sourced fields to an
// already-imported merge request. first_reviewed_at and task_id are
// intentionally not touched here — see UpdateMergeRequestFirstReviewedAt
// and UpdateMergeRequestTaskID, which set them at most once each.
func (q *Queries) UpdateMergeRequest(ctx context.Context, arg UpdateMergeRequestParams) (MergeRequest, error) {
	row := q.db.QueryRow(ctx, updateMergeRequest,
		arg.GitlabMergeRequestID,
		arg.Title,
		arg.State,
		arg.IsDraft,
		arg.AuthorGitlabUsername,
		arg.AuthorAvatarUrl,
		arg.BaseBranch,
		arg.HeadBranch,
		arg.GitlabUpdatedAt,
		arg.MergedAt,
		arg.ClosedAt,
		arg.HtmlUrl,
		arg.PipelineStatus,
		arg.PipelineID,
		arg.PipelineUpdatedAt,
	)
	var i MergeRequest
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.GitlabMergeRequestID,
		&i.Number,
		&i.Title,
		&i.State,
		&i.IsDraft,
		&i.AuthorGitlabUsername,
		&i.AuthorAvatarUrl,
		&i.BaseBranch,
		&i.HeadBranch,
		&i.Additions,
		&i.Deletions,
		&i.ChangedFiles,
		&i.GitlabCreatedAt,
		&i.GitlabUpdatedAt,
		&i.MergedAt,
		&i.ClosedAt,
		&i.HtmlUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstReviewedAt,
		&i.PipelineStatus,
		&i.PipelineID,
		&i.PipelineUpdatedAt,
		&i.TaskID,
	)
	return i, err
}

const updateMergeRequestFirstReviewedAt = `-- name: UpdateMergeRequestFirstReviewedAt :one

UPDATE merge_requests
SET first_reviewed_at = $2
WHERE id = $1 AND first_reviewed_at IS NULL
RETURNING id, repository_id, gitlab_merge_request_id, number, title, state, is_draft, author_gitlab_username, author_avatar_url, base_branch, head_branch, additions, deletions, changed_files, gitlab_created_at, gitlab_updated_at, merged_at, closed_at, html_url, created_at, updated_at, first_reviewed_at, pipeline_status, pipeline_id, pipeline_updated_at, task_id
`

type UpdateMergeRequestFirstReviewedAtParams struct {
	ID              uuid.UUID          `json:"id"`
	FirstReviewedAt pgtype.Timestamptz `json:"first_reviewed_at"`
}

// UpdateMergeRequestFirstReviewedAt records the first review activity
// (ADR-0011 §3) at most once: the WHERE guard means a later, later-timed
// call is a no-op rather than clobbering the true first review.
func (q *Queries) UpdateMergeRequestFirstReviewedAt(ctx context.Context, arg UpdateMergeRequestFirstReviewedAtParams) (MergeRequest, error) {
	row := q.db.QueryRow(ctx, updateMergeRequestFirstReviewedAt, arg.ID, arg.FirstReviewedAt)
	var i MergeRequest
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.GitlabMergeRequestID,
		&i.Number,
		&i.Title,
		&i.State,
		&i.IsDraft,
		&i.AuthorGitlabUsername,
		&i.AuthorAvatarUrl,
		&i.BaseBranch,
		&i.HeadBranch,
		&i.Additions,
		&i.Deletions,
		&i.ChangedFiles,
		&i.GitlabCreatedAt,
		&i.GitlabUpdatedAt,
		&i.MergedAt,
		&i.ClosedAt,
		&i.HtmlUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstReviewedAt,
		&i.PipelineStatus,
		&i.PipelineID,
		&i.PipelineUpdatedAt,
		&i.TaskID,
	)
	return i, err
}

const updateMergeRequestPipeline = `-- name: UpdateMergeRequestPipeline :one

UPDATE merge_requests
SET pipeline_status = $2,
    pipeline_id = $3,
    pipeline_updated_at = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, repository_id, gitlab_merge_request_id, number, title, state, is_draft, author_gitlab_username, author_avatar_url, base_branch, head_branch, additions, deletions, changed_files, gitlab_created_at, gitlab_updated_at, merged_at, closed_at, html_url, created_at, updated_at, first_reviewed_at, pipeline_status, pipeline_id, pipeline_updated_at, task_id
`

type UpdateMergeRequestPipelineParams struct {
	ID                uuid.UUID          `json:"id"`
	PipelineStatus    string             `json:"pipeline_status"`
	PipelineID        pgtype.Int8        `json:"pipeline_id"`
	PipelineUpdatedAt pgtype.Timestamptz `json:"pipeline_updated_at"`
}

// UpdateMergeRequestPipeline applies a "Pipeline Hook" delivery's status to
// the merge request it belongs to (internal/webhookapply), narrower than
// UpdateMergeRequest since a pipeline event carries no MR fields at all.
func (q *Queries) UpdateMergeRequestPipeline(ctx context.Context, arg UpdateMergeRequestPipelineParams) (MergeRequest, error) {
	row := q.db.QueryRow(ctx, updateMergeRequestPipeline,
		arg.ID,
		arg.PipelineStatus,
		arg.PipelineID,
		arg.PipelineUpdatedAt,
	)
	var i MergeRequest
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.GitlabMergeRequestID,
		&i.Number,
		&i.Title,
		&i.State,
		&i.IsDraft,
		&i.AuthorGitlabUsername,
		&i.AuthorAvatarUrl,
		&i.BaseBranch,
		&i.HeadBranch,
		&i.Additions,
		&i.Deletions,
		&i.ChangedFiles,
		&i.GitlabCreatedAt,
		&i.GitlabUpdatedAt,
		&i.MergedAt,
		&i.ClosedAt,
		&i.HtmlUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstReviewedAt,
		&i.PipelineStatus,
		&i.PipelineID,
		&i.PipelineUpdatedAt,
		&i.TaskID,
	)
	return i, err
}

const updateMergeRequestTaskID = `-- name: UpdateMergeRequestTaskID :one

UPDATE merge_requests
SET task_id = $2
WHERE id = $1
RETURNING id, repository_id, gitlab_merge_request_id, number, title, state, is_draft, author_gitlab_username, author_avatar_url, base_branch, head_branch, additions, deletions, changed_files, gitlab_created_at, gitlab_updated_at, merged_at, closed_at, html_url, created_at, updated_at, first_reviewed_at, pipeline_status, pipeline_id, pipeline_updated_at, task_id
`

type UpdateMergeRequestTaskIDParams struct {
	ID     uuid.UUID   `json:"id"`
	TaskID pgtype.UUID `json:"task_id"`
}

// UpdateMergeRequestTaskID links a merge request to the task its
// description/branch name references (resolved through task_gitlab_links).
func (q *Queries) UpdateMergeRequestTaskID(ctx context.Context, arg UpdateMergeRequestTaskIDParams) (MergeRequest, error) {
	row := q.db.QueryRow(ctx, updateMergeRequestTaskID, arg.ID, arg.TaskID)
	var i MergeRequest
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.GitlabMergeRequestID,
		&i.Number,
		&i.Title,
		&i.State,
		&i.IsDraft,
		&i.AuthorGitlabUsername,
		&i.AuthorAvatarUrl,
		&i.BaseBranch,
		&i.HeadBranch,
		&i.Additions,
		&i.Deletions,
		&i.ChangedFiles,
		&i.GitlabCreatedAt,
		&i.GitlabUpdatedAt,
		&i.MergedAt,
		&i.ClosedAt,
		&i.HtmlUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstReviewedAt,
		&i.PipelineStatus,
		&i.PipelineID,
		&i.PipelineUpdatedAt,
		&i.TaskID,
	)
	return i, err
}
