// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Organization struct {
	ID            pgtype.UUID        `json:"id"`
	GitlabGroupID int64              `json:"gitlab_group_id"`
	Login         string             `json:"login"`
	DisplayName   string             `json:"display_name"`
	AvatarUrl     string             `json:"avatar_url"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type OrganizationMember struct {
	OrganizationID pgtype.UUID        `json:"organization_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Role           string             `json:"role"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type PullRequest struct {
	ID                   pgtype.UUID        `json:"id"`
	RepositoryID         pgtype.UUID        `json:"repository_id"`
	GitlabMergeRequestID int64              `json:"gitlab_merge_request_id"`
	Number               int32              `json:"number"`
	Title                string             `json:"title"`
	State                string             `json:"state"`
	IsDraft              bool               `json:"is_draft"`
	AuthorGitlabUsername string             `json:"author_gitlab_username"`
	AuthorAvatarUrl      string             `json:"author_avatar_url"`
	BaseBranch           string             `json:"base_branch"`
	HeadBranch           string             `json:"head_branch"`
	Additions            int32              `json:"additions"`
	Deletions            int32              `json:"deletions"`
	ChangedFiles         int32              `json:"changed_files"`
	GitlabCreatedAt      pgtype.Timestamptz `json:"gitlab_created_at"`
	GitlabUpdatedAt      pgtype.Timestamptz `json:"gitlab_updated_at"`
	MergedAt             pgtype.Timestamptz `json:"merged_at"`
	ClosedAt             pgtype.Timestamptz `json:"closed_at"`
	HtmlUrl              string             `json:"html_url"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type PullRequestReviewer struct {
	PullRequestID  pgtype.UUID        `json:"pull_request_id"`
	GitlabUsername string             `json:"gitlab_username"`
	AvatarUrl      string             `json:"avatar_url"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Repository struct {
	ID              pgtype.UUID        `json:"id"`
	OrganizationID  pgtype.UUID        `json:"organization_id"`
	GitlabProjectID int64              `json:"gitlab_project_id"`
	Name            string             `json:"name"`
	FullName        string             `json:"full_name"`
	Description     string             `json:"description"`
	IsPrivate       bool               `json:"is_private"`
	DefaultBranch   string             `json:"default_branch"`
	HtmlUrl         string             `json:"html_url"`
	IsActive        bool               `json:"is_active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SyncRun struct {
	ID           pgtype.UUID        `json:"id"`
	RepositoryID pgtype.UUID        `json:"repository_id"`
	Status       string             `json:"status"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	ErrorMessage string             `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	DisplayName  string             `json:"display_name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
}
