// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getNotificationSettingsForOwner = `-- name: GetNotificationSettingsForOwner :one
SELECT ns.project_id, ns.webhook_url, ns.enabled, ns.send_hour, ns.created_at, ns.updated_at
FROM notification_settings ns
WHERE ns.project_id = $1
  AND EXISTS (
    SELECT 1 FROM project_members pm
    WHERE pm.project_id = ns.project_id AND pm.user_id = $2 AND pm.role = 'owner'
  )
`

type GetNotificationSettingsForOwnerParams struct {
	ProjectID   uuid.UUID `json:"project_id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) GetNotificationSettingsForOwner(ctx context.Context, arg GetNotificationSettingsForOwnerParams) (NotificationSetting, error) {
	row := q.db.QueryRow(ctx, getNotificationSettingsForOwner, arg.ProjectID, arg.OwnerUserID)
	var i NotificationSetting
	err := row.Scan(
		&i.ProjectID,
		&i.WebhookUrl,
		&i.Enabled,
		&i.SendHour,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertNotificationDigestLog = `-- name: InsertNotificationDigestLog :one

INSERT INTO notification_digests (project_id, digest_date, status, error)
VALUES ($1, $2, $3, $4)
ON CONFLICT (project_id, digest_date) DO NOTHING
RETURNING id, project_id, digest_date, status, error, sent_at
`

type InsertNotificationDigestLogParams struct {
	ProjectID  uuid.UUID   `json:"project_id"`
	DigestDate pgtype.Date `json:"digest_date"`
	Status     string      `json:"status"`
	Error      string      `json:"error"`
}

// InsertNotificationDigestLog is the dedupe guard itself: the worker calls
// this *before* building or sending a digest, so a second attempt for the
// same project on the same day (a slow first attempt still in flight, or a
// second process) hits the notification_digests unique constraint and
// reports pgx.ErrNoRows instead of a duplicate send.
func (q *Queries) InsertNotificationDigestLog(ctx context.Context, arg InsertNotificationDigestLogParams) (NotificationDigest, error) {
	row := q.db.QueryRow(ctx, insertNotificationDigestLog,
		arg.ProjectID,
		arg.DigestDate,
		arg.Status,
		arg.Error,
	)
	var i NotificationDigest
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DigestDate,
		&i.Status,
		&i.Error,
		&i.SentAt,
	)
	return i, err
}

const listEnabledNotificationSettings = `-- name: ListEnabledNotificationSettings :many

SELECT project_id, webhook_url, enabled, send_hour, created_at, updated_at FROM notification_settings WHERE enabled = true
`

// ListEnabledNotificationSettings backs the digest worker's sweep: every
// project with notifications turned on, regardless of caller, since the
// worker runs outside any request.
func (q *Queries) ListEnabledNotificationSettings(ctx context.Context) ([]NotificationSetting, error) {
	rows, err := q.db.Query(ctx, listEnabledNotificationSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationSetting{}
	for rows.Next() {
		var i NotificationSetting
		if err := rows.Scan(
			&i.ProjectID,
			&i.WebhookUrl,
			&i.Enabled,
			&i.SendHour,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFailedSyncJobsByProject = `-- name: ListFailedSyncJobsByProject :many
SELECT id, project_id, task_id, kind, payload, dedupe_key, status, attempts, run_after, last_error, created_at, updated_at FROM sync_jobs
WHERE project_id = $1 AND status = 'failed'
ORDER BY updated_at DESC
`

func (q *Queries) ListFailedSyncJobsByProject(ctx context.Context, projectID uuid.UUID) ([]SyncJob, error) {
	rows, err := q.db.Query(ctx, listFailedSyncJobsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncJob{}
	for rows.Next() {
		var i SyncJob
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TaskID,
			&i.Kind,
			&i.Payload,
			&i.DedupeKey,
			&i.Status,
			&i.Attempts,
			&i.RunAfter,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFailedWebhookEventsByProject = `-- name: ListFailedWebhookEventsByProject :many
SELECT we.id, we.linked_gitlab_project_id, we.delivery_uuid, we.event_name, we.object_kind, we.gitlab_issue_iid, we.payload, we.gitlab_updated_at, we.status, we.skip_reason, we.error_message, we.received_at, we.processed_at
FROM webhook_events we
JOIN linked_gitlab_projects lgp ON lgp.id = we.linked_gitlab_project_id
JOIN gitlab_connections gc ON gc.id = lgp.gitlab_connection_id
WHERE gc.project_id = $1 AND we.status = 'failed'
ORDER BY we.received_at DESC
`

func (q *Queries) ListFailedWebhookEventsByProject(ctx context.Context, projectID uuid.UUID) ([]WebhookEvent, error) {
	rows, err := q.db.Query(ctx, listFailedWebhookEventsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEvent{}
	for rows.Next() {
		var i WebhookEvent
		if err := rows.Scan(
			&i.ID,
			&i.LinkedGitlabProjectID,
			&i.DeliveryUuid,
			&i.EventName,
			&i.ObjectKind,
			&i.GitlabIssueIid,
			&i.Payload,
			&i.GitlabUpdatedAt,
			&i.Status,
			&i.SkipReason,
			&i.ErrorMessage,
			&i.ReceivedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverdueOpenTasksByProject = `-- name: ListOverdueOpenTasksByProject :many

SELECT id, project_id, backlog_id, title, description, status, closed_at, assignee_gitlab_user_id, assignee_gitlab_username, labels, due_on, position, created_by_user_id, created_at, updated_at, start_date, priority, progress, search_vector, design_started_at, implementation_started_at FROM tasks
WHERE project_id = $1 AND status = 'open' AND due_on IS NOT NULL AND due_on < $2::date
ORDER BY due_on ASC
`

type ListOverdueOpenTasksByProjectParams struct {
	ProjectID uuid.UUID   `json:"project_id"`
	Today     pgtype.Date `json:"today"`
}

// ListOverdueOpenTasksByProject / ListTasksDueSoonByProject back the digest
// content (issue #109's (a)/(b)). due_on is a DATE (no time-of-day), so
// "due within 24h" is approximated as "due today" — the finest-grained
// distinction the column supports.
func (q *Queries) ListOverdueOpenTasksByProject(ctx context.Context, arg ListOverdueOpenTasksByProjectParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listOverdueOpenTasksByProject, arg.ProjectID, arg.Today)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.BacklogID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.ClosedAt,
			&i.AssigneeGitlabUserID,
			&i.AssigneeGitlabUsername,
			&i.Labels,
			&i.DueOn,
			&i.Position,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartDate,
			&i.Priority,
			&i.Progress,
			&i.SearchVector,
			&i.DesignStartedAt,
			&i.ImplementationStartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksDueSoonByProject = `-- name: ListTasksDueSoonByProject :many
SELECT id, project_id, backlog_id, title, description, status, closed_at, assignee_gitlab_user_id, assignee_gitlab_username, labels, due_on, position, created_by_user_id, created_at, updated_at, start_date, priority, progress, search_vector, design_started_at, implementation_started_at FROM tasks
WHERE project_id = $1 AND status = 'open' AND due_on = $2::date
ORDER BY due_on ASC
`

type ListTasksDueSoonByProjectParams struct {
	ProjectID uuid.UUID   `json:"project_id"`
	Today     pgtype.Date `json:"today"`
}

func (q *Queries) ListTasksDueSoonByProject(ctx context.Context, arg ListTasksDueSoonByProjectParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksDueSoonByProject, arg.ProjectID, arg.Today)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.BacklogID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.ClosedAt,
			&i.AssigneeGitlabUserID,
			&i.AssigneeGitlabUsername,
			&i.Labels,
			&i.DueOn,
			&i.Position,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartDate,
			&i.Priority,
			&i.Progress,
			&i.SearchVector,
			&i.DesignStartedAt,
			&i.ImplementationStartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationDigestFailed = `-- name: MarkNotificationDigestFailed :exec
UPDATE notification_digests
SET status = 'failed', error = $2
WHERE id = $1
`

type MarkNotificationDigestFailedParams struct {
	ID    uuid.UUID `json:"id"`
	Error string    `json:"error"`
}

func (q *Queries) MarkNotificationDigestFailed(ctx context.Context, arg MarkNotificationDigestFailedParams) error {
	_, err := q.db.Exec(ctx, markNotificationDigestFailed, arg.ID, arg.Error)
	return err
}

const upsertNotificationSettings = `-- name: UpsertNotificationSettings :one

INSERT INTO notification_settings (project_id, webhook_url, enabled, send_hour)
VALUES ($1, $2, $3, $4)
ON CONFLICT (project_id) DO UPDATE
SET webhook_url = EXCLUDED.webhook_url,
    enabled = EXCLUDED.enabled,
    send_hour = EXCLUDED.send_hour,
    updated_at = now()
RETURNING project_id, webhook_url, enabled, send_hour, created_at, updated_at
`

type UpsertNotificationSettingsParams struct {
	ProjectID  uuid.UUID `json:"project_id"`
	WebhookUrl string    `json:"webhook_url"`
	Enabled    bool      `json:"enabled"`
	SendHour   int32     `json:"send_hour"`
}

// Daily digest notifications (issue #109). notification_settings has no
// owner column of its own; the owner-scoped queries join through
// project_members the same way gitlab_connections does. The digest worker
// itself has no acting user (like sync.Worker), so ListEnabledNotificationSettings
// and the digest-content queries below are unscoped.
func (q *Queries) UpsertNotificationSettings(ctx context.Context, arg UpsertNotificationSettingsParams) (NotificationSetting, error) {
	row := q.db.QueryRow(ctx, upsertNotificationSettings,
		arg.ProjectID,
		arg.WebhookUrl,
		arg.Enabled,
		arg.SendHour,
	)
	var i NotificationSetting
	err := row.Scan(
		&i.ProjectID,
		&i.WebhookUrl,
		&i.Enabled,
		&i.SendHour,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
