// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: progress_sync_settings.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getProgressSyncSettingsForOwner = `-- name: GetProgressSyncSettingsForOwner :one
SELECT pss.project_id, pss.enabled, pss.created_at, pss.updated_at
FROM progress_sync_settings pss
WHERE pss.project_id = $1
  AND EXISTS (
    SELECT 1 FROM project_members pm
    WHERE pm.project_id = pss.project_id AND pm.user_id = $2 AND pm.role = 'owner'
  )
`

type GetProgressSyncSettingsForOwnerParams struct {
	ProjectID   uuid.UUID `json:"project_id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) GetProgressSyncSettingsForOwner(ctx context.Context, arg GetProgressSyncSettingsForOwnerParams) (ProgressSyncSetting, error) {
	row := q.db.QueryRow(ctx, getProgressSyncSettingsForOwner, arg.ProjectID, arg.OwnerUserID)
	var i ProgressSyncSetting
	err := row.Scan(
		&i.ProjectID,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isProgressSyncEnabledForProject = `-- name: IsProgressSyncEnabledForProject :one

SELECT COALESCE((SELECT enabled FROM progress_sync_settings WHERE project_id = $1), false)::bool AS enabled
`

// IsProgressSyncEnabledForProject reports false, not an error, for a
// project that has never saved a row: settings conceptually always exist,
// just possibly unset (default off).
func (q *Queries) IsProgressSyncEnabledForProject(ctx context.Context, projectID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isProgressSyncEnabledForProject, projectID)
	var enabled bool
	err := row.Scan(&enabled)
	return enabled, err
}

const upsertProgressSyncSettings = `-- name: UpsertProgressSyncSettings :one

INSERT INTO progress_sync_settings (project_id, enabled)
VALUES ($1, $2)
ON CONFLICT (project_id) DO UPDATE
SET enabled = EXCLUDED.enabled,
    updated_at = now()
RETURNING project_id, enabled, created_at, updated_at
`

type UpsertProgressSyncSettingsParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Enabled   bool      `json:"enabled"`
}

// Progress sync on issue close settings (issue #202). No owner column of
// its own; the owner-scoped query joins through project_members the same
// way notification_settings does. The sync paths (webhookapply,
// projectsync) have no acting user, so IsProgressSyncEnabledForProject is
// unscoped, like ListEnabledNotificationSettings.
func (q *Queries) UpsertProgressSyncSettings(ctx context.Context, arg UpsertProgressSyncSettingsParams) (ProgressSyncSetting, error) {
	row := q.db.QueryRow(ctx, upsertProgressSyncSettings, arg.ProjectID, arg.Enabled)
	var i ProgressSyncSetting
	err := row.Scan(
		&i.ProjectID,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
