// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_members.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addProjectMember = `-- name: AddProjectMember :one

INSERT INTO project_members (project_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING project_id, user_id, role, created_at
`

type AddProjectMemberParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
}

// These back internal/projectmember, the member invite/list/role-change/
// remove API (issue #100), the first thing to actually write to
// project_members since it was added by
// docs/decisions/0010-why-project-membership.md.
func (q *Queries) AddProjectMember(ctx context.Context, arg AddProjectMemberParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, addProjectMember, arg.ProjectID, arg.UserID, arg.Role)
	var i ProjectMember
	err := row.Scan(
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectMemberRole = `-- name: GetProjectMemberRole :one
SELECT role FROM project_members WHERE project_id = $1 AND user_id = $2
`

type GetProjectMemberRoleParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) GetProjectMemberRole(ctx context.Context, arg GetProjectMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getProjectMemberRole, arg.ProjectID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT project_id, user_id, role, created_at FROM project_members WHERE project_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListProjectMembers(ctx context.Context, projectID uuid.UUID) ([]ProjectMember, error) {
	rows, err := q.db.Query(ctx, listProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectMember{}
	for rows.Next() {
		var i ProjectMember
		if err := rows.Scan(
			&i.ProjectID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectMembersWithUser = `-- name: ListProjectMembersWithUser :many
SELECT pm.project_id, pm.user_id, pm.role, pm.created_at, u.username, u.display_name
FROM project_members pm
JOIN users u ON u.id = pm.user_id
WHERE pm.project_id = $1
ORDER BY pm.created_at ASC
`

type ListProjectMembersWithUserRow struct {
	ProjectID   uuid.UUID          `json:"project_id"`
	UserID      uuid.UUID          `json:"user_id"`
	Role        string             `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Username    string             `json:"username"`
	DisplayName string             `json:"display_name"`
}

// ListProjectMembersWithUser joins in the username/display name the member
// list response needs; email is deliberately left out so the response never
// carries it (issue #100's "avoid user enumeration via email").
func (q *Queries) ListProjectMembersWithUser(ctx context.Context, projectID uuid.UUID) ([]ListProjectMembersWithUserRow, error) {
	rows, err := q.db.Query(ctx, listProjectMembersWithUser, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectMembersWithUserRow{}
	for rows.Next() {
		var i ListProjectMembersWithUserRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.Username,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProjectMember = `-- name: RemoveProjectMember :execrows
DELETE FROM project_members WHERE project_id = $1 AND user_id = $2
`

type RemoveProjectMemberParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveProjectMember(ctx context.Context, arg RemoveProjectMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeProjectMember, arg.ProjectID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const searchProjectMemberCandidates = `-- name: SearchProjectMemberCandidates :many
SELECT DISTINCT u.id, u.username, u.display_name
FROM users u
JOIN project_members pm ON pm.user_id = u.id
WHERE pm.project_id IN (
        SELECT shared.project_id FROM project_members shared
        WHERE shared.user_id = $1
    )
  AND u.id <> $1
  AND u.id NOT IN (
        SELECT existing.user_id FROM project_members existing
        WHERE existing.project_id = $2
    )
  AND (u.username ILIKE $3 OR u.display_name ILIKE $3)
ORDER BY u.username
LIMIT 10
`

type SearchProjectMemberCandidatesParams struct {
	CallerUserID uuid.UUID `json:"caller_user_id"`
	ProjectID    uuid.UUID `json:"project_id"`
	Query        string    `json:"query"`
}

type SearchProjectMemberCandidatesRow struct {
	ID          uuid.UUID `json:"id"`
	Username    string    `json:"username"`
	DisplayName string    `json:"display_name"`
}

// SearchProjectMemberCandidates finds users an owner could invite to a
// project (issue #140): people they already share *some* project with, minus
// themselves and minus the project's existing members. The whole user table
// is deliberately out of reach — a searchable directory of every registered
// account would undo the "no user enumeration" rule the member list follows.
// Email is neither matched nor returned, for the same reason.
// A picker, not a listing: enough rows to choose from, never enough to walk.
func (q *Queries) SearchProjectMemberCandidates(ctx context.Context, arg SearchProjectMemberCandidatesParams) ([]SearchProjectMemberCandidatesRow, error) {
	rows, err := q.db.Query(ctx, searchProjectMemberCandidates, arg.CallerUserID, arg.ProjectID, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchProjectMemberCandidatesRow{}
	for rows.Next() {
		var i SearchProjectMemberCandidatesRow
		if err := rows.Scan(&i.ID, &i.Username, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjectMemberRole = `-- name: UpdateProjectMemberRole :one
UPDATE project_members
SET role = $3
WHERE project_id = $1 AND user_id = $2
RETURNING project_id, user_id, role, created_at
`

type UpdateProjectMemberRoleParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
}

func (q *Queries) UpdateProjectMemberRole(ctx context.Context, arg UpdateProjectMemberRoleParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, updateProjectMemberRole, arg.ProjectID, arg.UserID, arg.Role)
	var i ProjectMember
	err := row.Scan(
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
