// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_api_tokens.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProjectAPIToken = `-- name: CreateProjectAPIToken :one

INSERT INTO project_api_tokens (project_id, name, token_hash, token_prefix, scopes, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, name, token_hash, last_used_at, expires_at, created_at, scopes, token_prefix
`

type CreateProjectAPITokenParams struct {
	ProjectID   uuid.UUID          `json:"project_id"`
	Name        string             `json:"name"`
	TokenHash   string             `json:"token_hash"`
	TokenPrefix pgtype.Text        `json:"token_prefix"`
	Scopes      []string           `json:"scopes"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

// project_api_tokens has no owner column of its own; ownership is always
// checked through the parent project, the same way backlogs, tasks and
// gitlab_connections are. CreateProjectAPIToken/ListProjectAPITokensByProject
// trust the caller to have already verified project ownership (e.g. via
// project.Service.Get), while DeleteProjectAPITokenForOwner joins to projects
// so a foreign token is indistinguishable from a missing one.
func (q *Queries) CreateProjectAPIToken(ctx context.Context, arg CreateProjectAPITokenParams) (ProjectApiToken, error) {
	row := q.db.QueryRow(ctx, createProjectAPIToken,
		arg.ProjectID,
		arg.Name,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.Scopes,
		arg.ExpiresAt,
	)
	var i ProjectApiToken
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.TokenHash,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Scopes,
		&i.TokenPrefix,
	)
	return i, err
}

const deleteProjectAPITokenForOwner = `-- name: DeleteProjectAPITokenForOwner :execrows
DELETE FROM project_api_tokens t
USING projects p
WHERE t.id = $1 AND t.project_id = p.id AND p.owner_user_id = $2
`

type DeleteProjectAPITokenForOwnerParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) DeleteProjectAPITokenForOwner(ctx context.Context, arg DeleteProjectAPITokenForOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProjectAPITokenForOwner, arg.ID, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProjectAPITokenByTokenHash = `-- name: GetProjectAPITokenByTokenHash :one

SELECT t.id, t.project_id, t.name, t.token_hash, t.last_used_at, t.expires_at, t.created_at, t.scopes, t.token_prefix, p.owner_user_id
FROM project_api_tokens t
JOIN projects p ON p.id = t.project_id
WHERE t.token_hash = $1
  AND (t.expires_at IS NULL OR t.expires_at > now())
`

type GetProjectAPITokenByTokenHashRow struct {
	ID          uuid.UUID          `json:"id"`
	ProjectID   uuid.UUID          `json:"project_id"`
	Name        string             `json:"name"`
	TokenHash   string             `json:"token_hash"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Scopes      []string           `json:"scopes"`
	TokenPrefix pgtype.Text        `json:"token_prefix"`
	OwnerUserID uuid.UUID          `json:"owner_user_id"`
}

// GetProjectAPITokenByTokenHash is unscoped and used only by bearer
// authentication (internal/apitoken.Service.Authenticate), which has no
// acting user to scope through and resolves the project from the token
// itself. Like GetUserBySessionToken, it filters out expired rows in SQL. It
// joins projects to also resolve owner_user_id: a bearer request has no
// session, so the project's owner is the only user it can act as (see
// internal/apitoken's Auth type).
func (q *Queries) GetProjectAPITokenByTokenHash(ctx context.Context, tokenHash string) (GetProjectAPITokenByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getProjectAPITokenByTokenHash, tokenHash)
	var i GetProjectAPITokenByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.TokenHash,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Scopes,
		&i.TokenPrefix,
		&i.OwnerUserID,
	)
	return i, err
}

const listProjectAPITokensByProject = `-- name: ListProjectAPITokensByProject :many
SELECT id, project_id, name, token_hash, last_used_at, expires_at, created_at, scopes, token_prefix FROM project_api_tokens WHERE project_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListProjectAPITokensByProject(ctx context.Context, projectID uuid.UUID) ([]ProjectApiToken, error) {
	rows, err := q.db.Query(ctx, listProjectAPITokensByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectApiToken{}
	for rows.Next() {
		var i ProjectApiToken
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.TokenHash,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.Scopes,
			&i.TokenPrefix,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjectAPITokenLastUsedAt = `-- name: UpdateProjectAPITokenLastUsedAt :exec
UPDATE project_api_tokens SET last_used_at = $2 WHERE id = $1
`

type UpdateProjectAPITokenLastUsedAtParams struct {
	ID         uuid.UUID          `json:"id"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

func (q *Queries) UpdateProjectAPITokenLastUsedAt(ctx context.Context, arg UpdateProjectAPITokenLastUsedAtParams) error {
	_, err := q.db.Exec(ctx, updateProjectAPITokenLastUsedAt, arg.ID, arg.LastUsedAt)
	return err
}
