// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_invites.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acceptProjectInvite = `-- name: AcceptProjectInvite :one
UPDATE project_invites
SET accepted_at = now(), accepted_by_user_id = $2
WHERE id = $1 AND accepted_at IS NULL AND expires_at > now()
RETURNING id, project_id, token_hash, token_prefix, role, accepted_at, accepted_by_user_id, expires_at, created_by_user_id, created_at
`

type AcceptProjectInviteParams struct {
	ID               uuid.UUID   `json:"id"`
	AcceptedByUserID pgtype.UUID `json:"accepted_by_user_id"`
}

// AcceptProjectInvite spends an invite, and only if it is still spendable:
// the accepted_at IS NULL guard means two callers racing to accept the same
// invite cannot both win, since the loser's UPDATE matches no row.
func (q *Queries) AcceptProjectInvite(ctx context.Context, arg AcceptProjectInviteParams) (ProjectInvite, error) {
	row := q.db.QueryRow(ctx, acceptProjectInvite, arg.ID, arg.AcceptedByUserID)
	var i ProjectInvite
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Role,
		&i.AcceptedAt,
		&i.AcceptedByUserID,
		&i.ExpiresAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const createProjectInvite = `-- name: CreateProjectInvite :one
INSERT INTO project_invites (
    project_id, token_hash, token_prefix, role, expires_at, created_by_user_id
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, project_id, token_hash, token_prefix, role, accepted_at, accepted_by_user_id, expires_at, created_by_user_id, created_at
`

type CreateProjectInviteParams struct {
	ProjectID       uuid.UUID          `json:"project_id"`
	TokenHash       string             `json:"token_hash"`
	TokenPrefix     string             `json:"token_prefix"`
	Role            string             `json:"role"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	CreatedByUserID pgtype.UUID        `json:"created_by_user_id"`
}

func (q *Queries) CreateProjectInvite(ctx context.Context, arg CreateProjectInviteParams) (ProjectInvite, error) {
	row := q.db.QueryRow(ctx, createProjectInvite,
		arg.ProjectID,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.Role,
		arg.ExpiresAt,
		arg.CreatedByUserID,
	)
	var i ProjectInvite
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Role,
		&i.AcceptedAt,
		&i.AcceptedByUserID,
		&i.ExpiresAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProjectInviteForOwner = `-- name: DeleteProjectInviteForOwner :execrows
DELETE FROM project_invites
WHERE id = $1
  AND project_id IN (
      SELECT project_id FROM project_members
      WHERE user_id = $2 AND role = 'owner'
  )
`

type DeleteProjectInviteForOwnerParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// DeleteProjectInviteForOwner revokes an invite, scoped to a caller holding
// the 'owner' role on its project — the ownership check is in the query, so
// a non-owner deletes nothing and cannot tell the invite apart from a
// missing one. Mirrors DeleteProjectAPITokenForOwner.
func (q *Queries) DeleteProjectInviteForOwner(ctx context.Context, arg DeleteProjectInviteForOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProjectInviteForOwner, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProjectInviteByTokenHash = `-- name: GetProjectInviteByTokenHash :one
SELECT project_invites.id, project_invites.project_id, project_invites.token_hash, project_invites.token_prefix, project_invites.role, project_invites.accepted_at, project_invites.accepted_by_user_id, project_invites.expires_at, project_invites.created_by_user_id, project_invites.created_at, projects.name AS project_name
FROM project_invites
JOIN projects ON projects.id = project_invites.project_id
WHERE project_invites.token_hash = $1
`

type GetProjectInviteByTokenHashRow struct {
	ProjectInvite ProjectInvite `json:"project_invite"`
	ProjectName   string        `json:"project_name"`
}

// GetProjectInviteByTokenHash resolves a raw invite token (hashed by the
// caller) to the invite it names, joined to the project it grants access
// to so the acceptance screen can name it without a second query. It
// deliberately does not filter on expires_at or accepted_at: the caller
// distinguishes "expired" from "already used" from "never existed" for its
// own error, and only the last of those is a not-found.
func (q *Queries) GetProjectInviteByTokenHash(ctx context.Context, tokenHash string) (GetProjectInviteByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getProjectInviteByTokenHash, tokenHash)
	var i GetProjectInviteByTokenHashRow
	err := row.Scan(
		&i.ProjectInvite.ID,
		&i.ProjectInvite.ProjectID,
		&i.ProjectInvite.TokenHash,
		&i.ProjectInvite.TokenPrefix,
		&i.ProjectInvite.Role,
		&i.ProjectInvite.AcceptedAt,
		&i.ProjectInvite.AcceptedByUserID,
		&i.ProjectInvite.ExpiresAt,
		&i.ProjectInvite.CreatedByUserID,
		&i.ProjectInvite.CreatedAt,
		&i.ProjectName,
	)
	return i, err
}

const listProjectInvitesByProject = `-- name: ListProjectInvitesByProject :many
SELECT id, project_id, token_hash, token_prefix, role, accepted_at, accepted_by_user_id, expires_at, created_by_user_id, created_at FROM project_invites
WHERE project_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListProjectInvitesByProject(ctx context.Context, projectID uuid.UUID) ([]ProjectInvite, error) {
	rows, err := q.db.Query(ctx, listProjectInvitesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectInvite{}
	for rows.Next() {
		var i ProjectInvite
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TokenHash,
			&i.TokenPrefix,
			&i.Role,
			&i.AcceptedAt,
			&i.AcceptedByUserID,
			&i.ExpiresAt,
			&i.CreatedByUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
