// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one

INSERT INTO projects (owner_user_id, name, description)
VALUES ($1, $2, $3)
RETURNING id, owner_user_id, name, description, created_at, updated_at
`

type CreateProjectParams struct {
	OwnerUserID uuid.UUID `json:"owner_user_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}

// Every project-scoped query filters on owner_user_id in SQL. Authorization
// is therefore enforced by the query itself: a non-owner gets "no rows",
// which callers map to ErrNotFound. Handlers must never do their own
// ownership check, and later project-scoped tables follow the same rule.
func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.OwnerUserID, arg.Name, arg.Description)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProjectForOwner = `-- name: DeleteProjectForOwner :execrows
DELETE FROM projects WHERE id = $1 AND owner_user_id = $2
`

type DeleteProjectForOwnerParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) DeleteProjectForOwner(ctx context.Context, arg DeleteProjectForOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProjectForOwner, arg.ID, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProjectByID = `-- name: GetProjectByID :one

SELECT id, owner_user_id, name, description, created_at, updated_at FROM projects WHERE id = $1
`

// GetProjectByID is unscoped, for the inbound webhook apply pipeline
// (internal/webhookapply, docs/plans/issue-sync.md "Inbound"), which
// resolves a new unclassified task's created_by_user_id from the project's
// owner and has no acting user of its own to scope through — the same
// reasoning as GetLinkedGitlabProjectByID.
func (q *Queries) GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectForOwner = `-- name: GetProjectForOwner :one
SELECT id, owner_user_id, name, description, created_at, updated_at FROM projects WHERE id = $1 AND owner_user_id = $2
`

type GetProjectForOwnerParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) GetProjectForOwner(ctx context.Context, arg GetProjectForOwnerParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectForOwner, arg.ID, arg.OwnerUserID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFailedSyncProjectsByOwner = `-- name: ListFailedSyncProjectsByOwner :many

SELECT p.id, p.owner_user_id, p.name, p.description, p.created_at, p.updated_at, COUNT(*) AS failed_sync_task_count
FROM projects p
JOIN tasks t ON t.project_id = p.id
LEFT JOIN task_gitlab_links tgl ON tgl.task_id = t.id
WHERE p.owner_user_id = $1
  AND (
    tgl.sync_status = 'failed'
    OR (tgl.task_id IS NULL AND EXISTS (
      SELECT 1 FROM sync_jobs sj WHERE sj.task_id = t.id AND sj.status = 'failed'
    ))
  )
GROUP BY p.id
ORDER BY p.updated_at DESC
`

type ListFailedSyncProjectsByOwnerRow struct {
	ID                  uuid.UUID          `json:"id"`
	OwnerUserID         uuid.UUID          `json:"owner_user_id"`
	Name                string             `json:"name"`
	Description         string             `json:"description"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	FailedSyncTaskCount int64              `json:"failed_sync_task_count"`
}

// ListFailedSyncProjectsByOwner backs the dashboard's "sync failures"
// section (issue #77): every project ownerID owns that has at least one
// task with a failed GitLab sync, counted the same way
// CountFailedSyncTasksByProjectForOwner counts a single project — from
// task_gitlab_links when a link exists, or from the task's most recent
// sync_jobs row otherwise — but joined across every project in one round
// trip instead of one query per project.
func (q *Queries) ListFailedSyncProjectsByOwner(ctx context.Context, ownerUserID uuid.UUID) ([]ListFailedSyncProjectsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listFailedSyncProjectsByOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFailedSyncProjectsByOwnerRow{}
	for rows.Next() {
		var i ListFailedSyncProjectsByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FailedSyncTaskCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByOwner = `-- name: ListProjectsByOwner :many
SELECT id, owner_user_id, name, description, created_at, updated_at FROM projects WHERE owner_user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListProjectsByOwner(ctx context.Context, ownerUserID uuid.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjectForOwner = `-- name: UpdateProjectForOwner :one
UPDATE projects
SET name = $3, description = $4, updated_at = now()
WHERE id = $1 AND owner_user_id = $2
RETURNING id, owner_user_id, name, description, created_at, updated_at
`

type UpdateProjectForOwnerParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}

func (q *Queries) UpdateProjectForOwner(ctx context.Context, arg UpdateProjectForOwnerParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProjectForOwner,
		arg.ID,
		arg.OwnerUserID,
		arg.Name,
		arg.Description,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
