// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createProject = `-- name: CreateProject :one

INSERT INTO projects (owner_user_id, name, description)
VALUES ($1, $2, $3)
RETURNING id, owner_user_id, name, description, created_at, updated_at
`

type CreateProjectParams struct {
	OwnerUserID uuid.UUID `json:"owner_user_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}

// Every project-scoped query filters on owner_user_id in SQL. Authorization
// is therefore enforced by the query itself: a non-owner gets "no rows",
// which callers map to ErrNotFound. Handlers must never do their own
// ownership check, and later project-scoped tables follow the same rule.
func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.OwnerUserID, arg.Name, arg.Description)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProjectForOwner = `-- name: DeleteProjectForOwner :execrows
DELETE FROM projects WHERE id = $1 AND owner_user_id = $2
`

type DeleteProjectForOwnerParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) DeleteProjectForOwner(ctx context.Context, arg DeleteProjectForOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProjectForOwner, arg.ID, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProjectForOwner = `-- name: GetProjectForOwner :one
SELECT id, owner_user_id, name, description, created_at, updated_at FROM projects WHERE id = $1 AND owner_user_id = $2
`

type GetProjectForOwnerParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) GetProjectForOwner(ctx context.Context, arg GetProjectForOwnerParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectForOwner, arg.ID, arg.OwnerUserID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one

SELECT id, owner_user_id, name, description, created_at, updated_at FROM projects WHERE id = $1
`

// GetProjectByID is unscoped, for the inbound webhook apply pipeline
// (internal/webhookapply, docs/plans/issue-sync.md "Inbound"), which
// resolves a new unclassified task's created_by_user_id from the project's
// owner and has no acting user of its own to scope through — the same
// reasoning as GetLinkedGitlabProjectByID.
func (q *Queries) GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectsByOwner = `-- name: ListProjectsByOwner :many
SELECT id, owner_user_id, name, description, created_at, updated_at FROM projects WHERE owner_user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListProjectsByOwner(ctx context.Context, ownerUserID uuid.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjectForOwner = `-- name: UpdateProjectForOwner :one
UPDATE projects
SET name = $3, description = $4, updated_at = now()
WHERE id = $1 AND owner_user_id = $2
RETURNING id, owner_user_id, name, description, created_at, updated_at
`

type UpdateProjectForOwnerParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}

func (q *Queries) UpdateProjectForOwner(ctx context.Context, arg UpdateProjectForOwnerParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProjectForOwner,
		arg.ID,
		arg.OwnerUserID,
		arg.Name,
		arg.Description,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
