// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// These back internal/projectmember, the member invite/list/role-change/
	// remove API (issue #100), the first thing to actually write to
	// project_members since it was added by
	// docs/decisions/0010-why-project-membership.md.
	AddProjectMember(ctx context.Context, arg AddProjectMemberParams) (ProjectMember, error)
	// CountFailedSyncTasksByProjectForOwner backs the project single view's sync
	// warning (docs/plans/issue-sync.md's "gitlab" fields, surfaced per-task by
	// internal/task). A task counts as failed the same way internal/task derives
	// a single task's sync_status: from task_gitlab_links when a link exists, or
	// from its most recent sync_jobs row (necessarily an issue.create, see
	// GetLatestSyncJobForTask) when it doesn't.
	// ApplyWebhookTaskFields is the inbound apply pipeline's write to tasks
	// (internal/webhookapply, docs/plans/issue-sync.md "Inbound"): unscoped, like
	// GetLinkedGitlabProjectByID, because the task_gitlab_links row that names
	// this task ID was already authorized when the link was first created (or,
	// for a brand-new unclassified task, in the same transaction that just
	// created it). It never touches backlog_id, position, priority or progress,
	// which are app-only — in particular an issue being closed on GitLab moves
	// status, never progress (see the 000011 migration).
	// closed_at only advances when status transitions into 'closed' — the CASE
	// reads the pre-update closed_at (every SET expression in one UPDATE sees
	// the same original row), so re-applying while already closed never moves
	// the timestamp, mirroring internal/task.Service.Close's own no-op rule.
	ApplyWebhookTaskFields(ctx context.Context, arg ApplyWebhookTaskFieldsParams) (Task, error)
	AssignTaskBacklogForOwner(ctx context.Context, arg AssignTaskBacklogForOwnerParams) (Task, error)
	// The inbound apply pipeline (internal/webhookapply, docs/plans/issue-sync.md
	// "Inbound"). ClaimNextPendingWebhookEvent must be called through a
	// transaction-scoped Querier (database.TxRunner): FOR UPDATE SKIP LOCKED only
	// holds its lock for the life of the transaction, so the claim and the
	// resulting task write and status update need to commit together — that is
	// what lets a crash mid-apply leave the event 'pending' for a clean retry
	// instead of stuck half-applied. SKIP LOCKED also means two workers polling
	// concurrently never claim the same row. ORDER BY received_at ASC processes
	// deliveries oldest-first, which combined with the stale-event guard means
	// out-of-order redelivery can never apply a newer event before an older one.
	ClaimNextPendingWebhookEvent(ctx context.Context) (WebhookEvent, error)
	ClaimPendingSyncJobs(ctx context.Context, limit int32) ([]SyncJob, error)
	// Unsets is_default on every other link in the same connection as linkID,
	// so SetDefaultLinkedGitlabProjectForOwner can set exactly one.
	ClearDefaultLinkedGitlabProjectsForOwner(ctx context.Context, arg ClearDefaultLinkedGitlabProjectsForOwnerParams) error
	CloseTaskForOwner(ctx context.Context, arg CloseTaskForOwnerParams) (Task, error)
	CompleteGitlabSyncRun(ctx context.Context, arg CompleteGitlabSyncRunParams) (GitlabSyncRun, error)
	CountFailedSyncTasksByProjectForOwner(ctx context.Context, arg CountFailedSyncTasksByProjectForOwnerParams) (int64, error)
	// Backlogs have no owner column of their own; ownership is always checked
	// through the parent project. CreateBacklog/ListBacklogsByProject trust the
	// caller to have already verified project ownership (e.g. via
	// project.Service.Get), while the single-backlog queries join to projects so
	// a foreign backlog is indistinguishable from a missing one.
	CreateBacklog(ctx context.Context, arg CreateBacklogParams) (Backlog, error)
	// gitlab_sync_runs records one project.import / project.resync execution
	// against a linked GitLab project (docs/plans/issue-sync.md's SyncRun
	// object, issue #25). Concurrency is enforced at the database level, not by
	// a check-then-insert race in Go: a partial UNIQUE index on
	// (linked_gitlab_project_id) WHERE completed_at IS NULL (migration 000006)
	// means CreateGitlabSyncRun itself fails with a unique-constraint violation
	// when a run is already in progress for the same link, which
	// internal/projectsync maps to ErrRunInProgress (HTTP 409).
	CreateGitlabSyncRun(ctx context.Context, arg CreateGitlabSyncRunParams) (GitlabSyncRun, error)
	// linked_gitlab_projects has no owner column of its own; ownership is always
	// checked by joining through gitlab_connections to projects, the same way
	// gitlab_connections is checked through projects. A link belonging to
	// another user's project is indistinguishable from a missing one.
	// is_default is computed here, not by the caller: the first project linked
	// to a connection becomes its default, later ones do not.
	CreateLinkedGitlabProject(ctx context.Context, arg CreateLinkedGitlabProjectParams) (LinkedGitlabProject, error)
	// Every project-scoped query filters on project_members in SQL (see
	// docs/decisions/0010-why-project-membership.md and issue #99): access is
	// therefore enforced by the query itself, not by application code. A
	// read query (Get/List) accepts any role; a write query restricts the
	// EXISTS subquery's role IN (...) to the roles that action requires. A
	// caller with no membership row at all gets "no rows", which callers map to
	// ErrNotFound; one with a membership row of too low a role also gets "no
	// rows" from these queries alone — the distinct ErrForbidden comes from
	// project.Service.Authorize (backed by GetProjectMemberRole), not from
	// these list/get/write queries. DeleteProjectForOwner is the one exception:
	// it stays keyed on projects.owner_user_id directly, not project_members,
	// per the ADR's "last owner" reasoning.
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	// project_api_tokens has no owner column of its own; ownership is always
	// checked through the parent project, the same way backlogs, tasks and
	// gitlab_connections are. CreateProjectAPIToken/ListProjectAPITokensByProject
	// trust the caller to have already verified project ownership (e.g. via
	// project.Service.Get), while DeleteProjectAPITokenForOwner joins to projects
	// so a foreign token is indistinguishable from a missing one.
	//
	// GetProjectAPITokenByTokenHash is unscoped and used only by bearer
	// authentication (internal/apitoken.Service.Authenticate), which has no
	// acting user to scope through and resolves the project from the token
	// itself. Like GetUserBySessionToken, it filters out expired rows in SQL. It
	// joins projects to also resolve owner_user_id: a bearer request has no
	// session, so the project's owner is the only user it can act as (see
	// internal/apitoken's Auth type).
	CreateProjectAPIToken(ctx context.Context, arg CreateProjectAPITokenParams) (ProjectApiToken, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// Tasks are scoped through their parent project the same way backlogs are:
	// every single-task query joins to projects and filters on
	// owner_user_id, so a foreign task is indistinguishable from a missing one.
	// CreateTask trusts the caller to have already verified project ownership
	// (e.g. via project.Service.Get), like CreateBacklog.
	//
	// ListTasksByProject takes three independent optional filters so one query
	// serves the unfiltered, single-backlog, unassigned-only and status-scoped
	// list views: passing false/NULL/'' for a filter disables it.
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	// task_dependencies has no project_id/owner column of its own; ownership is
	// always checked through its tasks, the same way task_gitlab_links is never
	// queried through a project/owner join directly. CreateTaskDependency and
	// ListTaskDependenciesByProject trust the caller (internal/taskdependency) to
	// have already verified project ownership and that both tasks belong to the
	// same project, the same way CreateTask trusts an already-verified project.
	// DeleteTaskDependencyForOwner joins through the predecessor task to
	// projects, so a dependency belonging to another user's project is
	// indistinguishable from a missing one.
	CreateTaskDependency(ctx context.Context, arg CreateTaskDependencyParams) (TaskDependency, error)
	// task_gitlab_links has no owner column and is never queried through a
	// project/owner join: only the outbox worker (internal/issuesync) reads and
	// writes it, and the job row that drives it was already authorized when
	// internal/task enqueued it in the same transaction as the task write. See
	// docs/plans/issue-sync.md, "Outbound".
	CreateTaskGitlabLink(ctx context.Context, arg CreateTaskGitlabLinkParams) (TaskGitlabLink, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// webhook_events has no owner column and is never queried through a
	// project/owner join: the linkID in the URL path (POST
	// /webhooks/gitlab/{linkID}) is itself the authorization boundary, verified
	// by comparing X-Gitlab-Token against the link's decrypted webhook secret in
	// constant time before any of these run (see internal/webhookevent,
	// ADR-0008).
	// ON CONFLICT DO NOTHING makes a duplicate GitLab delivery (same
	// linked_gitlab_project_id + delivery_uuid) a no-op instead of an error: the
	// caller sees pgx.ErrNoRows and treats it the same as a fresh insert, so
	// retried/duplicated deliveries are idempotent (docs/plans/issue-sync.md,
	// "Inbound").
	CreateWebhookEvent(ctx context.Context, arg CreateWebhookEventParams) (WebhookEvent, error)
	DeleteBacklogForOwner(ctx context.Context, arg DeleteBacklogForOwnerParams) (int64, error)
	DeleteExpiredSessions(ctx context.Context) error
	DeleteGitlabConnectionForOwner(ctx context.Context, arg DeleteGitlabConnectionForOwnerParams) (int64, error)
	// Returns the deleted row (rather than an affected-row count) so the
	// service can tell whether it removed the default link and needs to
	// promote another one.
	DeleteLinkedGitlabProjectForOwner(ctx context.Context, arg DeleteLinkedGitlabProjectForOwnerParams) (LinkedGitlabProject, error)
	// The retention policy decided for issue #26: only 'processed' rows are
	// pruned. 'failed' and 'skipped' rows are kept indefinitely (their error and
	// skip_reason are the whole point of troubleshooting) and 'pending' rows are
	// never touched by cleanup — the apply worker is the only thing that moves a
	// pending row out of that state.
	DeleteProcessedWebhookEventsOlderThan(ctx context.Context, processedAt pgtype.Timestamptz) (int64, error)
	DeleteProjectAPITokenForOwner(ctx context.Context, arg DeleteProjectAPITokenForOwnerParams) (int64, error)
	// DeleteProjectForOwner deliberately stays keyed on the single
	// owner_user_id column, not a project_members role check: restricting
	// delete to the one designated owner avoids the "last owner deletes, a
	// second owner-role member is left holding a project with no owner" race a
	// membership table alone invites (docs/decisions/0010-why-project-membership.md).
	DeleteProjectForOwner(ctx context.Context, arg DeleteProjectForOwnerParams) (int64, error)
	DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error
	DeleteTaskDependencyForOwner(ctx context.Context, arg DeleteTaskDependencyForOwnerParams) (int64, error)
	DeleteTaskForOwner(ctx context.Context, arg DeleteTaskForOwnerParams) (int64, error)
	// The outbox worker (internal/sync, docs/plans/issue-sync.md "Sync engine").
	//
	// EnqueueSyncJob upserts on dedupe_key: a colliding insert only overwrites the
	// existing row while it is still 'pending' (collapsing rapid repeated edits
	// into one job); a collision with a running/succeeded/failed row leaves that
	// row untouched and returns no rows, so the caller falls back to
	// GetSyncJobByDedupeKey and reuses it as-is. MarkSyncJobSucceeded and
	// MarkSyncJobFailed clear dedupe_key so a later edit is never permanently
	// blocked by a job that already reached a terminal state.
	//
	// ClaimPendingSyncJobs is the SKIP LOCKED claim: it atomically selects and
	// flips due pending jobs to 'running' in one statement, so two workers
	// polling concurrently never claim the same row.
	EnqueueSyncJob(ctx context.Context, arg EnqueueSyncJobParams) (SyncJob, error)
	FailGitlabSyncRun(ctx context.Context, arg FailGitlabSyncRunParams) (GitlabSyncRun, error)
	GetBacklogForOwner(ctx context.Context, arg GetBacklogForOwnerParams) (Backlog, error)
	// GetBacklogProjectID is the lightweight project lookup
	// requireTokenResourceProject (internal/http, issue #66) uses to enforce a
	// bearer token's project boundary on a single-backlog URL, without
	// GetBacklogForOwner's owner join — a token has no session owner to join
	// against.
	GetBacklogProjectID(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	// internal/task uses this at task-create time to decide whether the
	// project has anywhere to push a new issue, and if so, where
	// (docs/plans/issue-sync.md, "Outbound").
	GetDefaultLinkedGitlabProjectForOwner(ctx context.Context, arg GetDefaultLinkedGitlabProjectForOwnerParams) (LinkedGitlabProject, error)
	// Unscoped, for the outbox worker (internal/issuesync): a linked_gitlab_projects
	// row carries gitlab_connection_id but the worker has no acting user to
	// scope through, the same reasoning as GetLinkedGitlabProjectByID.
	GetGitlabConnectionByID(ctx context.Context, id uuid.UUID) (GitlabConnection, error)
	// Same as GetGitlabConnectionForOwner, but keyed by the connection's own ID
	// rather than by its project. internal/linkedproject uses this to dial
	// GitLab (issue #18's webhook registration/repair/delete) starting from a
	// linked_gitlab_projects row, which carries gitlab_connection_id but not the
	// app project ID.
	GetGitlabConnectionByIDForOwner(ctx context.Context, arg GetGitlabConnectionByIDForOwnerParams) (GitlabConnection, error)
	// GetGitlabConnectionForOwner/GetGitlabConnectionByIDForOwner only check
	// membership exists (any role), not a specific role: they back both
	// gitlabconn.Service's own owner-only HTTP-facing methods (Get/Test, via
	// getRow) *and* Dial/DialByConnectionID, which internal/linkedproject calls
	// on behalf of a member performing a member-level linked-project action
	// (Create/RegisterWebhook/...). The role-specific check
	// ("is ownerID actually allowed to do *this*") is enforced once, by the
	// caller: gitlabconn.Service.{Save,Get,Test,Delete} call
	// project.Service.Authorize(..., RoleOwner) themselves before touching the
	// row; internal/linkedproject authorizes its own member-minimum before ever
	// calling Dial/DialByConnectionID. Update/Delete below stay owner-only in
	// SQL directly, since nothing else reuses them.
	GetGitlabConnectionForOwner(ctx context.Context, arg GetGitlabConnectionForOwnerParams) (GitlabConnection, error)
	// Unscoped, like GetLinkedGitlabProjectByID: the background worker
	// (internal/projectsync) reads this with no acting user of its own — the
	// job row that names this run's ID was already authorized when it was
	// created (either automatically at link creation, or by an owner-scoped
	// HTTP request).
	GetGitlabSyncRunByID(ctx context.Context, id uuid.UUID) (GitlabSyncRun, error)
	// GetLatestSyncJobForTask backs a task's sync status (internal/task) when it
	// has no task_gitlab_links row yet — i.e. its issue.create job hasn't
	// succeeded (or has permanently failed), so there is nothing in
	// task_gitlab_links to read sync_status from. Before a link exists, a task
	// can only ever have enqueued issue.create jobs (issue.update/close/reopen
	// all require an existing link), so "latest" is unambiguous.
	GetLatestSyncJobForTask(ctx context.Context, taskID uuid.UUID) (SyncJob, error)
	// Unscoped: the outbox worker (internal/issuesync) has no acting user. The
	// sync_jobs row that names this linked project's ID was already authorized
	// when internal/task enqueued it, so the job's execution needs no further
	// ownership check.
	GetLinkedGitlabProjectByID(ctx context.Context, id uuid.UUID) (LinkedGitlabProject, error)
	GetLinkedGitlabProjectForOwner(ctx context.Context, arg GetLinkedGitlabProjectForOwnerParams) (LinkedGitlabProject, error)
	// The lightweight project lookup requireTokenResourceProject (internal/http,
	// issue #66) uses to enforce a bearer token's project boundary on
	// GET /linked-gitlab-projects/{linkID}/sync-runs, resolved through
	// gitlab_connections the same way linkedProjectOwner (dbtest) does, since a
	// linked project has no project_id column of its own.
	GetLinkedGitlabProjectProjectID(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	// GetPendingSyncJobQueueStats backs the worker's queue-depth gauges (issue
	// #96): how many jobs are waiting, and how long the oldest of them has been
	// waiting, are what turn "the worker looks busy" into "the worker is stuck".
	// oldest_pending_at is NULL (via min() on zero rows) when the queue is
	// empty, which internal/sync reads as "no gauge to report" rather than a
	// bogus zero-age job.
	GetPendingSyncJobQueueStats(ctx context.Context) (GetPendingSyncJobQueueStatsRow, error)
	GetProjectAPITokenByTokenHash(ctx context.Context, tokenHash string) (GetProjectAPITokenByTokenHashRow, error)
	// GetProjectByID is unscoped, for the inbound webhook apply pipeline
	// (internal/webhookapply, docs/plans/issue-sync.md "Inbound"), which
	// resolves a new unclassified task's created_by_user_id from the project's
	// owner and has no acting user of its own to scope through — the same
	// reasoning as GetLinkedGitlabProjectByID.
	GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error)
	GetProjectForOwner(ctx context.Context, arg GetProjectForOwnerParams) (Project, error)
	GetProjectMemberRole(ctx context.Context, arg GetProjectMemberRoleParams) (string, error)
	GetSyncJobByDedupeKey(ctx context.Context, dedupeKey pgtype.Text) (SyncJob, error)
	// GetSyncJobForOwner backs POST /sync-jobs/{jobID}/retry: resolves a job by
	// ID scoped to its project's owner in one round trip, since the URL carries
	// no projectID for this route. Membership only (any role) is checked here —
	// Retry (member-minimum) does its own project.Service.Authorize call first,
	// so it can distinguish ErrForbidden from ErrNotFound.
	GetSyncJobForOwner(ctx context.Context, arg GetSyncJobForOwnerParams) (SyncJob, error)
	GetTaskAIContext(ctx context.Context, taskID uuid.UUID) (TaskAiContext, error)
	// GetTaskDependencyProjectID is the lightweight project lookup
	// requireTokenResourceProject (internal/http, issue #66) uses to enforce a
	// bearer token's project boundary on a single-dependency URL: resolved
	// through the predecessor task, the same way DeleteTaskDependencyForOwner
	// resolves ownership.
	GetTaskDependencyProjectID(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	GetTaskForOwner(ctx context.Context, arg GetTaskForOwnerParams) (Task, error)
	// GetTaskForProject scopes a task by its project directly, not by owner: the
	// AI-facing bearer-token path (docs/plans/issue-sync.md "AI-facing") has no
	// session user, only the project a project.Service-verified token was issued
	// for (internal/apitoken), so there is no owner to join against.
	GetTaskForProject(ctx context.Context, arg GetTaskForProjectParams) (Task, error)
	// GetTaskGitlabLinkByLinkedProjectAndIID looks up a task already linked to a
	// specific GitLab issue, keyed by the same columns as the 1:1 UNIQUE
	// constraint. The inbound apply pipeline (internal/webhookapply,
	// docs/plans/issue-sync.md "Inbound") uses this to tell a known issue
	// (update an existing task) from an unknown one (create a new unclassified
	// task).
	GetTaskGitlabLinkByLinkedProjectAndIID(ctx context.Context, arg GetTaskGitlabLinkByLinkedProjectAndIIDParams) (TaskGitlabLink, error)
	GetTaskGitlabLinkByTaskID(ctx context.Context, taskID uuid.UUID) (TaskGitlabLink, error)
	// GetTaskGitlabLinkWithProjectPathByTaskID is GetTaskGitlabLinkByTaskID plus
	// the linked GitLab project's path_with_namespace, joined in for the
	// AI-facing /context endpoints (docs/plans/issue-sync.md "AI-facing"): an AI
	// agent needs the project path alongside the issue IID/URL to identify the
	// issue without a second call.
	GetTaskGitlabLinkWithProjectPathByTaskID(ctx context.Context, taskID uuid.UUID) (GetTaskGitlabLinkWithProjectPathByTaskIDRow, error)
	// GetTaskProjectID is the lightweight project lookup
	// requireTokenResourceProject (internal/http, issue #66) uses to enforce a
	// bearer token's project boundary on a single-task URL. It has no owner
	// join, unlike GetTaskForOwner: a token has no session owner to join
	// against (apitoken.Auth), only its own project to compare the result
	// against.
	GetTaskProjectID(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserBySessionToken(ctx context.Context, tokenHash string) (GetUserBySessionTokenRow, error)
	GetUserByUsernameOrEmail(ctx context.Context, username string) (User, error)
	// The detail view: unlike the list row, its payload is actually read by the
	// caller (internal/http keeps the list DTO payload-free to avoid exposing
	// raw GitLab payloads by default).
	GetWebhookEventByLinkedGitlabProjectIDAndID(ctx context.Context, arg GetWebhookEventByLinkedGitlabProjectIDAndIDParams) (WebhookEvent, error)
	// ListBacklogsByProject's priority and progress filters and sorts follow the
	// same "empty/false disables it" convention as internal/task's
	// ListTasksByProject. Sorting by priority ranks urgent > high > medium > low;
	// sorting by progress runs the other way, not_started first through done, so
	// the order reads as the work advancing (and matches the Board view's
	// left-to-right axis). Both fall back to the usual position/created_at order
	// as a tiebreak. sort_by_priority and sort_by_progress are mutually exclusive
	// in practice — internal/backlog sets at most one from a single ?sort=.
	ListBacklogsByProject(ctx context.Context, arg ListBacklogsByProjectParams) ([]Backlog, error)
	// ListFailedSyncJobsByProjectForOwner backs GET
	// /projects/{projectID}/sync-jobs?status=failed (issue #97): every
	// permanently-failed sync_jobs row for a project, scoped to ownerID through
	// a join on projects, so an unknown or foreign projectID simply returns no
	// rows rather than needing a separate ownership check first.
	ListFailedSyncJobsByProjectForOwner(ctx context.Context, arg ListFailedSyncJobsByProjectForOwnerParams) ([]SyncJob, error)
	// ListFailedSyncProjectsByMember backs the dashboard's "sync failures"
	// section (issue #77): every project ownerID is a member of (any role) that
	// has at least one task with a failed GitLab sync, counted the same way
	// CountFailedSyncTasksByProjectForOwner counts a single project — from
	// task_gitlab_links when a link exists, or from the task's most recent
	// sync_jobs row otherwise — but joined across every project in one round
	// trip instead of one query per project.
	ListFailedSyncProjectsByMember(ctx context.Context, userID uuid.UUID) ([]ListFailedSyncProjectsByMemberRow, error)
	// Ownership of linkID must already be verified by the caller via
	// GetLinkedGitlabProjectForOwner before this runs.
	ListGitlabSyncRunsByLinkedGitlabProjectID(ctx context.Context, linkedGitlabProjectID uuid.UUID) ([]GitlabSyncRun, error)
	ListLinkedGitlabProjectsForOwner(ctx context.Context, arg ListLinkedGitlabProjectsForOwnerParams) ([]LinkedGitlabProject, error)
	ListProjectAPITokensByProject(ctx context.Context, projectID uuid.UUID) ([]ProjectApiToken, error)
	ListProjectMembers(ctx context.Context, projectID uuid.UUID) ([]ProjectMember, error)
	// ListProjectMembersWithUser joins in the username/display name the member
	// list response needs; email is deliberately left out so the response never
	// carries it (issue #100's "avoid user enumeration via email").
	ListProjectMembersWithUser(ctx context.Context, projectID uuid.UUID) ([]ListProjectMembersWithUserRow, error)
	ListProjectsByMember(ctx context.Context, userID uuid.UUID) ([]Project, error)
	ListTaskDependenciesByProject(ctx context.Context, projectID uuid.UUID) ([]TaskDependency, error)
	// ListTasksByProject's priority and progress filters and sorts follow the same
	// "empty/false disables it" convention as the other three filters. Sorting by
	// priority ranks urgent > high > medium > low; sorting by progress runs the
	// other way, not_started first through done, so the order reads as the work
	// advancing (and matches the Board view's left-to-right axis). Both fall back
	// to the usual position/created_at order as a tiebreak, so equal-ranked tasks
	// keep their manual order instead of shuffling; when a sort_by_* flag is false
	// its CASE always evaluates to 0, leaving the original position/created_at
	// order untouched. The two flags are mutually exclusive in practice —
	// internal/task sets at most one from a single ?sort=.
	// ListTasksByProject's assignee_me filter joins the project's own GitLab
	// connection (if any) to the caller's registered identity for that same
	// base_url (internal/gitlabidentity, issue #102): a caller with no
	// registered identity, or a project with no GitLab connection, joins to
	// NULL, and NULL never equals assignee_gitlab_user_id, so the filter
	// correctly yields zero rows instead of erroring.
	ListTasksByProject(ctx context.Context, arg ListTasksByProjectParams) ([]Task, error)
	// ListTasksByProjectPaged backs the AI-facing bulk context endpoint (GET
	// /api/v1/projects/{projectID}/tasks/context, docs/plans/issue-sync.md
	// "AI-facing"): the same backlog_id/status filters as ListTasksByProject
	// plus updated_since (tasks.updated_at >= the given time) and LIMIT/OFFSET
	// paging, following the "fetch one extra row to detect a next page"
	// convention ListWebhookEventsByLinkedGitlabProjectID/internal/webhookevent
	// established. It has no "unassigned" filter — the bulk context view has no
	// use for it yet, unlike the board view ListTasksByProject serves.
	ListTasksByProjectPaged(ctx context.Context, arg ListTasksByProjectPagedParams) ([]Task, error)
	// ListTasksForOwner backs the cross-project task collection (GET
	// /api/v1/tasks, issue #76): every task across every project ownerID owns,
	// narrowed by the same status/priority/progress filters as ListTasksByProject plus
	// due/start date ranges and an optional project_id allowlist — each
	// following the same "empty/NULL disables it" convention. project_name is
	// joined in for the same reason GetTaskGitlabLinkWithProjectPathByTaskID
	// joins in path_with_namespace: a cross-project row is unreadable without
	// knowing which project it belongs to, and a second per-row fetch would
	// cost the same round trip anyway.
	//
	// The ORDER BY leans on two properties: sqlc.arg(sort) is a single bound
	// value for the whole query, not a per-row one, so a CASE guarded by it is
	// either non-NULL for every row or NULL for every row — never a mix: sort
	// values not being ranked stay a true tie and fall through instead of
	// corrupting the row order. And due_on ASC's default NULLS LAST (Postgres
	// sorts NULL last on ASC, first on DESC) is exactly "tasks with no due date
	// sink to the bottom", so it works unguarded both as sort=dueOn's primary
	// key and as every other sort's final tiebreak.
	// ListTasksForMember's assignee_me filter follows the same
	// gitlab_connections/user_gitlab_identities join ListTasksByProject uses
	// (issue #102), joined per-project since the cross-project list spans
	// however many projects and GitLab connections the caller belongs to.
	ListTasksForMember(ctx context.Context, arg ListTasksForMemberParams) ([]ListTasksForMemberRow, error)
	ListUserGitlabIdentitiesByUser(ctx context.Context, userID uuid.UUID) ([]UserGitlabIdentity, error)
	// The troubleshooting read side (issue #26): ListWebhookEventsByLinkedGitlabProjectID
	// and GetWebhookEventByLinkedGitlabProjectIDAndID are scoped by
	// linked_gitlab_project_id only, not owner — internal/webhookevent.Service
	// verifies the caller owns linkID via GetLinkedGitlabProjectForOwner first, the
	// same two-step internal/projectsync's ListRuns uses, so a foreign or unknown
	// eventID under an owned link and an owned eventID under a foreign link both
	// come back empty.
	// status = '' disables the filter, matching ListTasksByProject's convention.
	ListWebhookEventsByLinkedGitlabProjectID(ctx context.Context, arg ListWebhookEventsByLinkedGitlabProjectIDParams) ([]WebhookEvent, error)
	MarkSyncJobFailed(ctx context.Context, arg MarkSyncJobFailedParams) error
	MarkSyncJobRetry(ctx context.Context, arg MarkSyncJobRetryParams) error
	MarkSyncJobSucceeded(ctx context.Context, id uuid.UUID) error
	// MarkTaskGitlabLinkAppliedForTask records a successful inbound apply
	// (internal/webhookapply): only gitlab_updated_at advances and
	// sync_status/last_error clear. Unlike MarkTaskGitlabLinkSyncedForTask (the
	// outbound counterpart), it never touches last_pushed_fingerprint — that
	// field records what FlowLens itself last pushed, and an inbound apply is by
	// definition not that.
	MarkTaskGitlabLinkAppliedForTask(ctx context.Context, arg MarkTaskGitlabLinkAppliedForTaskParams) (TaskGitlabLink, error)
	MarkTaskGitlabLinkFailedForTask(ctx context.Context, arg MarkTaskGitlabLinkFailedForTaskParams) (TaskGitlabLink, error)
	// MarkTaskGitlabLinkPendingForTask is the other half of a sync retry
	// (internal/task.Service.RetrySync, alongside RetryFailedSyncJobForTask in
	// sync_jobs.sql): it puts an already-linked task's sync status back to
	// 'pending' so the UI reflects the retry immediately, without waiting for
	// the worker to pick the job back up. A task whose issue.create never
	// succeeded has no row here yet, so a no-match (no rows returned) is
	// expected and not an error — the caller falls back to sync_jobs alone for
	// that case.
	MarkTaskGitlabLinkPendingForTask(ctx context.Context, taskID uuid.UUID) (TaskGitlabLink, error)
	MarkTaskGitlabLinkSyncedForTask(ctx context.Context, arg MarkTaskGitlabLinkSyncedForTaskParams) (TaskGitlabLink, error)
	MarkWebhookEventFailed(ctx context.Context, arg MarkWebhookEventFailedParams) error
	MarkWebhookEventProcessed(ctx context.Context, id uuid.UUID) error
	MarkWebhookEventSkipped(ctx context.Context, arg MarkWebhookEventSkippedParams) error
	// Used after deleting the default link: makes the oldest remaining link in
	// the same connection the new default. A no-op if none remain.
	PromoteOldestLinkedGitlabProjectAsDefault(ctx context.Context, gitlabConnectionID uuid.UUID) error
	ReclaimStaleRunningSyncJobs(ctx context.Context, updatedAt pgtype.Timestamptz) (int64, error)
	RemoveProjectMember(ctx context.Context, arg RemoveProjectMemberParams) (int64, error)
	ReopenTaskForOwner(ctx context.Context, arg ReopenTaskForOwnerParams) (Task, error)
	// ReorderBacklogs resequences a project's backlogs to backlog_ids' given
	// order (position 0 for the first id, 1 for the second, ...) in a single
	// statement, the same all-or-nothing shape as internal/task's ReorderTasks
	// (issue #79). internal/backlog.Service.Reorder checks backlog_ids is
	// exactly the project's current backlog set before calling this.
	ReorderBacklogs(ctx context.Context, arg ReorderBacklogsParams) error
	// ReorderTasks resequences one backlog bucket's tasks to task_ids' given
	// order (position 0 for the first id, 1 for the second, ...) in a single
	// statement, so a drag across many tasks either lands as one committed order
	// or fails outright, never a partially-applied one (issue #79). backlog_id
	// follows CreateTask's own "IS NOT DISTINCT FROM" convention: NULL scopes to
	// the Unclassified bucket, a UUID to one specific backlog.
	// internal/task.Service.Reorder checks task_ids is exactly that bucket's
	// current task set before calling this, so the WHERE clause can never miss a
	// row or touch one outside the intended bucket.
	ReorderTasks(ctx context.Context, arg ReorderTasksParams) error
	// RetryFailedSyncJobForTask powers POST /tasks/{taskID}/sync-retry: it
	// forces the task's most recent pending-or-failed job to run again
	// immediately with a fresh attempt budget. 'pending' is included alongside
	// 'failed' because task_gitlab_links.sync_status can already read 'failed'
	// (set on the first failed push attempt) while the job itself is still
	// mid-backoff, not yet exhausted — internal/task.Service.RetrySync checks
	// that sync_status first, so by the time this query runs the caller already
	// knows a retry is warranted. Returns no rows if the task has no
	// pending/failed job (e.g. it never had one, or it already succeeded),
	// which internal/task maps to ErrSyncNotFailed.
	RetryFailedSyncJobForTask(ctx context.Context, taskID uuid.UUID) (SyncJob, error)
	// RetrySyncJob mirrors RetryFailedSyncJobForTask's reset (attempts back to
	// 0, a fresh pending attempt) but is keyed by job ID directly rather than by
	// task, and only ever touches a job already 'failed' — the WHERE clause
	// makes a concurrent double-retry (or a retry racing the worker) a no-op
	// reported as no rows, the same convention webhookevent.Retry relies on.
	RetrySyncJob(ctx context.Context, id uuid.UUID) (SyncJob, error)
	// Only a 'failed' event can be retried. internal/webhookevent.Service checks
	// the event exists and is 'failed' via GetWebhookEventByLinkedGitlabProjectIDAndID
	// first, so a zero-row result here is only the rare race where another
	// request already retried it; that maps to the same ErrNotFailed.
	RetryWebhookEvent(ctx context.Context, id uuid.UUID) (WebhookEvent, error)
	SetDefaultLinkedGitlabProjectForOwner(ctx context.Context, arg SetDefaultLinkedGitlabProjectForOwnerParams) (LinkedGitlabProject, error)
	// Records why registering or repairing a webhook failed (most commonly
	// insufficient GitLab permissions) without touching any existing
	// webhook_id, so the link stays usable via manual sync.
	SetLinkedGitlabProjectWebhookErrorForOwner(ctx context.Context, arg SetLinkedGitlabProjectWebhookErrorForOwnerParams) (LinkedGitlabProject, error)
	// Records a successful webhook registration or rotation (issue #18) and
	// clears any earlier registration error.
	SetLinkedGitlabProjectWebhookForOwner(ctx context.Context, arg SetLinkedGitlabProjectWebhookForOwnerParams) (LinkedGitlabProject, error)
	// UpdateBacklogForOwner overwrites every editable column, so start_date/due_on
	// must arrive already resolved: backlog.Service reads the current row first and
	// fills in whatever the PATCH body left out (see its Update).
	UpdateBacklogForOwner(ctx context.Context, arg UpdateBacklogForOwnerParams) (Backlog, error)
	UpdateGitlabConnectionVerificationForOwner(ctx context.Context, arg UpdateGitlabConnectionVerificationForOwnerParams) (GitlabConnection, error)
	// Unscoped, for the same reason as UpdateLinkedGitlabProjectLastSyncedAt.
	// Values used: "pending" (default), "completed", "failed"
	// (internal/projectsync).
	UpdateLinkedGitlabProjectInitialImportStatus(ctx context.Context, arg UpdateLinkedGitlabProjectInitialImportStatusParams) (LinkedGitlabProject, error)
	// Unscoped, like GetLinkedGitlabProjectByID: called by the background
	// worker (internal/projectsync) after a project.import/project.resync run
	// finishes, which has no acting user to scope through.
	UpdateLinkedGitlabProjectLastSyncedAt(ctx context.Context, id uuid.UUID) (LinkedGitlabProject, error)
	// Everything below is member-minimum (issue #99): using an already-connected
	// project to link/sync is a member-level action, distinct from managing the
	// connection's credential itself (owner-only, gitlab_connections.sql).
	UpdateLinkedGitlabProjectSyncScopeForOwner(ctx context.Context, arg UpdateLinkedGitlabProjectSyncScopeForOwnerParams) (LinkedGitlabProject, error)
	UpdateProjectAPITokenLastUsedAt(ctx context.Context, arg UpdateProjectAPITokenLastUsedAtParams) error
	// UpdateProjectForOwner backs project.Service.Update (name/description
	// edit), member-minimum per issue #99 — not explicitly named owner-only, so
	// it follows the "writes are member-tier by default" rule.
	UpdateProjectForOwner(ctx context.Context, arg UpdateProjectForOwnerParams) (Project, error)
	UpdateProjectMemberRole(ctx context.Context, arg UpdateProjectMemberRoleParams) (ProjectMember, error)
	UpdateTaskForOwner(ctx context.Context, arg UpdateTaskForOwnerParams) (Task, error)
	// gitlab_connections has no owner column of its own; ownership is always
	// checked through the parent project, the same way backlogs and tasks are.
	// UpsertGitlabConnection trusts the caller to have already verified project
	// ownership (e.g. via project.Service.Get) before running, while the other
	// queries join to projects so a foreign connection is indistinguishable from
	// a missing one. The access token is only ever handled encrypted here; see
	// internal/crypto and internal/gitlabconn.
	UpsertGitlabConnection(ctx context.Context, arg UpsertGitlabConnectionParams) (GitlabConnection, error)
	// task_ai_contexts is app-only: acceptance criteria, AI context, and the
	// allowed/forbidden change scope must never be sent to GitLab (see "Why the
	// task is split across three tables" in docs/plans/issue-sync.md). Ownership
	// is verified by the caller via task.Service.Get before either query runs,
	// the same way CreateTask trusts an already-verified project.
	UpsertTaskAIContext(ctx context.Context, arg UpsertTaskAIContextParams) (TaskAiContext, error)
	// user_gitlab_identities maps a FlowLens user to their GitLab user ID/username
	// on one GitLab CE instance (gitlab_base_url), so ?assignee=me on the task
	// collections (internal/task) can match against tasks.assignee_gitlab_user_id.
	// UpsertUserGitlabIdentity is the only write: a user re-registering the same
	// base_url replaces the previous mapping rather than erroring.
	UpsertUserGitlabIdentity(ctx context.Context, arg UpsertUserGitlabIdentityParams) (UserGitlabIdentity, error)
}

var _ Querier = (*Queries)(nil)
