// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AssignTaskBacklogForOwner(ctx context.Context, arg AssignTaskBacklogForOwnerParams) (Task, error)
	CloseTaskForOwner(ctx context.Context, arg CloseTaskForOwnerParams) (Task, error)
	// Every project-scoped query filters on owner_user_id in SQL. Authorization
	// is therefore enforced by the query itself: a non-owner gets "no rows",
	// which callers map to ErrNotFound. Handlers must never do their own
	// ownership check, and later project-scoped tables follow the same rule.
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	// Backlogs have no owner column of their own; ownership is always checked
	// through the parent project. CreateBacklog/ListBacklogsByProject trust the
	// caller to have already verified project ownership (e.g. via
	// project.Service.Get), while the single-backlog queries join to projects so
	// a foreign backlog is indistinguishable from a missing one.
	CreateBacklog(ctx context.Context, arg CreateBacklogParams) (Backlog, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// Tasks are scoped through their parent project the same way backlogs are:
	// every single-task query joins to projects and filters on owner_user_id,
	// so a foreign task is indistinguishable from a missing one. CreateTask
	// trusts the caller to have already verified project ownership.
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBacklogForOwner(ctx context.Context, arg DeleteBacklogForOwnerParams) (int64, error)
	DeleteExpiredSessions(ctx context.Context) error
	DeleteProjectForOwner(ctx context.Context, arg DeleteProjectForOwnerParams) (int64, error)
	DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error
	DeleteTaskForOwner(ctx context.Context, arg DeleteTaskForOwnerParams) (int64, error)
	GetBacklogForOwner(ctx context.Context, arg GetBacklogForOwnerParams) (Backlog, error)
	GetProjectForOwner(ctx context.Context, arg GetProjectForOwnerParams) (Project, error)
	// task_ai_contexts is app-only and must never be sent to GitLab (see "Why
	// the task is split across three tables" in docs/plans/issue-sync.md).
	// Callers verify task ownership via task.Service.Get before either query
	// runs, the same way CreateTask trusts an already-verified project.
	GetTaskAIContext(ctx context.Context, taskID uuid.UUID) (TaskAiContext, error)
	GetTaskForOwner(ctx context.Context, arg GetTaskForOwnerParams) (Task, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserBySessionToken(ctx context.Context, tokenHash string) (GetUserBySessionTokenRow, error)
	GetUserByUsernameOrEmail(ctx context.Context, username string) (User, error)
	ListBacklogsByProject(ctx context.Context, projectID uuid.UUID) ([]Backlog, error)
	ListProjectsByOwner(ctx context.Context, ownerUserID uuid.UUID) ([]Project, error)
	// ListTasksByProject takes three independent optional filters so one query
	// serves the unfiltered, single-backlog, unassigned-only and status-scoped
	// list views: passing false/NULL/'' for a filter disables it.
	ListTasksByProject(ctx context.Context, arg ListTasksByProjectParams) ([]Task, error)
	ReopenTaskForOwner(ctx context.Context, arg ReopenTaskForOwnerParams) (Task, error)
	UpdateBacklogForOwner(ctx context.Context, arg UpdateBacklogForOwnerParams) (Backlog, error)
	UpdateProjectForOwner(ctx context.Context, arg UpdateProjectForOwnerParams) (Project, error)
	UpdateTaskForOwner(ctx context.Context, arg UpdateTaskForOwnerParams) (Task, error)
	UpsertTaskAIContext(ctx context.Context, arg UpsertTaskAIContextParams) (TaskAiContext, error)
}

var _ Querier = (*Queries)(nil)
