// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repositories.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createRepository = `-- name: CreateRepository :one

INSERT INTO repositories (
    linked_gitlab_project_id, name, full_name, description, is_private,
    default_branch, html_url, is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, true
)
RETURNING id, name, full_name, description, is_private, default_branch, html_url, is_active, created_at, updated_at, linked_gitlab_project_id
`

type CreateRepositoryParams struct {
	LinkedGitlabProjectID uuid.UUID `json:"linked_gitlab_project_id"`
	Name                  string    `json:"name"`
	FullName              string    `json:"full_name"`
	Description           string    `json:"description"`
	IsPrivate             bool      `json:"is_private"`
	DefaultBranch         string    `json:"default_branch"`
	HtmlUrl               string    `json:"html_url"`
}

// repositories is the MR-tracking sibling of a linked GitLab project
// (ADR-0011 §1): one linked_gitlab_projects row has at most one repositories
// row, created automatically alongside it (internal/linkedproject.Service.Create),
// never through a separate flow. No owner column of its own — every access
// goes through linked_gitlab_projects, same as task_gitlab_links.
func (q *Queries) CreateRepository(ctx context.Context, arg CreateRepositoryParams) (Repository, error) {
	row := q.db.QueryRow(ctx, createRepository,
		arg.LinkedGitlabProjectID,
		arg.Name,
		arg.FullName,
		arg.Description,
		arg.IsPrivate,
		arg.DefaultBranch,
		arg.HtmlUrl,
	)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FullName,
		&i.Description,
		&i.IsPrivate,
		&i.DefaultBranch,
		&i.HtmlUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LinkedGitlabProjectID,
	)
	return i, err
}

const getRepositoryByID = `-- name: GetRepositoryByID :one
SELECT id, name, full_name, description, is_private, default_branch, html_url, is_active, created_at, updated_at, linked_gitlab_project_id FROM repositories WHERE id = $1
`

func (q *Queries) GetRepositoryByID(ctx context.Context, id uuid.UUID) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepositoryByID, id)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FullName,
		&i.Description,
		&i.IsPrivate,
		&i.DefaultBranch,
		&i.HtmlUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LinkedGitlabProjectID,
	)
	return i, err
}

const getRepositoryByLinkedGitlabProjectID = `-- name: GetRepositoryByLinkedGitlabProjectID :one
SELECT id, name, full_name, description, is_private, default_branch, html_url, is_active, created_at, updated_at, linked_gitlab_project_id FROM repositories WHERE linked_gitlab_project_id = $1
`

// Unscoped, like GetLinkedGitlabProjectByID: the background sync worker
// (internal/mrsync) reads this with no acting user of its own — the job row
// that names this repository's linked project was already authorized when
// it was created.
func (q *Queries) GetRepositoryByLinkedGitlabProjectID(ctx context.Context, linkedGitlabProjectID uuid.UUID) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepositoryByLinkedGitlabProjectID, linkedGitlabProjectID)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FullName,
		&i.Description,
		&i.IsPrivate,
		&i.DefaultBranch,
		&i.HtmlUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LinkedGitlabProjectID,
	)
	return i, err
}
