// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repository_sync_runs.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const completeRepositorySyncRun = `-- name: CompleteRepositorySyncRun :one
UPDATE repository_sync_runs
SET status = 'succeeded',
    mrs_seen = $2,
    mrs_created = $3,
    mrs_updated = $4,
    completed_at = now()
WHERE id = $1
RETURNING id, repository_id, status, started_at, completed_at, error_message, created_at, kind, mrs_seen, mrs_created, mrs_updated
`

type CompleteRepositorySyncRunParams struct {
	ID         uuid.UUID `json:"id"`
	MrsSeen    int32     `json:"mrs_seen"`
	MrsCreated int32     `json:"mrs_created"`
	MrsUpdated int32     `json:"mrs_updated"`
}

func (q *Queries) CompleteRepositorySyncRun(ctx context.Context, arg CompleteRepositorySyncRunParams) (RepositorySyncRun, error) {
	row := q.db.QueryRow(ctx, completeRepositorySyncRun,
		arg.ID,
		arg.MrsSeen,
		arg.MrsCreated,
		arg.MrsUpdated,
	)
	var i RepositorySyncRun
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.Kind,
		&i.MrsSeen,
		&i.MrsCreated,
		&i.MrsUpdated,
	)
	return i, err
}

const createRepositorySyncRun = `-- name: CreateRepositorySyncRun :one

INSERT INTO repository_sync_runs (repository_id, kind, status, started_at)
VALUES ($1, $2, 'running', now())
RETURNING id, repository_id, status, started_at, completed_at, error_message, created_at, kind, mrs_seen, mrs_created, mrs_updated
`

type CreateRepositorySyncRunParams struct {
	RepositoryID uuid.UUID `json:"repository_id"`
	Kind         string    `json:"kind"`
}

// repository_sync_runs records one mr.import / mr.resync execution against a
// repository (ADR-0011 §2: reuses gitlab_sync_runs' shape, scoped to a
// Repository instead of a LinkedGitlabProject). Concurrency is enforced at
// the database level: a partial UNIQUE index on (repository_id) WHERE
// completed_at IS NULL (migration 000019) means CreateRepositorySyncRun
// itself fails with a unique-constraint violation when a run is already in
// progress for the same repository, which internal/mrsync maps to
// ErrRunInProgress (HTTP 409), the same as issue sync's gitlab_sync_runs.
func (q *Queries) CreateRepositorySyncRun(ctx context.Context, arg CreateRepositorySyncRunParams) (RepositorySyncRun, error) {
	row := q.db.QueryRow(ctx, createRepositorySyncRun, arg.RepositoryID, arg.Kind)
	var i RepositorySyncRun
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.Kind,
		&i.MrsSeen,
		&i.MrsCreated,
		&i.MrsUpdated,
	)
	return i, err
}

const failRepositorySyncRun = `-- name: FailRepositorySyncRun :one
UPDATE repository_sync_runs
SET status = 'failed',
    mrs_seen = $2,
    mrs_created = $3,
    mrs_updated = $4,
    error_message = $5,
    completed_at = now()
WHERE id = $1
RETURNING id, repository_id, status, started_at, completed_at, error_message, created_at, kind, mrs_seen, mrs_created, mrs_updated
`

type FailRepositorySyncRunParams struct {
	ID           uuid.UUID `json:"id"`
	MrsSeen      int32     `json:"mrs_seen"`
	MrsCreated   int32     `json:"mrs_created"`
	MrsUpdated   int32     `json:"mrs_updated"`
	ErrorMessage string    `json:"error_message"`
}

func (q *Queries) FailRepositorySyncRun(ctx context.Context, arg FailRepositorySyncRunParams) (RepositorySyncRun, error) {
	row := q.db.QueryRow(ctx, failRepositorySyncRun,
		arg.ID,
		arg.MrsSeen,
		arg.MrsCreated,
		arg.MrsUpdated,
		arg.ErrorMessage,
	)
	var i RepositorySyncRun
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.Kind,
		&i.MrsSeen,
		&i.MrsCreated,
		&i.MrsUpdated,
	)
	return i, err
}

const getRepositorySyncRunByID = `-- name: GetRepositorySyncRunByID :one
SELECT id, repository_id, status, started_at, completed_at, error_message, created_at, kind, mrs_seen, mrs_created, mrs_updated FROM repository_sync_runs WHERE id = $1
`

// Unscoped, like GetGitlabSyncRunByID: the background worker
// (internal/mrsync) reads this with no acting user of its own — the job row
// that names this run's ID was already authorized when it was created
// (automatically, alongside the repository, at link creation).
func (q *Queries) GetRepositorySyncRunByID(ctx context.Context, id uuid.UUID) (RepositorySyncRun, error) {
	row := q.db.QueryRow(ctx, getRepositorySyncRunByID, id)
	var i RepositorySyncRun
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.Kind,
		&i.MrsSeen,
		&i.MrsCreated,
		&i.MrsUpdated,
	)
	return i, err
}
