// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync_jobs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimPendingSyncJobs = `-- name: ClaimPendingSyncJobs :many

WITH claimed AS (
    SELECT id FROM sync_jobs
    WHERE status = 'pending' AND run_after <= now()
    ORDER BY run_after ASC
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
UPDATE sync_jobs
SET status = 'running', updated_at = now()
WHERE id IN (SELECT id FROM claimed)
RETURNING id, project_id, task_id, kind, payload, dedupe_key, status, attempts, run_after, last_error, created_at, updated_at
`

// The outbox worker (internal/sync, docs/plans/issue-sync.md "Sync engine").
//
// EnqueueSyncJob upserts on dedupe_key: a colliding insert only overwrites the
// existing row while it is still 'pending' (collapsing rapid repeated edits
// into one job); a collision with a running/succeeded/failed row leaves that
// row untouched and returns no rows, so the caller falls back to
// GetSyncJobByDedupeKey and reuses it as-is. MarkSyncJobSucceeded and
// MarkSyncJobFailed clear dedupe_key so a later edit is never permanently
// blocked by a job that already reached a terminal state.
//
// ClaimPendingSyncJobs is the SKIP LOCKED claim: it atomically selects and
// flips due pending jobs to 'running' in one statement, so two workers
// polling concurrently never claim the same row.
func (q *Queries) ClaimPendingSyncJobs(ctx context.Context, limit int32) ([]SyncJob, error) {
	rows, err := q.db.Query(ctx, claimPendingSyncJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncJob{}
	for rows.Next() {
		var i SyncJob
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TaskID,
			&i.Kind,
			&i.Payload,
			&i.DedupeKey,
			&i.Status,
			&i.Attempts,
			&i.RunAfter,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueueSyncJob = `-- name: EnqueueSyncJob :one
INSERT INTO sync_jobs (project_id, task_id, kind, payload, dedupe_key)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (dedupe_key) DO UPDATE
SET payload = EXCLUDED.payload, updated_at = now()
WHERE sync_jobs.status = 'pending'
RETURNING id, project_id, task_id, kind, payload, dedupe_key, status, attempts, run_after, last_error, created_at, updated_at
`

type EnqueueSyncJobParams struct {
	ProjectID uuid.UUID   `json:"project_id"`
	TaskID    pgtype.UUID `json:"task_id"`
	Kind      string      `json:"kind"`
	Payload   []byte      `json:"payload"`
	DedupeKey pgtype.Text `json:"dedupe_key"`
}

func (q *Queries) EnqueueSyncJob(ctx context.Context, arg EnqueueSyncJobParams) (SyncJob, error) {
	row := q.db.QueryRow(ctx, enqueueSyncJob,
		arg.ProjectID,
		arg.TaskID,
		arg.Kind,
		arg.Payload,
		arg.DedupeKey,
	)
	var i SyncJob
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskID,
		&i.Kind,
		&i.Payload,
		&i.DedupeKey,
		&i.Status,
		&i.Attempts,
		&i.RunAfter,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestSyncJobForTask = `-- name: GetLatestSyncJobForTask :one

SELECT id, project_id, task_id, kind, payload, dedupe_key, status, attempts, run_after, last_error, created_at, updated_at
FROM sync_jobs
WHERE task_id = $1::uuid
ORDER BY created_at DESC
LIMIT 1
`

// GetLatestSyncJobForTask backs a task's sync status (internal/task) when it
// has no task_gitlab_links row yet — i.e. its issue.create job hasn't
// succeeded (or has permanently failed), so there is nothing in
// task_gitlab_links to read sync_status from. Before a link exists, a task
// can only ever have enqueued issue.create jobs (issue.update/close/reopen
// all require an existing link), so "latest" is unambiguous.
func (q *Queries) GetLatestSyncJobForTask(ctx context.Context, taskID uuid.UUID) (SyncJob, error) {
	row := q.db.QueryRow(ctx, getLatestSyncJobForTask, taskID)
	var i SyncJob
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskID,
		&i.Kind,
		&i.Payload,
		&i.DedupeKey,
		&i.Status,
		&i.Attempts,
		&i.RunAfter,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSyncJobByDedupeKey = `-- name: GetSyncJobByDedupeKey :one
SELECT id, project_id, task_id, kind, payload, dedupe_key, status, attempts, run_after, last_error, created_at, updated_at
FROM sync_jobs
WHERE dedupe_key = $1
`

func (q *Queries) GetSyncJobByDedupeKey(ctx context.Context, dedupeKey pgtype.Text) (SyncJob, error) {
	row := q.db.QueryRow(ctx, getSyncJobByDedupeKey, dedupeKey)
	var i SyncJob
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskID,
		&i.Kind,
		&i.Payload,
		&i.DedupeKey,
		&i.Status,
		&i.Attempts,
		&i.RunAfter,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markSyncJobFailed = `-- name: MarkSyncJobFailed :exec
UPDATE sync_jobs
SET status = 'failed', attempts = attempts + 1, dedupe_key = NULL, last_error = $2, updated_at = now()
WHERE id = $1
`

type MarkSyncJobFailedParams struct {
	ID        uuid.UUID `json:"id"`
	LastError string    `json:"last_error"`
}

func (q *Queries) MarkSyncJobFailed(ctx context.Context, arg MarkSyncJobFailedParams) error {
	_, err := q.db.Exec(ctx, markSyncJobFailed, arg.ID, arg.LastError)
	return err
}

const markSyncJobRetry = `-- name: MarkSyncJobRetry :exec
UPDATE sync_jobs
SET status = 'pending', attempts = attempts + 1, run_after = $2, last_error = $3, updated_at = now()
WHERE id = $1
`

type MarkSyncJobRetryParams struct {
	ID        uuid.UUID          `json:"id"`
	RunAfter  pgtype.Timestamptz `json:"run_after"`
	LastError string             `json:"last_error"`
}

func (q *Queries) MarkSyncJobRetry(ctx context.Context, arg MarkSyncJobRetryParams) error {
	_, err := q.db.Exec(ctx, markSyncJobRetry, arg.ID, arg.RunAfter, arg.LastError)
	return err
}

const markSyncJobSucceeded = `-- name: MarkSyncJobSucceeded :exec
UPDATE sync_jobs
SET status = 'succeeded', dedupe_key = NULL, last_error = '', updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkSyncJobSucceeded(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markSyncJobSucceeded, id)
	return err
}

const reclaimStaleRunningSyncJobs = `-- name: ReclaimStaleRunningSyncJobs :execrows
UPDATE sync_jobs
SET status = 'pending', updated_at = now()
WHERE status = 'running' AND updated_at < $1
`

func (q *Queries) ReclaimStaleRunningSyncJobs(ctx context.Context, updatedAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, reclaimStaleRunningSyncJobs, updatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryFailedSyncJobForTask = `-- name: RetryFailedSyncJobForTask :one

UPDATE sync_jobs
SET status = 'pending', attempts = 0, run_after = now(), last_error = ''
WHERE id = (
    SELECT id FROM sync_jobs
    WHERE task_id = $1::uuid AND status IN ('pending', 'failed')
    ORDER BY created_at DESC
    LIMIT 1
)
RETURNING id, project_id, task_id, kind, payload, dedupe_key, status, attempts, run_after, last_error, created_at, updated_at
`

// RetryFailedSyncJobForTask powers POST /tasks/{taskID}/sync-retry: it
// forces the task's most recent pending-or-failed job to run again
// immediately with a fresh attempt budget. 'pending' is included alongside
// 'failed' because task_gitlab_links.sync_status can already read 'failed'
// (set on the first failed push attempt) while the job itself is still
// mid-backoff, not yet exhausted — internal/task.Service.RetrySync checks
// that sync_status first, so by the time this query runs the caller already
// knows a retry is warranted. Returns no rows if the task has no
// pending/failed job (e.g. it never had one, or it already succeeded),
// which internal/task maps to ErrSyncNotFailed.
func (q *Queries) RetryFailedSyncJobForTask(ctx context.Context, taskID uuid.UUID) (SyncJob, error) {
	row := q.db.QueryRow(ctx, retryFailedSyncJobForTask, taskID)
	var i SyncJob
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskID,
		&i.Kind,
		&i.Payload,
		&i.DedupeKey,
		&i.Status,
		&i.Attempts,
		&i.RunAfter,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
