// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const applyWebhookTaskFields = `-- name: ApplyWebhookTaskFields :one

UPDATE tasks
SET title = $2,
    description = $3,
    assignee_gitlab_user_id = $4,
    assignee_gitlab_username = $5,
    labels = $6,
    due_on = $7,
    status = $8,
    closed_at = CASE WHEN $8 = 'closed' THEN COALESCE(closed_at, now()) ELSE NULL END,
    updated_at = now()
WHERE id = $1
RETURNING id, project_id, backlog_id, title, description, status, closed_at, assignee_gitlab_user_id, assignee_gitlab_username, labels, due_on, start_date, priority, position, created_by_user_id, created_at, updated_at
`

type ApplyWebhookTaskFieldsParams struct {
	ID                     uuid.UUID   `json:"id"`
	Title                  string      `json:"title"`
	Description            string      `json:"description"`
	AssigneeGitlabUserID   pgtype.Int8 `json:"assignee_gitlab_user_id"`
	AssigneeGitlabUsername string      `json:"assignee_gitlab_username"`
	Labels                 []string    `json:"labels"`
	DueOn                  pgtype.Date `json:"due_on"`
	Status                 string      `json:"status"`
}

// ApplyWebhookTaskFields is the inbound apply pipeline's write to tasks
// (internal/webhookapply, docs/plans/issue-sync.md "Inbound"): unscoped, like
// GetLinkedGitlabProjectByID, because the task_gitlab_links row that names
// this task ID was already authorized when the link was first created (or,
// for a brand-new unclassified task, in the same transaction that just
// created it). It never touches backlog_id or position, which are app-only.
// closed_at only advances when status transitions into 'closed' — the CASE
// reads the pre-update closed_at (every SET expression in one UPDATE sees
// the same original row), so re-applying while already closed never moves
// the timestamp, mirroring internal/task.Service.Close's own no-op rule.
func (q *Queries) ApplyWebhookTaskFields(ctx context.Context, arg ApplyWebhookTaskFieldsParams) (Task, error) {
	row := q.db.QueryRow(ctx, applyWebhookTaskFields,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.AssigneeGitlabUserID,
		arg.AssigneeGitlabUsername,
		arg.Labels,
		arg.DueOn,
		arg.Status,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BacklogID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.ClosedAt,
		&i.AssigneeGitlabUserID,
		&i.AssigneeGitlabUsername,
		&i.Labels,
		&i.DueOn,
		&i.StartDate,
		&i.Priority,
		&i.Position,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const assignTaskBacklogForOwner = `-- name: AssignTaskBacklogForOwner :one
UPDATE tasks t
SET backlog_id = $3, updated_at = now()
FROM projects p
WHERE t.id = $1 AND t.project_id = p.id AND p.owner_user_id = $2
RETURNING t.id, t.project_id, t.backlog_id, t.title, t.description, t.status, t.closed_at, t.assignee_gitlab_user_id, t.assignee_gitlab_username, t.labels, t.due_on, t.start_date, t.priority, t.position, t.created_by_user_id, t.created_at, t.updated_at
`

type AssignTaskBacklogForOwnerParams struct {
	ID          uuid.UUID   `json:"id"`
	OwnerUserID uuid.UUID   `json:"owner_user_id"`
	BacklogID   pgtype.UUID `json:"backlog_id"`
}

func (q *Queries) AssignTaskBacklogForOwner(ctx context.Context, arg AssignTaskBacklogForOwnerParams) (Task, error) {
	row := q.db.QueryRow(ctx, assignTaskBacklogForOwner, arg.ID, arg.OwnerUserID, arg.BacklogID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BacklogID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.ClosedAt,
		&i.AssigneeGitlabUserID,
		&i.AssigneeGitlabUsername,
		&i.Labels,
		&i.DueOn,
		&i.StartDate,
		&i.Priority,
		&i.Position,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const closeTaskForOwner = `-- name: CloseTaskForOwner :one
UPDATE tasks t
SET status = 'closed', closed_at = now(), updated_at = now()
FROM projects p
WHERE t.id = $1 AND t.project_id = p.id AND p.owner_user_id = $2
RETURNING t.id, t.project_id, t.backlog_id, t.title, t.description, t.status, t.closed_at, t.assignee_gitlab_user_id, t.assignee_gitlab_username, t.labels, t.due_on, t.start_date, t.priority, t.position, t.created_by_user_id, t.created_at, t.updated_at
`

type CloseTaskForOwnerParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) CloseTaskForOwner(ctx context.Context, arg CloseTaskForOwnerParams) (Task, error) {
	row := q.db.QueryRow(ctx, closeTaskForOwner, arg.ID, arg.OwnerUserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BacklogID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.ClosedAt,
		&i.AssigneeGitlabUserID,
		&i.AssigneeGitlabUsername,
		&i.Labels,
		&i.DueOn,
		&i.StartDate,
		&i.Priority,
		&i.Position,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countFailedSyncTasksByProjectForOwner = `-- name: CountFailedSyncTasksByProjectForOwner :one

SELECT COUNT(*) FROM tasks t
JOIN projects p ON p.id = t.project_id
LEFT JOIN task_gitlab_links tgl ON tgl.task_id = t.id
WHERE t.project_id = $1 AND p.owner_user_id = $2
  AND (
    tgl.sync_status = 'failed'
    OR (tgl.task_id IS NULL AND EXISTS (
      SELECT 1 FROM sync_jobs sj WHERE sj.task_id = t.id AND sj.status = 'failed'
    ))
  )
`

type CountFailedSyncTasksByProjectForOwnerParams struct {
	ProjectID   uuid.UUID `json:"project_id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

// CountFailedSyncTasksByProjectForOwner backs the project single view's sync
// warning (docs/plans/issue-sync.md's "gitlab" fields, surfaced per-task by
// internal/task). A task counts as failed the same way internal/task derives
// a single task's sync_status: from task_gitlab_links when a link exists, or
// from its most recent sync_jobs row (necessarily an issue.create, see
// GetLatestSyncJobForTask) when it doesn't.
func (q *Queries) CountFailedSyncTasksByProjectForOwner(ctx context.Context, arg CountFailedSyncTasksByProjectForOwnerParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFailedSyncTasksByProjectForOwner, arg.ProjectID, arg.OwnerUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTask = `-- name: CreateTask :one

INSERT INTO tasks (
    project_id, backlog_id, title, description,
    assignee_gitlab_user_id, assignee_gitlab_username,
    labels, due_on, start_date, priority, created_by_user_id, position
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11,
    COALESCE((SELECT MAX(position) + 1 FROM tasks WHERE project_id = $1 AND backlog_id IS NOT DISTINCT FROM $2), 0)
)
RETURNING id, project_id, backlog_id, title, description, status, closed_at, assignee_gitlab_user_id, assignee_gitlab_username, labels, due_on, start_date, priority, position, created_by_user_id, created_at, updated_at
`

type CreateTaskParams struct {
	ProjectID              uuid.UUID   `json:"project_id"`
	BacklogID              pgtype.UUID `json:"backlog_id"`
	Title                  string      `json:"title"`
	Description            string      `json:"description"`
	AssigneeGitlabUserID   pgtype.Int8 `json:"assignee_gitlab_user_id"`
	AssigneeGitlabUsername string      `json:"assignee_gitlab_username"`
	Labels                 []string    `json:"labels"`
	DueOn                  pgtype.Date `json:"due_on"`
	StartDate              pgtype.Date `json:"start_date"`
	Priority               string      `json:"priority"`
	CreatedByUserID        uuid.UUID   `json:"created_by_user_id"`
}

// Tasks are scoped through their parent project the same way backlogs are:
// every single-task query joins to projects and filters on
// owner_user_id, so a foreign task is indistinguishable from a missing one.
// CreateTask trusts the caller to have already verified project ownership
// (e.g. via project.Service.Get), like CreateBacklog.
//
// ListTasksByProject takes three independent optional filters so one query
// serves the unfiltered, single-backlog, unassigned-only and status-scoped
// list views: passing false/NULL/” for a filter disables it.
func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ProjectID,
		arg.BacklogID,
		arg.Title,
		arg.Description,
		arg.AssigneeGitlabUserID,
		arg.AssigneeGitlabUsername,
		arg.Labels,
		arg.DueOn,
		arg.StartDate,
		arg.Priority,
		arg.CreatedByUserID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BacklogID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.ClosedAt,
		&i.AssigneeGitlabUserID,
		&i.AssigneeGitlabUsername,
		&i.Labels,
		&i.DueOn,
		&i.StartDate,
		&i.Priority,
		&i.Position,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTaskForOwner = `-- name: DeleteTaskForOwner :execrows
DELETE FROM tasks t
USING projects p
WHERE t.id = $1 AND t.project_id = p.id AND p.owner_user_id = $2
`

type DeleteTaskForOwnerParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) DeleteTaskForOwner(ctx context.Context, arg DeleteTaskForOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTaskForOwner, arg.ID, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTaskForOwner = `-- name: GetTaskForOwner :one
SELECT t.id, t.project_id, t.backlog_id, t.title, t.description, t.status, t.closed_at, t.assignee_gitlab_user_id, t.assignee_gitlab_username, t.labels, t.due_on, t.start_date, t.priority, t.position, t.created_by_user_id, t.created_at, t.updated_at
FROM tasks t
JOIN projects p ON p.id = t.project_id
WHERE t.id = $1 AND p.owner_user_id = $2
`

type GetTaskForOwnerParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) GetTaskForOwner(ctx context.Context, arg GetTaskForOwnerParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskForOwner, arg.ID, arg.OwnerUserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BacklogID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.ClosedAt,
		&i.AssigneeGitlabUserID,
		&i.AssigneeGitlabUsername,
		&i.Labels,
		&i.DueOn,
		&i.StartDate,
		&i.Priority,
		&i.Position,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskForProject = `-- name: GetTaskForProject :one

SELECT id, project_id, backlog_id, title, description, status, closed_at, assignee_gitlab_user_id, assignee_gitlab_username, labels, due_on, start_date, priority, position, created_by_user_id, created_at, updated_at
FROM tasks
WHERE id = $1 AND project_id = $2
`

type GetTaskForProjectParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

// GetTaskForProject scopes a task by its project directly, not by owner: the
// AI-facing bearer-token path (docs/plans/issue-sync.md "AI-facing") has no
// session user, only the project a project.Service-verified token was issued
// for (internal/apitoken), so there is no owner to join against.
func (q *Queries) GetTaskForProject(ctx context.Context, arg GetTaskForProjectParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskForProject, arg.ID, arg.ProjectID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BacklogID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.ClosedAt,
		&i.AssigneeGitlabUserID,
		&i.AssigneeGitlabUsername,
		&i.Labels,
		&i.DueOn,
		&i.StartDate,
		&i.Priority,
		&i.Position,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskProjectID = `-- name: GetTaskProjectID :one

SELECT project_id FROM tasks WHERE id = $1
`

// GetTaskProjectID is the lightweight project lookup
// requireTokenResourceProject (internal/http, issue #66) uses to enforce a
// bearer token's project boundary on a single-task URL. It has no owner
// join, unlike GetTaskForOwner: a token has no session owner to join
// against (apitoken.Auth), only its own project to compare the result
// against.
func (q *Queries) GetTaskProjectID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getTaskProjectID, id)
	var project_id uuid.UUID
	err := row.Scan(&project_id)
	return project_id, err
}

const listTasksByProject = `-- name: ListTasksByProject :many
SELECT id, project_id, backlog_id, title, description, status, closed_at, assignee_gitlab_user_id, assignee_gitlab_username, labels, due_on, start_date, priority, position, created_by_user_id, created_at, updated_at
FROM tasks
WHERE project_id = $1
  AND (NOT $2::boolean OR backlog_id IS NULL)
  AND ($3::uuid IS NULL OR backlog_id = $3)
  AND ($4::text = '' OR status = $4)
  AND ($5::text = '' OR priority = $5)
ORDER BY
  (CASE WHEN $6::boolean THEN
     CASE priority WHEN 'urgent' THEN 4 WHEN 'high' THEN 3 WHEN 'medium' THEN 2 WHEN 'low' THEN 1 ELSE 0 END
   ELSE 0 END) DESC,
  position ASC, created_at ASC
`

type ListTasksByProjectParams struct {
	ProjectID      uuid.UUID   `json:"project_id"`
	Unassigned     bool        `json:"unassigned"`
	BacklogID      pgtype.UUID `json:"backlog_id"`
	Status         string      `json:"status"`
	Priority       string      `json:"priority"`
	SortByPriority bool        `json:"sort_by_priority"`
}

// ListTasksByProject's priority filter and sort follow the same "empty/false
// disables it" convention as the other three filters. Sorting by priority
// ranks urgent > high > medium > low and falls back to the usual position/
// created_at order as a tiebreak, so equal-priority tasks keep their manual
// order instead of shuffling; when sort_by_priority is false the CASE always
// evaluates to 0, leaving the original position/created_at order untouched.
func (q *Queries) ListTasksByProject(ctx context.Context, arg ListTasksByProjectParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByProject,
		arg.ProjectID,
		arg.Unassigned,
		arg.BacklogID,
		arg.Status,
		arg.Priority,
		arg.SortByPriority,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.BacklogID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.ClosedAt,
			&i.AssigneeGitlabUserID,
			&i.AssigneeGitlabUsername,
			&i.Labels,
			&i.DueOn,
			&i.StartDate,
			&i.Priority,
			&i.Position,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByProjectPaged = `-- name: ListTasksByProjectPaged :many

SELECT id, project_id, backlog_id, title, description, status, closed_at, assignee_gitlab_user_id, assignee_gitlab_username, labels, due_on, start_date, priority, position, created_by_user_id, created_at, updated_at
FROM tasks
WHERE project_id = $1
  AND ($2::uuid IS NULL OR backlog_id = $2)
  AND ($3::text = '' OR status = $3)
  AND ($4::timestamptz IS NULL OR updated_at >= $4)
ORDER BY position ASC, created_at ASC
LIMIT $5 OFFSET $6
`

type ListTasksByProjectPagedParams struct {
	ProjectID    uuid.UUID          `json:"project_id"`
	BacklogID    pgtype.UUID        `json:"backlog_id"`
	Status       string             `json:"status"`
	UpdatedSince pgtype.Timestamptz `json:"updated_since"`
	LimitCount   int32              `json:"limit_count"`
	OffsetCount  int32              `json:"offset_count"`
}

// ListTasksByProjectPaged backs the AI-facing bulk context endpoint (GET
// /api/v1/projects/{projectID}/tasks/context, docs/plans/issue-sync.md
// "AI-facing"): the same backlog_id/status filters as ListTasksByProject
// plus updated_since (tasks.updated_at >= the given time) and LIMIT/OFFSET
// paging, following the "fetch one extra row to detect a next page"
// convention ListWebhookEventsByLinkedGitlabProjectID/internal/webhookevent
// established. It has no "unassigned" filter — the bulk context view has no
// use for it yet, unlike the board view ListTasksByProject serves.
func (q *Queries) ListTasksByProjectPaged(ctx context.Context, arg ListTasksByProjectPagedParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByProjectPaged,
		arg.ProjectID,
		arg.BacklogID,
		arg.Status,
		arg.UpdatedSince,
		arg.LimitCount,
		arg.OffsetCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.BacklogID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.ClosedAt,
			&i.AssigneeGitlabUserID,
			&i.AssigneeGitlabUsername,
			&i.Labels,
			&i.DueOn,
			&i.StartDate,
			&i.Priority,
			&i.Position,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksForOwner = `-- name: ListTasksForOwner :many

SELECT t.id, t.project_id, t.backlog_id, t.title, t.description, t.status, t.closed_at,
       t.assignee_gitlab_user_id, t.assignee_gitlab_username, t.labels, t.due_on, t.start_date,
       t.priority, t.position, t.created_by_user_id, t.created_at, t.updated_at,
       p.name AS project_name
FROM tasks t
JOIN projects p ON p.id = t.project_id
WHERE p.owner_user_id = $1
  AND ($2::text = '' OR t.status = $2)
  AND ($3::text = '' OR t.priority = $3)
  AND ($4::date IS NULL OR t.due_on <= $4)
  AND ($5::date IS NULL OR t.due_on >= $5)
  AND ($6::date IS NULL OR t.start_date <= $6)
  AND (cardinality($7::uuid[]) = 0 OR t.project_id = ANY($7::uuid[]))
ORDER BY
  (CASE WHEN $8::text = 'priority' THEN
     CASE t.priority WHEN 'urgent' THEN 4 WHEN 'high' THEN 3 WHEN 'medium' THEN 2 WHEN 'low' THEN 1 ELSE 0 END
   END) DESC,
  (CASE WHEN $8::text = 'updatedAt' THEN t.updated_at END) DESC,
  t.due_on ASC,
  t.position ASC, t.created_at ASC
LIMIT $9
`

type ListTasksForOwnerParams struct {
	OwnerUserID   uuid.UUID   `json:"owner_user_id"`
	Status        string      `json:"status"`
	Priority      string      `json:"priority"`
	DueBefore     pgtype.Date `json:"due_before"`
	DueAfter      pgtype.Date `json:"due_after"`
	StartedBefore pgtype.Date `json:"started_before"`
	ProjectIds    []uuid.UUID `json:"project_ids"`
	Sort          string      `json:"sort"`
	LimitCount    int32       `json:"limit_count"`
}

type ListTasksForOwnerRow struct {
	ID                     uuid.UUID          `json:"id"`
	ProjectID              uuid.UUID          `json:"project_id"`
	BacklogID              pgtype.UUID        `json:"backlog_id"`
	Title                  string             `json:"title"`
	Description            string             `json:"description"`
	Status                 string             `json:"status"`
	ClosedAt               pgtype.Timestamptz `json:"closed_at"`
	AssigneeGitlabUserID   pgtype.Int8        `json:"assignee_gitlab_user_id"`
	AssigneeGitlabUsername string             `json:"assignee_gitlab_username"`
	Labels                 []string           `json:"labels"`
	DueOn                  pgtype.Date        `json:"due_on"`
	StartDate              pgtype.Date        `json:"start_date"`
	Priority               string             `json:"priority"`
	Position               int32              `json:"position"`
	CreatedByUserID        uuid.UUID          `json:"created_by_user_id"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	ProjectName            string             `json:"project_name"`
}

// ListTasksForOwner backs the cross-project task collection (GET
// /api/v1/tasks, issue #76): every task across every project ownerID owns,
// narrowed by the same status/priority filters as ListTasksByProject plus
// due/start date ranges and an optional project_id allowlist — each
// following the same "empty/NULL disables it" convention. project_name is
// joined in for the same reason GetTaskGitlabLinkWithProjectPathByTaskID
// joins in path_with_namespace: a cross-project row is unreadable without
// knowing which project it belongs to, and a second per-row fetch would
// cost the same round trip anyway.
//
// The ORDER BY leans on two properties: sqlc.arg(sort) is a single bound
// value for the whole query, not a per-row one, so a CASE guarded by it is
// either non-NULL for every row or NULL for every row — never a mix: sort
// values not being ranked stay a true tie and fall through instead of
// corrupting the row order. And due_on ASC's default NULLS LAST (Postgres
// sorts NULL last on ASC, first on DESC) is exactly "tasks with no due date
// sink to the bottom", so it works unguarded both as sort=dueOn's primary
// key and as every other sort's final tiebreak.
func (q *Queries) ListTasksForOwner(ctx context.Context, arg ListTasksForOwnerParams) ([]ListTasksForOwnerRow, error) {
	rows, err := q.db.Query(ctx, listTasksForOwner,
		arg.OwnerUserID,
		arg.Status,
		arg.Priority,
		arg.DueBefore,
		arg.DueAfter,
		arg.StartedBefore,
		arg.ProjectIds,
		arg.Sort,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTasksForOwnerRow{}
	for rows.Next() {
		var i ListTasksForOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.BacklogID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.ClosedAt,
			&i.AssigneeGitlabUserID,
			&i.AssigneeGitlabUsername,
			&i.Labels,
			&i.DueOn,
			&i.StartDate,
			&i.Priority,
			&i.Position,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reopenTaskForOwner = `-- name: ReopenTaskForOwner :one
UPDATE tasks t
SET status = 'open', closed_at = NULL, updated_at = now()
FROM projects p
WHERE t.id = $1 AND t.project_id = p.id AND p.owner_user_id = $2
RETURNING t.id, t.project_id, t.backlog_id, t.title, t.description, t.status, t.closed_at, t.assignee_gitlab_user_id, t.assignee_gitlab_username, t.labels, t.due_on, t.start_date, t.priority, t.position, t.created_by_user_id, t.created_at, t.updated_at
`

type ReopenTaskForOwnerParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) ReopenTaskForOwner(ctx context.Context, arg ReopenTaskForOwnerParams) (Task, error) {
	row := q.db.QueryRow(ctx, reopenTaskForOwner, arg.ID, arg.OwnerUserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BacklogID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.ClosedAt,
		&i.AssigneeGitlabUserID,
		&i.AssigneeGitlabUsername,
		&i.Labels,
		&i.DueOn,
		&i.StartDate,
		&i.Priority,
		&i.Position,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reorderTasks = `-- name: ReorderTasks :exec

WITH ordered AS (
    SELECT id, (ord - 1)::int AS position
    FROM unnest($1::uuid[]) WITH ORDINALITY AS t(id, ord)
)
UPDATE tasks
SET position = ordered.position, updated_at = now()
FROM ordered
WHERE tasks.id = ordered.id
  AND tasks.project_id = $2
  AND tasks.backlog_id IS NOT DISTINCT FROM $3
`

type ReorderTasksParams struct {
	TaskIds   []uuid.UUID `json:"task_ids"`
	ProjectID uuid.UUID   `json:"project_id"`
	BacklogID pgtype.UUID `json:"backlog_id"`
}

// ReorderTasks resequences one backlog bucket's tasks to task_ids' given
// order (position 0 for the first id, 1 for the second, ...) in a single
// statement, so a drag across many tasks either lands as one committed order
// or fails outright, never a partially-applied one (issue #79). backlog_id
// follows CreateTask's own "IS NOT DISTINCT FROM" convention: NULL scopes to
// the Unclassified bucket, a UUID to one specific backlog.
// internal/task.Service.Reorder checks task_ids is exactly that bucket's
// current task set before calling this, so the WHERE clause can never miss a
// row or touch one outside the intended bucket.
func (q *Queries) ReorderTasks(ctx context.Context, arg ReorderTasksParams) error {
	_, err := q.db.Exec(ctx, reorderTasks, arg.TaskIds, arg.ProjectID, arg.BacklogID)
	return err
}

const updateTaskForOwner = `-- name: UpdateTaskForOwner :one
UPDATE tasks t
SET backlog_id = $3, title = $4, description = $5,
    assignee_gitlab_user_id = $6, assignee_gitlab_username = $7,
    labels = $8, due_on = $9, start_date = $10, priority = $11, position = $12, updated_at = now()
FROM projects p
WHERE t.id = $1 AND t.project_id = p.id AND p.owner_user_id = $2
RETURNING t.id, t.project_id, t.backlog_id, t.title, t.description, t.status, t.closed_at, t.assignee_gitlab_user_id, t.assignee_gitlab_username, t.labels, t.due_on, t.start_date, t.priority, t.position, t.created_by_user_id, t.created_at, t.updated_at
`

type UpdateTaskForOwnerParams struct {
	ID                     uuid.UUID   `json:"id"`
	OwnerUserID            uuid.UUID   `json:"owner_user_id"`
	BacklogID              pgtype.UUID `json:"backlog_id"`
	Title                  string      `json:"title"`
	Description            string      `json:"description"`
	AssigneeGitlabUserID   pgtype.Int8 `json:"assignee_gitlab_user_id"`
	AssigneeGitlabUsername string      `json:"assignee_gitlab_username"`
	Labels                 []string    `json:"labels"`
	DueOn                  pgtype.Date `json:"due_on"`
	StartDate              pgtype.Date `json:"start_date"`
	Priority               string      `json:"priority"`
	Position               int32       `json:"position"`
}

func (q *Queries) UpdateTaskForOwner(ctx context.Context, arg UpdateTaskForOwnerParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskForOwner,
		arg.ID,
		arg.OwnerUserID,
		arg.BacklogID,
		arg.Title,
		arg.Description,
		arg.AssigneeGitlabUserID,
		arg.AssigneeGitlabUsername,
		arg.Labels,
		arg.DueOn,
		arg.StartDate,
		arg.Priority,
		arg.Position,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BacklogID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.ClosedAt,
		&i.AssigneeGitlabUserID,
		&i.AssigneeGitlabUsername,
		&i.Labels,
		&i.DueOn,
		&i.StartDate,
		&i.Priority,
		&i.Position,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
