// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignTaskBacklogForOwner = `-- name: AssignTaskBacklogForOwner :one
UPDATE tasks t
SET backlog_id = $3, updated_at = now()
FROM projects p
WHERE t.id = $1 AND t.project_id = p.id AND p.owner_user_id = $2
RETURNING t.id, t.project_id, t.backlog_id, t.title, t.description, t.status, t.closed_at, t.assignee_gitlab_user_id, t.assignee_gitlab_username, t.labels, t.due_on, t.position, t.created_by_user_id, t.created_at, t.updated_at
`

type AssignTaskBacklogForOwnerParams struct {
	ID          uuid.UUID   `json:"id"`
	OwnerUserID uuid.UUID   `json:"owner_user_id"`
	BacklogID   pgtype.UUID `json:"backlog_id"`
}

func (q *Queries) AssignTaskBacklogForOwner(ctx context.Context, arg AssignTaskBacklogForOwnerParams) (Task, error) {
	row := q.db.QueryRow(ctx, assignTaskBacklogForOwner, arg.ID, arg.OwnerUserID, arg.BacklogID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BacklogID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.ClosedAt,
		&i.AssigneeGitlabUserID,
		&i.AssigneeGitlabUsername,
		&i.Labels,
		&i.DueOn,
		&i.Position,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const closeTaskForOwner = `-- name: CloseTaskForOwner :one
UPDATE tasks t
SET status = 'closed', closed_at = now(), updated_at = now()
FROM projects p
WHERE t.id = $1 AND t.project_id = p.id AND p.owner_user_id = $2
RETURNING t.id, t.project_id, t.backlog_id, t.title, t.description, t.status, t.closed_at, t.assignee_gitlab_user_id, t.assignee_gitlab_username, t.labels, t.due_on, t.position, t.created_by_user_id, t.created_at, t.updated_at
`

type CloseTaskForOwnerParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) CloseTaskForOwner(ctx context.Context, arg CloseTaskForOwnerParams) (Task, error) {
	row := q.db.QueryRow(ctx, closeTaskForOwner, arg.ID, arg.OwnerUserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BacklogID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.ClosedAt,
		&i.AssigneeGitlabUserID,
		&i.AssigneeGitlabUsername,
		&i.Labels,
		&i.DueOn,
		&i.Position,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one

INSERT INTO tasks (
    project_id, backlog_id, title, description,
    assignee_gitlab_user_id, assignee_gitlab_username,
    labels, due_on, created_by_user_id, position
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    COALESCE((SELECT MAX(position) + 1 FROM tasks WHERE project_id = $1 AND backlog_id IS NOT DISTINCT FROM $2), 0)
)
RETURNING id, project_id, backlog_id, title, description, status, closed_at, assignee_gitlab_user_id, assignee_gitlab_username, labels, due_on, position, created_by_user_id, created_at, updated_at
`

type CreateTaskParams struct {
	ProjectID              uuid.UUID   `json:"project_id"`
	BacklogID              pgtype.UUID `json:"backlog_id"`
	Title                  string      `json:"title"`
	Description            string      `json:"description"`
	AssigneeGitlabUserID   pgtype.Int8 `json:"assignee_gitlab_user_id"`
	AssigneeGitlabUsername string      `json:"assignee_gitlab_username"`
	Labels                 []string    `json:"labels"`
	DueOn                  pgtype.Date `json:"due_on"`
	CreatedByUserID        uuid.UUID   `json:"created_by_user_id"`
}

// Tasks are scoped through their parent project the same way backlogs are:
// every single-task query joins to projects and filters on
// owner_user_id, so a foreign task is indistinguishable from a missing one.
// CreateTask trusts the caller to have already verified project ownership
// (e.g. via project.Service.Get), like CreateBacklog.
//
// ListTasksByProject takes three independent optional filters so one query
// serves the unfiltered, single-backlog, unassigned-only and status-scoped
// list views: passing false/NULL/” for a filter disables it.
func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ProjectID,
		arg.BacklogID,
		arg.Title,
		arg.Description,
		arg.AssigneeGitlabUserID,
		arg.AssigneeGitlabUsername,
		arg.Labels,
		arg.DueOn,
		arg.CreatedByUserID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BacklogID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.ClosedAt,
		&i.AssigneeGitlabUserID,
		&i.AssigneeGitlabUsername,
		&i.Labels,
		&i.DueOn,
		&i.Position,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTaskForOwner = `-- name: DeleteTaskForOwner :execrows
DELETE FROM tasks t
USING projects p
WHERE t.id = $1 AND t.project_id = p.id AND p.owner_user_id = $2
`

type DeleteTaskForOwnerParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) DeleteTaskForOwner(ctx context.Context, arg DeleteTaskForOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTaskForOwner, arg.ID, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTaskForOwner = `-- name: GetTaskForOwner :one
SELECT t.id, t.project_id, t.backlog_id, t.title, t.description, t.status, t.closed_at, t.assignee_gitlab_user_id, t.assignee_gitlab_username, t.labels, t.due_on, t.position, t.created_by_user_id, t.created_at, t.updated_at
FROM tasks t
JOIN projects p ON p.id = t.project_id
WHERE t.id = $1 AND p.owner_user_id = $2
`

type GetTaskForOwnerParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) GetTaskForOwner(ctx context.Context, arg GetTaskForOwnerParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskForOwner, arg.ID, arg.OwnerUserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BacklogID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.ClosedAt,
		&i.AssigneeGitlabUserID,
		&i.AssigneeGitlabUsername,
		&i.Labels,
		&i.DueOn,
		&i.Position,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasksByProject = `-- name: ListTasksByProject :many
SELECT id, project_id, backlog_id, title, description, status, closed_at, assignee_gitlab_user_id, assignee_gitlab_username, labels, due_on, position, created_by_user_id, created_at, updated_at
FROM tasks
WHERE project_id = $1
  AND (NOT $2::boolean OR backlog_id IS NULL)
  AND ($3::uuid IS NULL OR backlog_id = $3)
  AND ($4::text = '' OR status = $4)
ORDER BY position ASC, created_at ASC
`

type ListTasksByProjectParams struct {
	ProjectID  uuid.UUID   `json:"project_id"`
	Unassigned bool        `json:"unassigned"`
	BacklogID  pgtype.UUID `json:"backlog_id"`
	Status     string      `json:"status"`
}

func (q *Queries) ListTasksByProject(ctx context.Context, arg ListTasksByProjectParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByProject,
		arg.ProjectID,
		arg.Unassigned,
		arg.BacklogID,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.BacklogID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.ClosedAt,
			&i.AssigneeGitlabUserID,
			&i.AssigneeGitlabUsername,
			&i.Labels,
			&i.DueOn,
			&i.Position,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reopenTaskForOwner = `-- name: ReopenTaskForOwner :one
UPDATE tasks t
SET status = 'open', closed_at = NULL, updated_at = now()
FROM projects p
WHERE t.id = $1 AND t.project_id = p.id AND p.owner_user_id = $2
RETURNING t.id, t.project_id, t.backlog_id, t.title, t.description, t.status, t.closed_at, t.assignee_gitlab_user_id, t.assignee_gitlab_username, t.labels, t.due_on, t.position, t.created_by_user_id, t.created_at, t.updated_at
`

type ReopenTaskForOwnerParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) ReopenTaskForOwner(ctx context.Context, arg ReopenTaskForOwnerParams) (Task, error) {
	row := q.db.QueryRow(ctx, reopenTaskForOwner, arg.ID, arg.OwnerUserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BacklogID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.ClosedAt,
		&i.AssigneeGitlabUserID,
		&i.AssigneeGitlabUsername,
		&i.Labels,
		&i.DueOn,
		&i.Position,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskForOwner = `-- name: UpdateTaskForOwner :one
UPDATE tasks t
SET backlog_id = $3, title = $4, description = $5,
    assignee_gitlab_user_id = $6, assignee_gitlab_username = $7,
    labels = $8, due_on = $9, position = $10, updated_at = now()
FROM projects p
WHERE t.id = $1 AND t.project_id = p.id AND p.owner_user_id = $2
RETURNING t.id, t.project_id, t.backlog_id, t.title, t.description, t.status, t.closed_at, t.assignee_gitlab_user_id, t.assignee_gitlab_username, t.labels, t.due_on, t.position, t.created_by_user_id, t.created_at, t.updated_at
`

type UpdateTaskForOwnerParams struct {
	ID                     uuid.UUID   `json:"id"`
	OwnerUserID            uuid.UUID   `json:"owner_user_id"`
	BacklogID              pgtype.UUID `json:"backlog_id"`
	Title                  string      `json:"title"`
	Description            string      `json:"description"`
	AssigneeGitlabUserID   pgtype.Int8 `json:"assignee_gitlab_user_id"`
	AssigneeGitlabUsername string      `json:"assignee_gitlab_username"`
	Labels                 []string    `json:"labels"`
	DueOn                  pgtype.Date `json:"due_on"`
	Position               int32       `json:"position"`
}

func (q *Queries) UpdateTaskForOwner(ctx context.Context, arg UpdateTaskForOwnerParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskForOwner,
		arg.ID,
		arg.OwnerUserID,
		arg.BacklogID,
		arg.Title,
		arg.Description,
		arg.AssigneeGitlabUserID,
		arg.AssigneeGitlabUsername,
		arg.Labels,
		arg.DueOn,
		arg.Position,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BacklogID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.ClosedAt,
		&i.AssigneeGitlabUserID,
		&i.AssigneeGitlabUsername,
		&i.Labels,
		&i.DueOn,
		&i.Position,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
