// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_progress_events.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTaskProgressEvent = `-- name: CreateTaskProgressEvent :one
INSERT INTO task_progress_events (task_id, from_progress, to_progress, actor_kind, actor_user_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, task_id, from_progress, to_progress, actor_kind, actor_user_id, occurred_at
`

type CreateTaskProgressEventParams struct {
	TaskID       uuid.UUID   `json:"task_id"`
	FromProgress string      `json:"from_progress"`
	ToProgress   string      `json:"to_progress"`
	ActorKind    string      `json:"actor_kind"`
	ActorUserID  pgtype.UUID `json:"actor_user_id"`
}

func (q *Queries) CreateTaskProgressEvent(ctx context.Context, arg CreateTaskProgressEventParams) (TaskProgressEvent, error) {
	row := q.db.QueryRow(ctx, createTaskProgressEvent,
		arg.TaskID,
		arg.FromProgress,
		arg.ToProgress,
		arg.ActorKind,
		arg.ActorUserID,
	)
	var i TaskProgressEvent
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.FromProgress,
		&i.ToProgress,
		&i.ActorKind,
		&i.ActorUserID,
		&i.OccurredAt,
	)
	return i, err
}

const listTaskProgressEventsByTask = `-- name: ListTaskProgressEventsByTask :many
SELECT id, task_id, from_progress, to_progress, actor_kind, actor_user_id, occurred_at FROM task_progress_events WHERE task_id = $1 ORDER BY occurred_at ASC
`

func (q *Queries) ListTaskProgressEventsByTask(ctx context.Context, taskID uuid.UUID) ([]TaskProgressEvent, error) {
	rows, err := q.db.Query(ctx, listTaskProgressEventsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskProgressEvent{}
	for rows.Next() {
		var i TaskProgressEvent
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.FromProgress,
			&i.ToProgress,
			&i.ActorKind,
			&i.ActorUserID,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
