// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_comments.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createGitlabTaskComment = `-- name: CreateGitlabTaskComment :one

INSERT INTO task_comments (task_id, author_kind, body, gitlab_note_id)
VALUES ($1, 'gitlab', $2, $3)
RETURNING id, task_id, author_user_id, author_token_id, author_kind, body, created_at, updated_at, gitlab_note_id
`

type CreateGitlabTaskCommentParams struct {
	TaskID       uuid.UUID   `json:"task_id"`
	Body         string      `json:"body"`
	GitlabNoteID pgtype.Int8 `json:"gitlab_note_id"`
}

// CreateGitlabTaskComment inserts a comment mirrored in from an inbound
// GitLab "Note Hook" webhook (#104): author_kind is always 'gitlab' and
// gitlab_note_id is always set, so a later delivery of the same note can be
// recognised via GetTaskCommentByGitlabNoteID rather than re-inserted.
func (q *Queries) CreateGitlabTaskComment(ctx context.Context, arg CreateGitlabTaskCommentParams) (TaskComment, error) {
	row := q.db.QueryRow(ctx, createGitlabTaskComment, arg.TaskID, arg.Body, arg.GitlabNoteID)
	var i TaskComment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.AuthorUserID,
		&i.AuthorTokenID,
		&i.AuthorKind,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GitlabNoteID,
	)
	return i, err
}

const createTaskComment = `-- name: CreateTaskComment :one
INSERT INTO task_comments (task_id, author_user_id, author_token_id, author_kind, body)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, task_id, author_user_id, author_token_id, author_kind, body, created_at, updated_at, gitlab_note_id
`

type CreateTaskCommentParams struct {
	TaskID        uuid.UUID   `json:"task_id"`
	AuthorUserID  pgtype.UUID `json:"author_user_id"`
	AuthorTokenID pgtype.UUID `json:"author_token_id"`
	AuthorKind    string      `json:"author_kind"`
	Body          string      `json:"body"`
}

func (q *Queries) CreateTaskComment(ctx context.Context, arg CreateTaskCommentParams) (TaskComment, error) {
	row := q.db.QueryRow(ctx, createTaskComment,
		arg.TaskID,
		arg.AuthorUserID,
		arg.AuthorTokenID,
		arg.AuthorKind,
		arg.Body,
	)
	var i TaskComment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.AuthorUserID,
		&i.AuthorTokenID,
		&i.AuthorKind,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GitlabNoteID,
	)
	return i, err
}

const deleteTaskCommentByID = `-- name: DeleteTaskCommentByID :execrows
DELETE FROM task_comments WHERE id = $1
`

func (q *Queries) DeleteTaskCommentByID(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTaskCommentByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTaskCommentByGitlabNoteID = `-- name: GetTaskCommentByGitlabNoteID :one
SELECT id, task_id, author_user_id, author_token_id, author_kind, body, created_at, updated_at, gitlab_note_id FROM task_comments WHERE gitlab_note_id = $1
`

func (q *Queries) GetTaskCommentByGitlabNoteID(ctx context.Context, gitlabNoteID pgtype.Int8) (TaskComment, error) {
	row := q.db.QueryRow(ctx, getTaskCommentByGitlabNoteID, gitlabNoteID)
	var i TaskComment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.AuthorUserID,
		&i.AuthorTokenID,
		&i.AuthorKind,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GitlabNoteID,
	)
	return i, err
}

const getTaskCommentByID = `-- name: GetTaskCommentByID :one
SELECT id, task_id, author_user_id, author_token_id, author_kind, body, created_at, updated_at, gitlab_note_id FROM task_comments WHERE id = $1
`

func (q *Queries) GetTaskCommentByID(ctx context.Context, id uuid.UUID) (TaskComment, error) {
	row := q.db.QueryRow(ctx, getTaskCommentByID, id)
	var i TaskComment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.AuthorUserID,
		&i.AuthorTokenID,
		&i.AuthorKind,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GitlabNoteID,
	)
	return i, err
}

const getTaskCommentProjectID = `-- name: GetTaskCommentProjectID :one

SELECT t.project_id
FROM task_comments tc
JOIN tasks t ON t.id = tc.task_id
WHERE tc.id = $1
`

// GetTaskCommentProjectID is the lightweight project lookup
// requireTokenResourceProject (internal/http, issue #66) uses to enforce a
// bearer token's project boundary on a single-comment URL, resolved through
// the comment's task, the same way GetTaskDependencyProjectID resolves
// through a dependency's predecessor task.
func (q *Queries) GetTaskCommentProjectID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getTaskCommentProjectID, id)
	var project_id uuid.UUID
	err := row.Scan(&project_id)
	return project_id, err
}

const listTaskCommentsByTask = `-- name: ListTaskCommentsByTask :many
SELECT id, task_id, author_user_id, author_token_id, author_kind, body, created_at, updated_at, gitlab_note_id FROM task_comments WHERE task_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListTaskCommentsByTask(ctx context.Context, taskID uuid.UUID) ([]TaskComment, error) {
	rows, err := q.db.Query(ctx, listTaskCommentsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskComment{}
	for rows.Next() {
		var i TaskComment
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.AuthorUserID,
			&i.AuthorTokenID,
			&i.AuthorKind,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GitlabNoteID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTaskCommentGitlabNoteID = `-- name: SetTaskCommentGitlabNoteID :exec
UPDATE task_comments SET gitlab_note_id = $2, updated_at = now() WHERE id = $1
`

type SetTaskCommentGitlabNoteIDParams struct {
	ID           uuid.UUID   `json:"id"`
	GitlabNoteID pgtype.Int8 `json:"gitlab_note_id"`
}

func (q *Queries) SetTaskCommentGitlabNoteID(ctx context.Context, arg SetTaskCommentGitlabNoteIDParams) error {
	_, err := q.db.Exec(ctx, setTaskCommentGitlabNoteID, arg.ID, arg.GitlabNoteID)
	return err
}
