// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_gitlab_links.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTaskGitlabLink = `-- name: CreateTaskGitlabLink :one

INSERT INTO task_gitlab_links (
    task_id, linked_gitlab_project_id, gitlab_issue_id, gitlab_issue_iid,
    gitlab_web_url, gitlab_updated_at, last_pushed_fingerprint, sync_status, last_synced_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, 'synced', now()
)
RETURNING task_id, linked_gitlab_project_id, gitlab_issue_id, gitlab_issue_iid, gitlab_web_url, gitlab_updated_at, last_pushed_fingerprint, sync_status, last_error, last_synced_at
`

type CreateTaskGitlabLinkParams struct {
	TaskID                uuid.UUID          `json:"task_id"`
	LinkedGitlabProjectID uuid.UUID          `json:"linked_gitlab_project_id"`
	GitlabIssueID         int64              `json:"gitlab_issue_id"`
	GitlabIssueIid        int64              `json:"gitlab_issue_iid"`
	GitlabWebUrl          string             `json:"gitlab_web_url"`
	GitlabUpdatedAt       pgtype.Timestamptz `json:"gitlab_updated_at"`
	LastPushedFingerprint string             `json:"last_pushed_fingerprint"`
}

// task_gitlab_links has no owner column and is never queried through a
// project/owner join: only the outbox worker (internal/issuesync) reads and
// writes it, and the job row that drives it was already authorized when
// internal/task enqueued it in the same transaction as the task write. See
// docs/plans/issue-sync.md, "Outbound".
func (q *Queries) CreateTaskGitlabLink(ctx context.Context, arg CreateTaskGitlabLinkParams) (TaskGitlabLink, error) {
	row := q.db.QueryRow(ctx, createTaskGitlabLink,
		arg.TaskID,
		arg.LinkedGitlabProjectID,
		arg.GitlabIssueID,
		arg.GitlabIssueIid,
		arg.GitlabWebUrl,
		arg.GitlabUpdatedAt,
		arg.LastPushedFingerprint,
	)
	var i TaskGitlabLink
	err := row.Scan(
		&i.TaskID,
		&i.LinkedGitlabProjectID,
		&i.GitlabIssueID,
		&i.GitlabIssueIid,
		&i.GitlabWebUrl,
		&i.GitlabUpdatedAt,
		&i.LastPushedFingerprint,
		&i.SyncStatus,
		&i.LastError,
		&i.LastSyncedAt,
	)
	return i, err
}

const getTaskGitlabLinkByTaskID = `-- name: GetTaskGitlabLinkByTaskID :one
SELECT task_id, linked_gitlab_project_id, gitlab_issue_id, gitlab_issue_iid, gitlab_web_url, gitlab_updated_at, last_pushed_fingerprint, sync_status, last_error, last_synced_at
FROM task_gitlab_links
WHERE task_id = $1
`

func (q *Queries) GetTaskGitlabLinkByTaskID(ctx context.Context, taskID uuid.UUID) (TaskGitlabLink, error) {
	row := q.db.QueryRow(ctx, getTaskGitlabLinkByTaskID, taskID)
	var i TaskGitlabLink
	err := row.Scan(
		&i.TaskID,
		&i.LinkedGitlabProjectID,
		&i.GitlabIssueID,
		&i.GitlabIssueIid,
		&i.GitlabWebUrl,
		&i.GitlabUpdatedAt,
		&i.LastPushedFingerprint,
		&i.SyncStatus,
		&i.LastError,
		&i.LastSyncedAt,
	)
	return i, err
}

const markTaskGitlabLinkFailedForTask = `-- name: MarkTaskGitlabLinkFailedForTask :one
UPDATE task_gitlab_links
SET sync_status = 'failed',
    last_error = $2
WHERE task_id = $1
RETURNING task_id, linked_gitlab_project_id, gitlab_issue_id, gitlab_issue_iid, gitlab_web_url, gitlab_updated_at, last_pushed_fingerprint, sync_status, last_error, last_synced_at
`

type MarkTaskGitlabLinkFailedForTaskParams struct {
	TaskID    uuid.UUID `json:"task_id"`
	LastError string    `json:"last_error"`
}

func (q *Queries) MarkTaskGitlabLinkFailedForTask(ctx context.Context, arg MarkTaskGitlabLinkFailedForTaskParams) (TaskGitlabLink, error) {
	row := q.db.QueryRow(ctx, markTaskGitlabLinkFailedForTask, arg.TaskID, arg.LastError)
	var i TaskGitlabLink
	err := row.Scan(
		&i.TaskID,
		&i.LinkedGitlabProjectID,
		&i.GitlabIssueID,
		&i.GitlabIssueIid,
		&i.GitlabWebUrl,
		&i.GitlabUpdatedAt,
		&i.LastPushedFingerprint,
		&i.SyncStatus,
		&i.LastError,
		&i.LastSyncedAt,
	)
	return i, err
}

const markTaskGitlabLinkSyncedForTask = `-- name: MarkTaskGitlabLinkSyncedForTask :one
UPDATE task_gitlab_links
SET gitlab_updated_at = $2,
    last_pushed_fingerprint = $3,
    sync_status = 'synced',
    last_error = '',
    last_synced_at = now()
WHERE task_id = $1
RETURNING task_id, linked_gitlab_project_id, gitlab_issue_id, gitlab_issue_iid, gitlab_web_url, gitlab_updated_at, last_pushed_fingerprint, sync_status, last_error, last_synced_at
`

type MarkTaskGitlabLinkSyncedForTaskParams struct {
	TaskID                uuid.UUID          `json:"task_id"`
	GitlabUpdatedAt       pgtype.Timestamptz `json:"gitlab_updated_at"`
	LastPushedFingerprint string             `json:"last_pushed_fingerprint"`
}

func (q *Queries) MarkTaskGitlabLinkSyncedForTask(ctx context.Context, arg MarkTaskGitlabLinkSyncedForTaskParams) (TaskGitlabLink, error) {
	row := q.db.QueryRow(ctx, markTaskGitlabLinkSyncedForTask, arg.TaskID, arg.GitlabUpdatedAt, arg.LastPushedFingerprint)
	var i TaskGitlabLink
	err := row.Scan(
		&i.TaskID,
		&i.LinkedGitlabProjectID,
		&i.GitlabIssueID,
		&i.GitlabIssueIid,
		&i.GitlabWebUrl,
		&i.GitlabUpdatedAt,
		&i.LastPushedFingerprint,
		&i.SyncStatus,
		&i.LastError,
		&i.LastSyncedAt,
	)
	return i, err
}
