// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_dependencies.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createTaskDependency = `-- name: CreateTaskDependency :one

INSERT INTO task_dependencies (predecessor_task_id, successor_task_id)
VALUES ($1, $2)
RETURNING id, predecessor_task_id, successor_task_id, created_at
`

type CreateTaskDependencyParams struct {
	PredecessorTaskID uuid.UUID `json:"predecessor_task_id"`
	SuccessorTaskID   uuid.UUID `json:"successor_task_id"`
}

// task_dependencies has no project_id/owner column of its own; ownership is
// always checked through its tasks, the same way task_gitlab_links is never
// queried through a project/owner join directly. CreateTaskDependency and
// ListTaskDependenciesByProject trust the caller (internal/taskdependency) to
// have already verified project ownership and that both tasks belong to the
// same project, the same way CreateTask trusts an already-verified project.
// DeleteTaskDependencyForOwner joins through the predecessor task to
// projects, so a dependency belonging to another user's project is
// indistinguishable from a missing one.
func (q *Queries) CreateTaskDependency(ctx context.Context, arg CreateTaskDependencyParams) (TaskDependency, error) {
	row := q.db.QueryRow(ctx, createTaskDependency, arg.PredecessorTaskID, arg.SuccessorTaskID)
	var i TaskDependency
	err := row.Scan(
		&i.ID,
		&i.PredecessorTaskID,
		&i.SuccessorTaskID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTaskDependencyForOwner = `-- name: DeleteTaskDependencyForOwner :execrows
DELETE FROM task_dependencies td
USING tasks t
WHERE td.id = $1 AND t.id = td.predecessor_task_id
  AND EXISTS (
    SELECT 1 FROM project_members pm
    WHERE pm.project_id = t.project_id AND pm.user_id = $2
  )
`

type DeleteTaskDependencyForOwnerParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) DeleteTaskDependencyForOwner(ctx context.Context, arg DeleteTaskDependencyForOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTaskDependencyForOwner, arg.ID, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTaskDependencyProjectID = `-- name: GetTaskDependencyProjectID :one

SELECT t.project_id
FROM task_dependencies td
JOIN tasks t ON t.id = td.predecessor_task_id
WHERE td.id = $1
`

// GetTaskDependencyProjectID is the lightweight project lookup
// requireTokenResourceProject (internal/http, issue #66) uses to enforce a
// bearer token's project boundary on a single-dependency URL: resolved
// through the predecessor task, the same way DeleteTaskDependencyForOwner
// resolves ownership.
func (q *Queries) GetTaskDependencyProjectID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getTaskDependencyProjectID, id)
	var project_id uuid.UUID
	err := row.Scan(&project_id)
	return project_id, err
}

const listTaskDependenciesByProject = `-- name: ListTaskDependenciesByProject :many
SELECT td.id, td.predecessor_task_id, td.successor_task_id, td.created_at
FROM task_dependencies td
JOIN tasks t ON t.id = td.predecessor_task_id
WHERE t.project_id = $1
ORDER BY td.created_at ASC
`

func (q *Queries) ListTaskDependenciesByProject(ctx context.Context, projectID uuid.UUID) ([]TaskDependency, error) {
	rows, err := q.db.Query(ctx, listTaskDependenciesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskDependency{}
	for rows.Next() {
		var i TaskDependency
		if err := rows.Scan(
			&i.ID,
			&i.PredecessorTaskID,
			&i.SuccessorTaskID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
