// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, github_user_id, github_login, display_name, avatar_url, encrypted_access_token, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubUserID,
		&i.GithubLogin,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.EncryptedAccessToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (
    github_user_id, github_login, display_name, avatar_url, encrypted_access_token
) VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (github_user_id) DO UPDATE SET
    github_login           = EXCLUDED.github_login,
    display_name           = EXCLUDED.display_name,
    avatar_url             = EXCLUDED.avatar_url,
    encrypted_access_token = EXCLUDED.encrypted_access_token,
    updated_at             = now()
RETURNING id, github_user_id, github_login, display_name, avatar_url, encrypted_access_token, created_at, updated_at
`

type UpsertUserParams struct {
	GithubUserID         int64  `json:"github_user_id"`
	GithubLogin          string `json:"github_login"`
	DisplayName          string `json:"display_name"`
	AvatarUrl            string `json:"avatar_url"`
	EncryptedAccessToken []byte `json:"encrypted_access_token"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.GithubUserID,
		arg.GithubLogin,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.EncryptedAccessToken,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubUserID,
		&i.GithubLogin,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.EncryptedAccessToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
