// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook_events.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createWebhookEvent = `-- name: CreateWebhookEvent :one

INSERT INTO webhook_events (
    linked_gitlab_project_id, delivery_uuid, event_name, object_kind,
    gitlab_issue_iid, payload, gitlab_updated_at, status, skip_reason
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (linked_gitlab_project_id, delivery_uuid) DO NOTHING
RETURNING id, linked_gitlab_project_id, delivery_uuid, event_name, object_kind, gitlab_issue_iid, payload, gitlab_updated_at, status, skip_reason, error_message, received_at, processed_at
`

type CreateWebhookEventParams struct {
	LinkedGitlabProjectID uuid.UUID          `json:"linked_gitlab_project_id"`
	DeliveryUuid          string             `json:"delivery_uuid"`
	EventName             string             `json:"event_name"`
	ObjectKind            string             `json:"object_kind"`
	GitlabIssueIid        pgtype.Int8        `json:"gitlab_issue_iid"`
	Payload               []byte             `json:"payload"`
	GitlabUpdatedAt       pgtype.Timestamptz `json:"gitlab_updated_at"`
	Status                string             `json:"status"`
	SkipReason            string             `json:"skip_reason"`
}

// webhook_events has no owner column and is never queried through a
// project/owner join: the linkID in the URL path (POST
// /webhooks/gitlab/{linkID}) is itself the authorization boundary, verified
// by comparing X-Gitlab-Token against the link's decrypted webhook secret in
// constant time before any of these run (see internal/webhookevent,
// ADR-0008).
//
// ON CONFLICT DO NOTHING makes a duplicate GitLab delivery (same
// linked_gitlab_project_id + delivery_uuid) a no-op instead of an error: the
// caller sees pgx.ErrNoRows and treats it the same as a fresh insert, so
// retried/duplicated deliveries are idempotent (docs/plans/issue-sync.md,
// "Inbound").
func (q *Queries) CreateWebhookEvent(ctx context.Context, arg CreateWebhookEventParams) (WebhookEvent, error) {
	row := q.db.QueryRow(ctx, createWebhookEvent,
		arg.LinkedGitlabProjectID,
		arg.DeliveryUuid,
		arg.EventName,
		arg.ObjectKind,
		arg.GitlabIssueIid,
		arg.Payload,
		arg.GitlabUpdatedAt,
		arg.Status,
		arg.SkipReason,
	)
	var i WebhookEvent
	err := row.Scan(
		&i.ID,
		&i.LinkedGitlabProjectID,
		&i.DeliveryUuid,
		&i.EventName,
		&i.ObjectKind,
		&i.GitlabIssueIid,
		&i.Payload,
		&i.GitlabUpdatedAt,
		&i.Status,
		&i.SkipReason,
		&i.ErrorMessage,
		&i.ReceivedAt,
		&i.ProcessedAt,
	)
	return i, err
}
